import { Inject, Injectable } from '@nestjs/common';
import { Kysely, sql } from 'kysely';
import { KYSELY_DB } from '../../../platform/database/database.tokens';
import { DatabaseSchema } from '../../../platform/database/database.types';
import { DatabaseExecutor } from '../../../platform/database/transaction-manager';
import { DomainError } from '../../../shared/errors/domain-error';

@Injectable()
export class InventoryRepository {
  constructor(@Inject(KYSELY_DB) private readonly db: Kysely<DatabaseSchema>) {}

  async listWarehouses(allowedWarehouseIds:string[]|null=null){const r=await sql<any>`SELECT * FROM inventory.warehouses WHERE (${allowedWarehouseIds}::uuid[] IS NULL OR id=ANY(${allowedWarehouseIds}::uuid[])) ORDER BY code`.execute(this.db);return r.rows;}
  async createWarehouse(ex:DatabaseExecutor,i:any){await sql`INSERT INTO inventory.warehouses(id,code,name_fa,warehouse_type,physical_protection_percent) VALUES(${i.id}::uuid,${i.code},${i.nameFa},${i.warehouseType},${i.protectionPercent??0})`.execute(ex);}
  async warehouse(id:string){const r=await sql<any>`SELECT * FROM inventory.warehouses WHERE id=${id}::uuid`.execute(this.db);return r.rows[0]??null;}
  async warehouseForUpdate(ex:DatabaseExecutor,id:string){const r=await sql<any>`SELECT * FROM inventory.warehouses WHERE id=${id}::uuid FOR UPDATE`.execute(ex);return r.rows[0]??null;}
  async updateWarehouseProtection(ex:DatabaseExecutor,id:string,pct:number,expected:number){const r=await sql`UPDATE inventory.warehouses SET physical_protection_percent=${pct},version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','انبار همزمان تغییر کرده است.');}

  async listBalances(variantId?:string){const r=await sql<any>`SELECT sb.*,w.code warehouse_code,w.name_fa warehouse_name,w.physical_protection_percent FROM inventory.stock_balances sb JOIN inventory.warehouses w ON w.id=sb.warehouse_id WHERE (${variantId??null}::uuid IS NULL OR sb.variant_id=${variantId??null}::uuid) ORDER BY w.code,sb.variant_id`.execute(this.db);return r.rows;}
  async lockBalance(ex:DatabaseExecutor,warehouseId:string,variantId:string){
    const wh=await sql<any>`SELECT id FROM inventory.warehouses WHERE id=${warehouseId}::uuid AND is_active=true`.execute(ex);if(!wh.rows[0])throw new DomainError('WAREHOUSE_NOT_FOUND','انبار فعال پیدا نشد.');
    let r=await sql<any>`SELECT sb.*,w.physical_protection_percent FROM inventory.stock_balances sb JOIN inventory.warehouses w ON w.id=sb.warehouse_id WHERE sb.warehouse_id=${warehouseId}::uuid AND sb.variant_id=${variantId}::uuid FOR UPDATE OF sb`.execute(ex);
    if(!r.rows[0]){await sql`INSERT INTO inventory.stock_balances(warehouse_id,variant_id) VALUES(${warehouseId}::uuid,${variantId}::uuid) ON CONFLICT DO NOTHING`.execute(ex);r=await sql<any>`SELECT sb.*,w.physical_protection_percent FROM inventory.stock_balances sb JOIN inventory.warehouses w ON w.id=sb.warehouse_id WHERE sb.warehouse_id=${warehouseId}::uuid AND sb.variant_id=${variantId}::uuid FOR UPDATE OF sb`.execute(ex);}return r.rows[0];
  }
  async updateBalance(ex:DatabaseExecutor,warehouseId:string,variantId:string,delta:{onHand?:number;reserved?:number;allocated?:number;damaged?:number;quarantine?:number}){const r=await sql`UPDATE inventory.stock_balances SET on_hand=on_hand+${delta.onHand??0},reserved=reserved+${delta.reserved??0},allocated=allocated+${delta.allocated??0},damaged=damaged+${delta.damaged??0},quarantine=quarantine+${delta.quarantine??0},version=version+1,updated_at=now() WHERE warehouse_id=${warehouseId}::uuid AND variant_id=${variantId}::uuid`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('STOCK_BALANCE_NOT_FOUND','مانده موجودی پیدا نشد.');}

  async movement(ex:DatabaseExecutor,i:any){await sql`INSERT INTO inventory.movements(id,warehouse_id,variant_id,movement_type,quantity_delta,bucket_from,bucket_to,cost_layer_id,reservation_id,allocation_id,transfer_id,return_item_id,source_event_id,reason_code,created_by) VALUES(${i.id}::uuid,${i.warehouseId}::uuid,${i.variantId}::uuid,${i.type},${i.quantityDelta},${i.bucketFrom??null},${i.bucketTo??null},${i.costLayerId??null}::uuid,${i.reservationId??null}::uuid,${i.allocationId??null}::uuid,${i.transferId??null}::uuid,${i.returnItemId??null}::uuid,${i.sourceEventId??null}::uuid,${i.reasonCode??null},${i.createdBy??null}::uuid)`.execute(ex);}
  async inventoryMovements(variantId:string,allowedWarehouseIds:string[]|null=null){const r=await sql<any>`SELECT * FROM inventory.movements WHERE variant_id=${variantId}::uuid AND (${allowedWarehouseIds}::uuid[] IS NULL OR warehouse_id=ANY(${allowedWarehouseIds}::uuid[])) ORDER BY occurred_at DESC LIMIT 500`.execute(this.db);return r.rows;}

  async insertReservation(ex:DatabaseExecutor,i:any){await sql`INSERT INTO inventory.reservations(id,cart_id,order_id,customer_id,status,expires_at,payment_grace_until) VALUES(${i.id}::uuid,${i.cartId??null}::uuid,${i.orderId??null}::uuid,${i.customerId??null}::uuid,'active',${i.expiresAt},${i.paymentGraceUntil??null})`.execute(ex);for(const x of i.items)await sql`INSERT INTO inventory.reservation_items(id,reservation_id,warehouse_id,variant_id,quantity) VALUES(${x.id}::uuid,${i.id}::uuid,${x.warehouseId}::uuid,${x.variantId}::uuid,${x.quantity})`.execute(ex);}
  async reservation(ex:DatabaseExecutor,id:string,lock=false){const r=await sql<any>`SELECT * FROM inventory.reservations WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]??null;}
  async reservationItems(ex:DatabaseExecutor,id:string){const r=await sql<any>`SELECT * FROM inventory.reservation_items WHERE reservation_id=${id}::uuid ORDER BY warehouse_id,variant_id`.execute(ex);return r.rows;}
  async reservationItemForAllocation(ex:DatabaseExecutor,reservationId:string,warehouseId:string,variantId:string){const r=await sql<any>`SELECT ri.* FROM inventory.reservation_items ri JOIN inventory.reservations r ON r.id=ri.reservation_id WHERE ri.reservation_id=${reservationId}::uuid AND ri.warehouse_id=${warehouseId}::uuid AND ri.variant_id=${variantId}::uuid AND r.status='converted' FOR UPDATE OF ri`.execute(ex);return r.rows[0]??null;}
  async addReservationAllocated(ex:DatabaseExecutor,itemId:string,q:number){const r=await sql`UPDATE inventory.reservation_items SET allocated_quantity=allocated_quantity+${q} WHERE id=${itemId}::uuid AND allocated_quantity+released_quantity+${q}<=quantity`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('RESERVATION_ALLOCATION_EXCEEDED','مقدار تخصیص از رزرو بیشتر است.');}
  async subtractReservationAllocated(ex:DatabaseExecutor,reservationId:string,warehouseId:string,variantId:string,q:number){const r=await sql`UPDATE inventory.reservation_items SET allocated_quantity=allocated_quantity-${q} WHERE reservation_id=${reservationId}::uuid AND warehouse_id=${warehouseId}::uuid AND variant_id=${variantId}::uuid AND allocated_quantity>=${q}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('RESERVATION_ALLOCATION_CONFLICT','ردیف رزرو با تخصیص سازگار نیست.');}
  async releaseReservationRemainder(ex:DatabaseExecutor,itemId:string,q:number){const r=await sql`UPDATE inventory.reservation_items SET released_quantity=released_quantity+${q} WHERE id=${itemId}::uuid AND allocated_quantity+released_quantity+${q}<=quantity`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('RESERVATION_RELEASE_CONFLICT','آزادسازی تعهد رزرو ناسازگار است.');}
  async reclaimReservationReleased(ex:DatabaseExecutor,itemId:string,q:number){const r=await sql`UPDATE inventory.reservation_items SET released_quantity=released_quantity-${q} WHERE id=${itemId}::uuid AND released_quantity>=${q}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('RESERVATION_RECLAIM_CONFLICT','بازپس‌گیری تعهد رزرو ناسازگار است.');}
  async setReservationStatus(ex:DatabaseExecutor,id:string,status:string){await sql`UPDATE inventory.reservations SET status=${status},version=version+1,updated_at=now() WHERE id=${id}::uuid`.execute(ex);}
  async attachReservationOrder(ex:DatabaseExecutor,id:string,orderId:string,paymentGraceUntil:string){const r=await sql<any>`UPDATE inventory.reservations SET order_id=${orderId}::uuid,status='payment_pending',payment_grace_until=${paymentGraceUntil}::timestamptz,updated_at=now(),version=version+1 WHERE id=${id}::uuid AND order_id IS NULL AND status IN ('active','payment_pending') AND expires_at>now() RETURNING id`.execute(ex);return !!r.rows[0];}
  async expiredReservationIds(limit:number){const r=await sql<any>`SELECT id FROM inventory.reservations WHERE ((status='active' AND expires_at<=now()) OR (status='payment_pending' AND COALESCE(payment_grace_until,expires_at)<=now())) ORDER BY COALESCE(payment_grace_until,expires_at),id LIMIT ${Math.max(1,Math.min(1000,limit))}`.execute(this.db);return r.rows.map((x:any)=>String(x.id));}

  async createAllocation(ex:DatabaseExecutor,i:any){await sql`INSERT INTO inventory.allocations(id,order_item_id,reservation_id,warehouse_id,variant_id,quantity,status) VALUES(${i.id}::uuid,${i.orderItemId}::uuid,${i.reservationId??null}::uuid,${i.warehouseId}::uuid,${i.variantId}::uuid,${i.quantity},'allocated')`.execute(ex);}
  async allocation(ex:DatabaseExecutor,id:string,lock=false){const r=await sql<any>`SELECT * FROM inventory.allocations WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]??null;}
  async allocationsForOrderItems(ex:DatabaseExecutor,orderItemIds:string[]){if(orderItemIds.length===0)return [];const r=await sql<any>`SELECT * FROM inventory.allocations WHERE order_item_id=ANY(${orderItemIds}::uuid[]) ORDER BY order_item_id,warehouse_id,id`.execute(ex);return r.rows;}
  async setAllocationStatus(ex:DatabaseExecutor,id:string,status:string){await sql`UPDATE inventory.allocations SET status=${status},version=version+1,updated_at=now() WHERE id=${id}::uuid`.execute(ex);}

  async listReservations(status?:string,allowedWarehouseIds:string[]|null=null){const r=await sql<any>`SELECT r.* FROM inventory.reservations r WHERE (${status??null}::text IS NULL OR r.status=${status??null}) AND (${allowedWarehouseIds}::uuid[] IS NULL OR NOT EXISTS(SELECT 1 FROM inventory.reservation_items ri WHERE ri.reservation_id=r.id AND NOT (ri.warehouse_id=ANY(${allowedWarehouseIds}::uuid[])))) ORDER BY r.created_at DESC LIMIT 500`.execute(this.db);return r.rows;}
  async reservationView(id:string){const r=await sql<any>`SELECT * FROM inventory.reservations WHERE id=${id}::uuid`.execute(this.db);if(!r.rows[0])return null;const items=await sql<any>`SELECT * FROM inventory.reservation_items WHERE reservation_id=${id}::uuid ORDER BY warehouse_id,variant_id`.execute(this.db);return {...r.rows[0],items:items.rows};}
  async listAllocations(orderItemId?:string,allowedWarehouseIds:string[]|null=null){const r=await sql<any>`SELECT * FROM inventory.allocations WHERE (${orderItemId??null}::uuid IS NULL OR order_item_id=${orderItemId??null}::uuid) AND (${allowedWarehouseIds}::uuid[] IS NULL OR warehouse_id=ANY(${allowedWarehouseIds}::uuid[])) ORDER BY created_at DESC LIMIT 500`.execute(this.db);return r.rows;}
  async listTransfers(allowedWarehouseIds:string[]|null=null){const r=await sql<any>`SELECT * FROM inventory.transfers WHERE (${allowedWarehouseIds}::uuid[] IS NULL OR (source_warehouse_id=ANY(${allowedWarehouseIds}::uuid[]) AND destination_warehouse_id=ANY(${allowedWarehouseIds}::uuid[]))) ORDER BY created_at DESC LIMIT 500`.execute(this.db);return r.rows;}
  async transferView(id:string){return this.transfer(this.db,id,false);}
  async costLayers(variantId:string,allowedWarehouseIds:string[]|null=null){const r=await sql<any>`SELECT * FROM inventory.cost_layers WHERE variant_id=${variantId}::uuid AND (${allowedWarehouseIds}::uuid[] IS NULL OR warehouse_id=ANY(${allowedWarehouseIds}::uuid[])) ORDER BY warehouse_id,stock_bucket,received_at,id`.execute(this.db);return r.rows;}

  async currentWeightedCost(variantId:string){const r=await sql<any>`SELECT CASE WHEN SUM(remaining_quantity)>0 THEN ROUND(SUM(remaining_quantity*effective_unit_cost_toman)::numeric/SUM(remaining_quantity))::bigint ELSE NULL END unit_cost_toman FROM inventory.cost_layers WHERE variant_id=${variantId}::uuid AND stock_bucket='sellable' AND remaining_quantity>0`.execute(this.db);return r.rows[0]?.unit_cost_toman==null?null:Number(r.rows[0].unit_cost_toman);}
  async currentProfitGuardCost(variantId:string){const r=await sql<any>`SELECT MAX(effective_unit_cost_toman)::bigint unit_cost_toman FROM inventory.cost_layers WHERE variant_id=${variantId}::uuid AND stock_bucket='sellable' AND remaining_quantity>0`.execute(this.db);return r.rows[0]?.unit_cost_toman==null?null:Number(r.rows[0].unit_cost_toman);}
  async fifoLayers(ex:DatabaseExecutor,warehouseId:string,variantId:string,bucket='sellable'){const r=await sql<any>`SELECT * FROM inventory.cost_layers WHERE warehouse_id=${warehouseId}::uuid AND variant_id=${variantId}::uuid AND stock_bucket=${bucket} AND remaining_quantity>0 ORDER BY received_at,id FOR UPDATE`.execute(ex);return r.rows;}
  async consumeLayer(ex:DatabaseExecutor,layerId:string,q:number){const r=await sql`UPDATE inventory.cost_layers SET remaining_quantity=remaining_quantity-${q} WHERE id=${layerId}::uuid AND remaining_quantity>=${q}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('COST_LAYER_CONFLICT','لایه هزینه همزمان تغییر کرده است.');}
  async createCostLayer(ex:DatabaseExecutor,i:any){await sql`INSERT INTO inventory.cost_layers(id,warehouse_id,variant_id,goods_receipt_item_id,transfer_parent_layer_id,return_parent_consumption_id,condition_parent_layer_id,stock_bucket,received_quantity,remaining_quantity,base_unit_cost_toman,landed_unit_cost_toman,effective_unit_cost_toman,received_at) VALUES(${i.id}::uuid,${i.warehouseId}::uuid,${i.variantId}::uuid,${i.goodsReceiptItemId??null}::uuid,${i.transferParentLayerId??null}::uuid,${i.returnParentConsumptionId??null}::uuid,${i.conditionParentLayerId??null}::uuid,${i.stockBucket??'sellable'},${i.quantity},${i.quantity},${i.baseUnitCostToman},${i.landedUnitCostToman??i.baseUnitCostToman},${i.effectiveUnitCostToman??i.landedUnitCostToman??i.baseUnitCostToman},${i.receivedAt??new Date()})`.execute(ex);}
  async insertCostConsumption(ex:DatabaseExecutor,i:any){await sql`INSERT INTO inventory.cost_layer_consumptions(id,cost_layer_id,order_item_id,inventory_movement_id,quantity,unit_cost_toman) VALUES(${i.id}::uuid,${i.costLayerId}::uuid,${i.orderItemId??null}::uuid,${i.movementId}::uuid,${i.quantity},${i.unitCostToman})`.execute(ex);}

  async createTransfer(ex:DatabaseExecutor,i:any){await sql`INSERT INTO inventory.transfers(id,source_warehouse_id,destination_warehouse_id,status,requested_by) VALUES(${i.id}::uuid,${i.sourceWarehouseId}::uuid,${i.destinationWarehouseId}::uuid,'draft',${i.requestedBy??null}::uuid)`.execute(ex);for(const x of i.items)await sql`INSERT INTO inventory.transfer_items(id,transfer_id,variant_id,requested_quantity) VALUES(${x.id}::uuid,${i.id}::uuid,${x.variantId}::uuid,${x.quantity})`.execute(ex);}
  async transfer(ex:DatabaseExecutor,id:string,lock=false){const r=await sql<any>`SELECT * FROM inventory.transfers WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);if(!r.rows[0])return null;const items=await sql<any>`SELECT * FROM inventory.transfer_items WHERE transfer_id=${id}::uuid ORDER BY variant_id`.execute(ex);return {...r.rows[0],items:items.rows};}
  async setTransferStatus(ex:DatabaseExecutor,id:string,status:string,actorId?:string){await sql`UPDATE inventory.transfers SET status=${status},approved_by=CASE WHEN ${status}='approved' THEN ${actorId??null}::uuid ELSE approved_by END,shipped_at=CASE WHEN ${status}='shipped' THEN now() ELSE shipped_at END,received_at=CASE WHEN ${status}='received' THEN now() ELSE received_at END,version=version+1,updated_at=now() WHERE id=${id}::uuid`.execute(ex);}
  async setTransferItemQuantities(ex:DatabaseExecutor,id:string,shipped:number,received?:number){await sql`UPDATE inventory.transfer_items SET shipped_quantity=${shipped},received_quantity=COALESCE(${received??null},received_quantity) WHERE id=${id}::uuid`.execute(ex);}
  async addTransferCostPart(ex:DatabaseExecutor,i:any){await sql`INSERT INTO inventory.transfer_cost_parts(id,transfer_item_id,source_cost_layer_id,quantity,unit_cost_toman) VALUES(${i.id}::uuid,${i.transferItemId}::uuid,${i.sourceCostLayerId}::uuid,${i.quantity},${i.unitCostToman})`.execute(ex);}
  async transferCostParts(ex:DatabaseExecutor,transferItemId:string){const r=await sql<any>`SELECT * FROM inventory.transfer_cost_parts WHERE transfer_item_id=${transferItemId}::uuid ORDER BY created_at,id`.execute(ex);return r.rows;}
  async setTransferDestinationLayer(ex:DatabaseExecutor,partId:string,layerId:string){const r=await sql`UPDATE inventory.transfer_cost_parts SET destination_cost_layer_id=${layerId}::uuid WHERE id=${partId}::uuid AND destination_cost_layer_id IS NULL`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('TRANSFER_COST_CONFLICT','هزینه انتقال قبلاً دریافت شده است.');}
  async receiptItemLayersForUpdate(ex:DatabaseExecutor,goodsReceiptItemId:string){const r=await sql<any>`SELECT * FROM inventory.cost_layers WHERE goods_receipt_item_id=${goodsReceiptItemId}::uuid ORDER BY received_at,id FOR UPDATE`.execute(ex);return r.rows;}
  async revalueCostLayer(ex:DatabaseExecutor,layerId:string,effective:number,landed:number){await sql`UPDATE inventory.cost_layers SET effective_unit_cost_toman=${effective},landed_unit_cost_toman=${landed} WHERE id=${layerId}::uuid`.execute(ex);}
  async insertCostRevaluation(ex:DatabaseExecutor,i:any){await sql`INSERT INTO inventory.cost_revaluations(id,goods_receipt_item_id,source_landed_cost_id,amount_toman,inventory_amount_toman,consumed_cogs_amount_toman) VALUES(${i.id}::uuid,${i.goodsReceiptItemId}::uuid,${i.sourceLandedCostId}::uuid,${i.amountToman},${i.inventoryAmountToman},${i.consumedCogsAmountToman})`.execute(ex);}

}
