import { Inject, Injectable } from '@nestjs/common';
import { Kysely,sql } from 'kysely';
import { randomUUID } from 'node:crypto';
import { KYSELY_DB } from '../../../platform/database/database.tokens';
import { DatabaseSchema } from '../../../platform/database/database.types';
import { TransactionManager } from '../../../platform/database/transaction-manager';
import { DomainError } from '../../../shared/errors/domain-error';
import { AuditWriter } from '../../../platform/audit/audit.writer';
import { RequestContextStore } from '../../../platform/request-context/request-context.store';

@Injectable()
export class TaxService{
 constructor(@Inject(KYSELY_DB)private readonly db:Kysely<DatabaseSchema>,private readonly tx:TransactionManager,private readonly audit:AuditWriter,private readonly ctx:RequestContextStore){}
 async resolve(input:{productId:string;brandId?:string|null;categoryId?:string|null;taxableToman:number}){if(!Number.isSafeInteger(input.taxableToman)||input.taxableToman<0)throw new DomainError('INVALID_MONEY','مبلغ مشمول مالیات معتبر نیست.');const r=await sql<any>`SELECT * FROM tax.tax_rules WHERE status='active' AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>now()) AND ((scope_type='product' AND scope_id=${input.productId}::uuid) OR (scope_type='brand' AND scope_id=${input.brandId??null}::uuid) OR (scope_type='category' AND scope_id=${input.categoryId??null}::uuid) OR scope_type='global') ORDER BY CASE scope_type WHEN 'product' THEN 4 WHEN 'brand' THEN 3 WHEN 'category' THEN 2 ELSE 1 END DESC LIMIT 1`.execute(this.db);const rule=r.rows[0];if(!rule)throw new DomainError('TAX_RULE_NOT_CONFIGURED','قانون مالیاتی فعال برای این کالا تعریف نشده است.');const rate=Number(rule.rate_basis_points);const numerator=BigInt(input.taxableToman)*BigInt(rate);const amount=Number((numerator+5000n)/10000n);return{rule_id:String(rule.id),rate_basis_points:rate,tax_toman:amount};}
 private present(r:any){return{id:String(r.id),name_fa:String(r.name_fa),rate_basis_points:Number(r.rate_basis_points),scope_type:String(r.scope_type),scope_id:r.scope_id?String(r.scope_id):null,status:String(r.status),starts_at:r.starts_at?new Date(r.starts_at).toISOString():null,ends_at:r.ends_at?new Date(r.ends_at).toISOString():null,version:Number(r.version)};}
 async list(){return (await sql<any>`SELECT id,name_fa,rate_basis_points,scope_type,scope_id,status,starts_at,ends_at,version FROM tax.tax_rules ORDER BY created_at DESC`.execute(this.db)).rows.map((r:any)=>this.present(r));}
 async create(input:any){const scope=String(input?.scope_type??''),scopeId=input?.scope_id?String(input.scope_id):null,rate=Number(input?.rate_basis_points),name=String(input?.name_fa??'').trim();if(!['global','brand','category','product'].includes(scope)||name.length<2||!Number.isInteger(rate)||rate<0||rate>10000||(scope==='global'?scopeId!==null:!scopeId))throw new DomainError('VALIDATION_ERROR','قانون مالیاتی معتبر نیست.');const id=randomUUID(),c=this.ctx.require();return this.tx.run(async ex=>{await sql`INSERT INTO tax.tax_rules(id,name_fa,rate_basis_points,scope_type,scope_id,status,starts_at,ends_at) VALUES(${id}::uuid,${name},${rate},${scope},${scopeId}::uuid,'draft',${input.starts_at??null}::timestamptz,${input.ends_at??null}::timestamptz)`.execute(ex);await this.audit.writeWith(ex,{actorType:c.actor.type,actorId:c.actor.id,action:'tax.rule.create',resourceType:'tax_rule',resourceId:id,afterData:input,requestId:c.requestId,traceId:c.traceId});return this.present({id,name_fa:name,rate_basis_points:rate,scope_type:scope,scope_id:scopeId,status:'draft',starts_at:input.starts_at??null,ends_at:input.ends_at??null,version:1});});}
 async update(id:string,input:any,expected:number){if(!Number.isSafeInteger(expected)||expected<1)throw new DomainError('IF_MATCH_REQUIRED','If-Match معتبر الزامی است.');const c=this.ctx.require();return this.tx.run(async ex=>{const r=await sql<any>`SELECT * FROM tax.tax_rules WHERE id=${id}::uuid FOR UPDATE`.execute(ex);const before=r.rows[0];if(!before)throw new DomainError('TAX_RULE_NOT_FOUND','قانون مالیاتی پیدا نشد.');if(before.status!=='draft')throw new DomainError('INVALID_STATE_TRANSITION','فقط قانون پیش‌نویس قابل ویرایش است.');if(Number(before.version)!==expected)throw new DomainError('VERSION_CONFLICT','نسخه قانون تغییر کرده است.');const name=input.name_fa===undefined?before.name_fa:String(input.name_fa).trim(),rate=input.rate_basis_points===undefined?Number(before.rate_basis_points):Number(input.rate_basis_points);if(name.length<2||!Number.isInteger(rate)||rate<0||rate>10000)throw new DomainError('VALIDATION_ERROR','اطلاعات قانون معتبر نیست.');await sql`UPDATE tax.tax_rules SET name_fa=${name},rate_basis_points=${rate},starts_at=${input.starts_at===undefined?before.starts_at:input.starts_at}::timestamptz,ends_at=${input.ends_at===undefined?before.ends_at:input.ends_at}::timestamptz,version=version+1,updated_at=now() WHERE id=${id}::uuid`.execute(ex);await this.audit.writeWith(ex,{actorType:c.actor.type,actorId:c.actor.id,action:'tax.rule.update',resourceType:'tax_rule',resourceId:id,beforeData:before,afterData:input,requestId:c.requestId,traceId:c.traceId});return this.present({...before,name_fa:name,rate_basis_points:rate,starts_at:input.starts_at===undefined?before.starts_at:input.starts_at,ends_at:input.ends_at===undefined?before.ends_at:input.ends_at,status:'draft',version:expected+1});});}
 async activate(id:string,expected:number){if(!Number.isSafeInteger(expected)||expected<1)throw new DomainError('IF_MATCH_REQUIRED','If-Match معتبر الزامی است.');const c=this.ctx.require();return this.tx.run(async ex=>{const r=await sql<any>`SELECT * FROM tax.tax_rules WHERE id=${id}::uuid FOR UPDATE`.execute(ex);const rule=r.rows[0];if(!rule)throw new DomainError('TAX_RULE_NOT_FOUND','قانون مالیاتی پیدا نشد.');if(rule.status!=='draft'||Number(rule.version)!==expected)throw new DomainError(rule.status!=='draft'?'INVALID_STATE_TRANSITION':'VERSION_CONFLICT','قانون قابل فعال‌سازی نیست یا نسخه تغییر کرده است.');const scopeLock=`tax-scope:${rule.scope_type}:${rule.scope_id??'global'}`;await sql`SELECT pg_advisory_xact_lock(hashtext(${scopeLock}))`.execute(ex);const conflict=await sql<any>`SELECT id FROM tax.tax_rules WHERE id<>${id}::uuid AND status='active' AND scope_type=${rule.scope_type} AND scope_id IS NOT DISTINCT FROM ${rule.scope_id}::uuid AND tstzrange(COALESCE(starts_at,'-infinity'::timestamptz),COALESCE(ends_at,'infinity'::timestamptz),'[)') && tstzrange(COALESCE(${rule.starts_at}::timestamptz,'-infinity'::timestamptz),COALESCE(${rule.ends_at}::timestamptz,'infinity'::timestamptz),'[)') LIMIT 1`.execute(ex);if(conflict.rows[0])throw new DomainError('TAX_RULE_CONFLICT','برای این محدوده در بازه زمانی موردنظر قانون مالیاتی فعال دیگری وجود دارد.');await sql`UPDATE tax.tax_rules SET status='active',version=version+1,updated_at=now() WHERE id=${id}::uuid`.execute(ex);await this.audit.writeWith(ex,{actorType:c.actor.type,actorId:c.actor.id,action:'tax.rule.activate',resourceType:'tax_rule',resourceId:id,beforeData:rule,afterData:{status:'active'},requestId:c.requestId,traceId:c.traceId});return this.present({...rule,status:'active',version:expected+1});});}
 async expire(id:string,expected:number){if(!Number.isSafeInteger(expected)||expected<1)throw new DomainError('IF_MATCH_REQUIRED','If-Match معتبر الزامی است.');const c=this.ctx.require();return this.tx.run(async ex=>{const r=await sql<any>`SELECT * FROM tax.tax_rules WHERE id=${id}::uuid FOR UPDATE`.execute(ex);const rule=r.rows[0];if(!rule)throw new DomainError('TAX_RULE_NOT_FOUND','قانون مالیاتی پیدا نشد.');if(rule.status!=='active'||Number(rule.version)!==expected)throw new DomainError(rule.status!=='active'?'INVALID_STATE_TRANSITION':'VERSION_CONFLICT','قانون قابل پایان نیست یا نسخه تغییر کرده است.');await sql`UPDATE tax.tax_rules SET status='expired',ends_at=COALESCE(ends_at,now()),version=version+1,updated_at=now() WHERE id=${id}::uuid`.execute(ex);await this.audit.writeWith(ex,{actorType:c.actor.type,actorId:c.actor.id,action:'tax.rule.expire',resourceType:'tax_rule',resourceId:id,beforeData:rule,afterData:{status:'expired'},requestId:c.requestId,traceId:c.traceId});return this.present({...rule,status:'expired',ends_at:rule.ends_at??new Date(),version:expected+1});});}
}
