import { Inject, Injectable } from '@nestjs/common';
import { Kysely, sql } from 'kysely';
import { KYSELY_DB } from '../../../platform/database/database.tokens';
import { DatabaseSchema } from '../../../platform/database/database.types';
import { AuditWriter, AuditEntry } from '../../../platform/audit/audit.writer';
import { ConflictError } from '../../../shared/errors/app-error';

@Injectable()
export class RbacRepository {
  constructor(@Inject(KYSELY_DB) private readonly db:Kysely<DatabaseSchema>,private readonly audit:AuditWriter){}
  listPermissions(){return sql<any>`SELECT id,key,module,name_fa,description_fa,risk_level FROM admin.permissions ORDER BY module,key`.execute(this.db).then(r=>r.rows);}
  listRoles(){return sql<any>`SELECT id,key,name_fa,description_fa,is_system,is_active,version FROM admin.roles ORDER BY key`.execute(this.db).then(r=>r.rows);}
  async createRole(input:{key:string;name_fa:string;description_fa?:string},audit:AuditEntry){return this.db.transaction().execute(async trx=>{const r=await sql<any>`INSERT INTO admin.roles(key,name_fa,description_fa) VALUES(${input.key},${input.name_fa},${input.description_fa??null}) RETURNING *`.execute(trx);const role=r.rows[0];await this.audit.writeWith(trx,{...audit,resourceType:'role',resourceId:role.id,afterData:role});return role;});}
  getRole(id:string){return sql<any>`SELECT * FROM admin.roles WHERE id=${id}::uuid`.execute(this.db).then(r=>r.rows[0]);}
  async updateRole(id:string,input:{name_fa?:string;description_fa?:string;is_active?:boolean},version:number,audit:AuditEntry){return this.db.transaction().execute(async trx=>{const before=(await sql<any>`SELECT * FROM admin.roles WHERE id=${id}::uuid FOR UPDATE`.execute(trx)).rows[0];if(!before) return; if(Number(before.version)!==version)throw new ConflictError('VERSION_CONFLICT','نسخه نقش تغییر کرده است.',{current_version:Number(before.version)});if(before.is_system&&input.is_active===false)throw new ConflictError('SYSTEM_ROLE_PROTECTED','نقش سیستمی قابل غیرفعال‌سازی نیست.');const r=await sql<any>`UPDATE admin.roles SET name_fa=COALESCE(${input.name_fa??null},name_fa),description_fa=COALESCE(${input.description_fa??null},description_fa),is_active=COALESCE(${input.is_active??null},is_active),updated_at=now(),version=version+1 WHERE id=${id}::uuid AND version=${version} RETURNING *`.execute(trx);const after=r.rows[0];await this.audit.writeWith(trx,{...audit,resourceType:'role',resourceId:id,beforeData:before,afterData:after});return after;});}
  async replaceRolePermissions(roleId:string,permissionIds:string[],version:number,audit:AuditEntry){return this.db.transaction().execute(async trx=>{const role=(await sql<any>`SELECT * FROM admin.roles WHERE id=${roleId}::uuid FOR UPDATE`.execute(trx)).rows[0];if(!role)return;if(Number(role.version)!==version)throw new ConflictError('VERSION_CONFLICT','نسخه نقش تغییر کرده است.',{current_version:Number(role.version)});if(role.is_system)throw new ConflictError('SYSTEM_ROLE_PROTECTED','دسترسی‌های نقش سیستمی مستقیماً قابل بازنویسی نیست.');const before=(await sql<any>`SELECT permission_id FROM admin.role_permissions WHERE role_id=${roleId}::uuid ORDER BY permission_id`.execute(trx)).rows.map(x=>x.permission_id);await sql`DELETE FROM admin.role_permissions WHERE role_id=${roleId}::uuid`.execute(trx);for(const id of permissionIds)await sql`INSERT INTO admin.role_permissions(role_id,permission_id) VALUES(${roleId}::uuid,${id}::uuid)`.execute(trx);const updated=await sql<any>`UPDATE admin.roles SET version=version+1,updated_at=now() WHERE id=${roleId}::uuid AND version=${version} RETURNING version`.execute(trx);await this.audit.writeWith(trx,{...audit,resourceType:'role',resourceId:roleId,beforeData:{permission_ids:before},afterData:{permission_ids:permissionIds,version:Number(updated.rows[0].version)}});return {version:Number(updated.rows[0].version)};});}
  listStaff(){return sql<any>`SELECT sp.id,sp.employee_code,sp.first_name,sp.last_name,sp.status,sp.version,a.email_normalized,a.mobile_normalized FROM admin.staff_profiles sp JOIN iam.accounts a ON a.id=sp.account_id ORDER BY sp.created_at DESC`.execute(this.db).then(r=>r.rows);}
  async getStaff(id:string){const staff=(await sql<any>`SELECT sp.*,a.email_normalized,a.mobile_normalized,a.status account_status FROM admin.staff_profiles sp JOIN iam.accounts a ON a.id=sp.account_id WHERE sp.id=${id}::uuid`.execute(this.db)).rows[0];if(!staff)return;const roles=(await sql<any>`SELECT r.id,r.key,r.name_fa FROM admin.staff_roles sr JOIN admin.roles r ON r.id=sr.role_id WHERE sr.staff_id=${id}::uuid AND (sr.expires_at IS NULL OR sr.expires_at>now()) ORDER BY r.key`.execute(this.db)).rows;const scopes=(await sql<any>`SELECT scope_type,scope_id FROM admin.access_scopes WHERE staff_id=${id}::uuid ORDER BY scope_type,scope_id`.execute(this.db)).rows;return {...staff,roles,scopes};}
  async updateStaff(id:string,input:{first_name?:string;last_name?:string;employee_code?:string},version:number,audit:AuditEntry){return this.db.transaction().execute(async trx=>{const before=(await sql<any>`SELECT * FROM admin.staff_profiles WHERE id=${id}::uuid FOR UPDATE`.execute(trx)).rows[0];if(!before)return;if(Number(before.version)!==version)throw new ConflictError('VERSION_CONFLICT','نسخه کارمند تغییر کرده است.',{current_version:Number(before.version)});const r=await sql<any>`UPDATE admin.staff_profiles SET first_name=COALESCE(${input.first_name??null},first_name),last_name=COALESCE(${input.last_name??null},last_name),employee_code=COALESCE(${input.employee_code??null},employee_code),updated_at=now(),version=version+1 WHERE id=${id}::uuid AND version=${version} RETURNING *`.execute(trx);const after=r.rows[0];await this.audit.writeWith(trx,{...audit,resourceType:'staff',resourceId:id,beforeData:before,afterData:after});return after;});}
  async createStaff(input:any,passwordHash:string,enrollmentHash:string,audit:AuditEntry){return this.db.transaction().execute(async trx=>{const r=await sql<any>`WITH a AS (INSERT INTO iam.accounts(email_normalized,mobile_normalized,password_hash,status,email_verified_at) VALUES(${input.email??null},${input.mobile??null},${passwordHash},'active',CASE WHEN ${input.email??null} IS NULL THEN NULL ELSE now() END) RETURNING id) INSERT INTO admin.staff_profiles(account_id,employee_code,first_name,last_name,fido_enrollment_token_hash,fido_enrollment_expires_at) SELECT id,${input.employee_code??null},${input.first_name},${input.last_name},${enrollmentHash},now()+interval '24 hours' FROM a RETURNING *`.execute(trx);const staff=r.rows[0];await this.audit.writeWith(trx,{...audit,resourceType:'staff',resourceId:staff.id,afterData:{id:staff.id,employee_code:staff.employee_code,first_name:staff.first_name,last_name:staff.last_name,status:staff.status}});return staff;});}
  async setStaffStatus(id:string,status:'active'|'disabled',version:number,audit:AuditEntry){return this.db.transaction().execute(async trx=>{const before=(await sql<any>`SELECT * FROM admin.staff_profiles WHERE id=${id}::uuid FOR UPDATE`.execute(trx)).rows[0];if(!before)return;if(Number(before.version)!==version)throw new ConflictError('VERSION_CONFLICT','نسخه کارمند تغییر کرده است.',{current_version:Number(before.version)});if(status==='disabled'){const isSuper=!!(await sql<any>`SELECT 1 FROM admin.staff_roles sr JOIN admin.roles r ON r.id=sr.role_id WHERE sr.staff_id=${id}::uuid AND r.key='superadmin' AND r.is_active=true LIMIT 1`.execute(trx)).rows[0];if(isSuper){const others=await sql<any>`SELECT count(DISTINCT sp.id)::int count FROM admin.staff_profiles sp JOIN admin.staff_roles sr ON sr.staff_id=sp.id JOIN admin.roles r ON r.id=sr.role_id WHERE sp.status='active' AND sp.id<>${id}::uuid AND r.key='superadmin' AND r.is_active=true AND (sr.expires_at IS NULL OR sr.expires_at>now())`.execute(trx);if(Number(others.rows[0]?.count??0)===0)throw new ConflictError('LAST_SUPERADMIN_PROTECTED','آخرین مدیر کل را نمی‌توان غیرفعال کرد.');}}const after=(await sql<any>`UPDATE admin.staff_profiles SET status=${status},updated_at=now(),version=version+1 WHERE id=${id}::uuid AND version=${version} RETURNING *`.execute(trx)).rows[0];if(status==='disabled')await sql`UPDATE iam.sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE account_id=${before.account_id}::uuid AND revoked_at IS NULL`.execute(trx);await this.audit.writeWith(trx,{...audit,resourceType:'staff',resourceId:id,beforeData:before,afterData:after});return after;});}
  async replaceStaffRoles(staffId:string,roleIds:string[],version:number,assignedBy:string|undefined,audit:AuditEntry){return this.db.transaction().execute(async trx=>{const staff=(await sql<any>`SELECT * FROM admin.staff_profiles WHERE id=${staffId}::uuid FOR UPDATE`.execute(trx)).rows[0];if(!staff)return;if(Number(staff.version)!==version)throw new ConflictError('VERSION_CONFLICT','نسخه کارمند تغییر کرده است.',{current_version:Number(staff.version)});const beforeRows=(await sql<any>`SELECT sr.role_id,r.key FROM admin.staff_roles sr JOIN admin.roles r ON r.id=sr.role_id WHERE sr.staff_id=${staffId}::uuid ORDER BY sr.role_id`.execute(trx)).rows;const before=beforeRows.map(x=>x.role_id);const hadSuper=beforeRows.some(x=>x.key==='superadmin');let keepsSuper=false;for(const rid of roleIds){const rr=(await sql<any>`SELECT key FROM admin.roles WHERE id=${rid}::uuid AND is_active=true`.execute(trx)).rows[0];if(!rr)throw new ConflictError('ROLE_NOT_FOUND','نقش انتخاب‌شده معتبر نیست.');if(rr.key==='superadmin')keepsSuper=true;}if(hadSuper&&!keepsSuper){const others=await sql<any>`SELECT count(DISTINCT sp.id)::int count FROM admin.staff_profiles sp JOIN admin.staff_roles sr ON sr.staff_id=sp.id JOIN admin.roles r ON r.id=sr.role_id WHERE sp.status='active' AND sp.id<>${staffId}::uuid AND r.key='superadmin' AND r.is_active=true AND (sr.expires_at IS NULL OR sr.expires_at>now())`.execute(trx);if(Number(others.rows[0]?.count??0)===0)throw new ConflictError('LAST_SUPERADMIN_PROTECTED','آخرین مدیر کل باید نقش superadmin را حفظ کند.');}await sql`DELETE FROM admin.staff_roles WHERE staff_id=${staffId}::uuid`.execute(trx);for(const id of roleIds)await sql`INSERT INTO admin.staff_roles(staff_id,role_id,assigned_by) VALUES(${staffId}::uuid,${id}::uuid,${assignedBy??null}::uuid)`.execute(trx);const updated=(await sql<any>`UPDATE admin.staff_profiles SET version=version+1,updated_at=now() WHERE id=${staffId}::uuid AND version=${version} RETURNING version`.execute(trx)).rows[0];await sql`UPDATE iam.sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE account_id=${staff.account_id}::uuid AND revoked_at IS NULL`.execute(trx);await this.audit.writeWith(trx,{...audit,resourceType:'staff',resourceId:staffId,beforeData:{role_ids:before},afterData:{role_ids:roleIds,version:Number(updated.version)}});return {version:Number(updated.version)};});}
  async replaceStaffScopes(staffId:string,scopes:{scope_type:string;scope_id:string}[],version:number,audit:AuditEntry){return this.db.transaction().execute(async trx=>{const staff=(await sql<any>`SELECT * FROM admin.staff_profiles WHERE id=${staffId}::uuid FOR UPDATE`.execute(trx)).rows[0];if(!staff)return;if(Number(staff.version)!==version)throw new ConflictError('VERSION_CONFLICT','نسخه کارمند تغییر کرده است.',{current_version:Number(staff.version)});const before=(await sql<any>`SELECT scope_type,scope_id FROM admin.access_scopes WHERE staff_id=${staffId}::uuid ORDER BY scope_type,scope_id`.execute(trx)).rows;await sql`DELETE FROM admin.access_scopes WHERE staff_id=${staffId}::uuid`.execute(trx);for(const s of scopes)await sql`INSERT INTO admin.access_scopes(staff_id,scope_type,scope_id) VALUES(${staffId}::uuid,${s.scope_type},${s.scope_id}::uuid)`.execute(trx);const updated=(await sql<any>`UPDATE admin.staff_profiles SET version=version+1,updated_at=now() WHERE id=${staffId}::uuid AND version=${version} RETURNING version`.execute(trx)).rows[0];await sql`UPDATE iam.sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE account_id=${staff.account_id}::uuid AND revoked_at IS NULL`.execute(trx);await this.audit.writeWith(trx,{...audit,resourceType:'staff',resourceId:staffId,beforeData:{scopes:before},afterData:{scopes,version:Number(updated.version)}});return {version:Number(updated.version)};});}
}
