import { Inject,Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { sql } from 'kysely';
import { CartRepository } from '../infrastructure/cart.repository';
import { CheckoutMarketingSnapshotRepository } from '../infrastructure/checkout-marketing-snapshot.repository';
import { hashCapabilityToken as hashToken,newCapabilityToken as newToken } from '../../../shared/security/capability-token';
import { TransactionManager } from '../../../platform/database/transaction-manager';
import { DomainError } from '../../../shared/errors/domain-error';
import { PRICING_QUOTE_PORT, PricingQuotePort } from '../../pricing/application/ports/pricing-quote.port';
import { INVENTORY_AVAILABILITY_PORT,INVENTORY_RESERVATION_PORT,InventoryAvailabilityPort,InventoryReservationPort } from '../../inventory/application/ports/inventory-public.port';
import { TaxService } from '../../tax/application/tax.service';
import { RequestContextStore } from '../../../platform/request-context/request-context.store';
import { MoneyToman } from '../../../shared/kernel/money-toman';
import { CUSTOMER_COMMERCE_PORT,CustomerCommercePort } from '../../customer/application/ports/customer-commerce.port';
import { STORE_CONFIGURATION_PORT,StoreConfigurationPort } from '../../configuration/application/ports/store-configuration.port';
import { CheckoutPromotionService } from '../../marketing/application/checkout-promotion.service';
import { ORDER_PURCHASE_HISTORY_PORT,OrderPurchaseHistoryPort } from '../../orders/application/ports/order-purchase-history.port';

@Injectable()
export class CartService{
 constructor(private readonly repo:CartRepository,private readonly marketingSnapshot:CheckoutMarketingSnapshotRepository,private readonly tx:TransactionManager,@Inject(PRICING_QUOTE_PORT)private readonly pricing:PricingQuotePort,@Inject(INVENTORY_AVAILABILITY_PORT)private readonly availability:InventoryAvailabilityPort,@Inject(INVENTORY_RESERVATION_PORT)private readonly reservation:InventoryReservationPort,@Inject(CUSTOMER_COMMERCE_PORT)private readonly customerCommerce:CustomerCommercePort,@Inject(ORDER_PURCHASE_HISTORY_PORT)private readonly purchaseHistory:OrderPurchaseHistoryPort,private readonly checkoutPromotions:CheckoutPromotionService,private readonly tax:TaxService,private readonly ctx:RequestContextStore,@Inject(STORE_CONFIGURATION_PORT)private readonly config:StoreConfigurationPort){}
 private async verify(c:any,t:string,ex?:any){if(!t||!c||c.status!=='active'||new Date(c.expires_at)<=new Date()||!(await this.repo.tokenValid(String(c.id),t,ex)))throw new DomainError('CART_ACCESS_DENIED','دسترسی به سبد معتبر نیست.');}
 private async cfgNumber(key:string,fallback:number,legacyKey:string){const c:any=this.config;if(typeof c.getNumber==='function')return c.getNumber(key,fallback);if(typeof c.get==='function'){const v=Number(c.get(legacyKey,String(fallback)));return Number.isFinite(v)?v:fallback;}return fallback;}
 private cartTtlHours(){return this.cfgNumber('commerce.cart_ttl_hours',168,'CART_TTL_HOURS');}
 private checkoutTtlMinutes(){return this.cfgNumber('commerce.checkout_ttl_minutes',15,'CHECKOUT_TTL_MINUTES');}
 private reservationTtlMinutes(){return this.cfgNumber('commerce.reservation_ttl_minutes',15,'RESERVATION_TTL_MINUTES');}
 private accessTokenMaxActive(){return this.cfgNumber('commerce.cart_access_token_max_active',5,'CART_ACCESS_TOKEN_MAX_ACTIVE');}
 private async assertGlobalSalesEnabled(){const c:any=this.config;const enabled=typeof c.getBoolean==='function'?await c.getBoolean('sales.global_sales_enabled',true):true;if(!enabled)throw new DomainError('SALES_GLOBALLY_DISABLED','فروش آنلاین موقتاً متوقف است.');}
 async create(customerId:string|null=null){const made=await this.repo.create(customerId,await this.cartTtlHours());return{cart_id:made.id,cart_token:made.token};}
 private presentCart(c:any,items:any[]){return{id:String(c.id),customer_id:c.customer_id?String(c.customer_id):null,status:String(c.status),version:Number(c.version),expires_at:new Date(c.expires_at).toISOString(),items:items.map(i=>({id:String(i.id),product_id:String(i.product_id),variant_id:String(i.variant_id),sku:String(i.sku),product_name:String(i.product_name),quantity:Number(i.quantity)}))};}
 async customerAccess(){const a=this.ctx.get()?.actor;if(a?.type!=='customer'||!a.id)throw new DomainError('CUSTOMER_REQUIRED','ورود مشتری الزامی است.');const customerId=a.id;return this.tx.run(async ex=>{await sql`SELECT pg_advisory_xact_lock(hashtext(${`customer-cart:${customerId}`}))`.execute(ex);await this.repo.expireCustomerCartIfDue(ex,customerId);let c=await this.repo.activeCustomerCart(customerId,ex,true);if(!c){const made=await this.repo.createWith(ex,customerId,await this.cartTtlHours());c=await this.repo.cart(made.id,ex,true);return{cart:this.presentCart(c,[]),cart_token:made.token};}const token=await this.repo.issueAccessToken(ex,String(c.id),await this.cartTtlHours(),await this.accessTokenMaxActive());return{cart:this.presentCart(c,await this.repo.items(String(c.id),ex)),cart_token:token};});}
 async mergeGuest(sourceId:string,sourceToken:string){const a=this.ctx.get()?.actor;if(a?.type!=='customer'||!a.id)throw new DomainError('CUSTOMER_REQUIRED','ورود مشتری الزامی است.');const customerId=a.id;return this.tx.run(async ex=>{await sql`SELECT pg_advisory_xact_lock(hashtext(${`customer-cart:${customerId}`}))`.execute(ex);await this.repo.expireCustomerCartIfDue(ex,customerId);const source=await this.repo.cart(sourceId,ex,true);await this.verify(source,sourceToken,ex);if(source.customer_id)throw new DomainError('CART_NOT_GUEST','سبد مبدا مهمان نیست.');const advanced=(await sql<any>`SELECT 1 FROM cart.checkouts WHERE cart_id=${sourceId}::uuid AND status IN ('reserved','order_created') LIMIT 1`.execute(ex)).rows[0];if(advanced)throw new DomainError('CART_ALREADY_IN_CHECKOUT','سبد وارد مرحله نهایی Checkout شده است.');await this.repo.expireQuotedForCart(ex,sourceId);let target=await this.repo.activeCustomerCart(customerId,ex,true);if(!target){await ex.updateTable('cart.carts' as any).set({customer_id:customerId,version:sql`version+1`,updated_at:new Date()} as any).where('id' as any,'=',sourceId as any).execute();await this.repo.invalidatePrimaryToken(ex,sourceId);target={...source,customer_id:customerId};}else if(String(target.id)!==sourceId){const targetAdvanced=(await sql<any>`SELECT 1 FROM cart.checkouts WHERE cart_id=${target.id}::uuid AND status IN ('reserved','order_created') LIMIT 1`.execute(ex)).rows[0];if(targetAdvanced)throw new DomainError('CART_ALREADY_IN_CHECKOUT','سبد مقصد وارد مرحله نهایی Checkout شده است.');await this.repo.expireQuotedForCart(ex,String(target.id));await this.repo.mergeItems(ex,sourceId,String(target.id));}const targetId=String(target.id);const token=await this.repo.issueAccessToken(ex,targetId,await this.cartTtlHours(),await this.accessTokenMaxActive());const fresh=await this.repo.cart(targetId,ex,true);return{cart:this.presentCart(fresh,await this.repo.items(targetId,ex)),cart_token:token};});}
 async customerView(){const a=this.ctx.get()?.actor;if(a?.type!=='customer'||!a.id)throw new DomainError('CUSTOMER_REQUIRED','ورود مشتری الزامی است.');return this.tx.run(async ex=>{await sql`SELECT pg_advisory_xact_lock(hashtext(${`customer-cart:${a.id}`}))`.execute(ex);await this.repo.expireCustomerCartIfDue(ex,a.id!);const c=await this.repo.activeCustomerCart(a.id!,ex,true);return c?this.presentCart(c,await this.repo.items(String(c.id),ex)):null;});}
 async view(id:string,token:string){const c=await this.repo.cart(id);await this.verify(c,token);return this.presentCart(c,await this.repo.items(id));}
 async shippingMethods(){return (await this.repo.activeShippingMethods()).map((r:any)=>({id:String(r.id),code:String(r.code),name_fa:String(r.name_fa),fee_toman:Number(r.fee_toman)}));}
 async add(id:string,token:string,variantId:string,q:number){await this.assertGlobalSalesEnabled();if(!Number.isSafeInteger(q)||q<1)throw new DomainError('VALIDATION_ERROR','تعداد نامعتبر است.');await this.tx.run(async ex=>{const c=await this.repo.cart(id,ex,true);await this.verify(c,token,ex);await this.assertNotAdvanced(ex,id);const variant=await this.repo.variantForCart(variantId,ex);if(!variant)throw new DomainError('VARIANT_NOT_FOUND','تنوع کالا پیدا نشد.');this.assertSellableItem(variant);const current=await this.repo.currentItemQuantity(id,variantId,ex),available=await this.availability.getOnlineSellableQuantity(variantId);if(current+q>available)throw new DomainError('INSUFFICIENT_STOCK','موجودی قابل فروش آنلاین کافی نیست.',{available});await this.repo.add(ex,id,variantId,q);});return this.view(id,token);}
 async qty(id:string,token:string,itemId:string,q:number){await this.assertGlobalSalesEnabled();if(!Number.isSafeInteger(q)||q<0)throw new DomainError('VALIDATION_ERROR','تعداد نامعتبر است.');await this.tx.run(async ex=>{const c=await this.repo.cart(id,ex,true);await this.verify(c,token,ex);await this.assertNotAdvanced(ex,id);const item=await this.repo.itemById(id,itemId,ex);if(!item)throw new DomainError('CART_ITEM_NOT_FOUND','قلم سبد پیدا نشد.');if(q>0){this.assertSellableItem(item);const available=await this.availability.getOnlineSellableQuantity(String(item.variant_id));if(q>available)throw new DomainError('INSUFFICIENT_STOCK','موجودی قابل فروش آنلاین کافی نیست.',{available});}await this.repo.setQty(ex,id,itemId,q);});return this.view(id,token);}
 async remove(id:string,token:string,itemId:string){await this.tx.run(async ex=>{const c=await this.repo.cart(id,ex,true);await this.verify(c,token,ex);await this.assertNotAdvanced(ex,id);const item=await this.repo.itemById(id,itemId,ex);if(item)await this.repo.setQty(ex,id,itemId,0);});return this.view(id,token);}
 async quote(id:string,token:string,input:{shipping_method_id:string;coupon_code?:string|null}){
  await this.assertGlobalSalesEnabled();
  if(!input?.shipping_method_id)throw new DomainError('VALIDATION_ERROR','روش ارسال الزامی است.');
  return this.tx.run(async ex=>{
   const c=await this.repo.cart(id,ex,true);await this.verify(c,token,ex);await this.assertNotAdvanced(ex,id);
   const items=await this.repo.items(id,ex);if(!items.length)throw new DomainError('CART_EMPTY','سبد خرید خالی است.');
   const shipping=await this.repo.shipping(input.shipping_method_id,ex);if(!shipping)throw new DomainError('SHIPPING_METHOD_UNAVAILABLE','روش ارسال در دسترس نیست.');
   const customerId=c.customer_id?String(c.customer_id):null;
   const customerType=await this.customerCommerce.getCustomerType(customerId);
   let subtotal=MoneyToman.zero(),pricingDiscount=MoneyToman.zero(),tax=MoneyToman.zero();const lines=[] as any[];
   for(const i of items){
    this.assertSellableItem(i);const quantity=Number(i.quantity);const available=await this.availability.getOnlineSellableQuantity(String(i.variant_id));
    if(quantity>available)throw new DomainError('INSUFFICIENT_STOCK','موجودی قابل فروش آنلاین کافی نیست.',{variant_id:String(i.variant_id),available});
    const p:any=await this.pricing.quoteVariant({variantId:String(i.variant_id),quantity,customerType});if(!p)throw new DomainError('PRICE_UNAVAILABLE','قیمت معتبر برای کالا وجود ندارد.');
    let baseUnit:MoneyToman,finalUnit:MoneyToman;try{baseUnit=MoneyToman.from(p.base_price_toman);finalUnit=MoneyToman.from(p.current_toman);}catch{throw new DomainError('PRICE_INVARIANT_VIOLATION','قیمت کالا خارج از محدوده امن محاسباتی است.');}
    if(finalUnit.compare(baseUnit)>0)throw new DomainError('PRICE_INVARIANT_VIOLATION','قیمت نهایی نمی‌تواند از قیمت پایه Snapshot بیشتر باشد.');
    const base=baseUnit.multiplyByInteger(quantity),final=finalUnit.multiplyByInteger(quantity),lineDiscount=base.subtract(final);
    const tr=await this.tax.resolve({productId:String(i.product_id),brandId:i.brand_id?String(i.brand_id):null,categoryId:i.primary_category_id?String(i.primary_category_id):null,taxableToman:final.toJSON()});
    const lineTax=MoneyToman.from(tr.tax_toman);subtotal=subtotal.add(base);pricingDiscount=pricingDiscount.add(lineDiscount);tax=tax.add(lineTax);
    lines.push({product_id:i.product_id,variant_id:i.variant_id,sku:i.sku,product_name:i.product_name,quantity,unit_base_toman:baseUnit.toJSON(),unit_final_toman:finalUnit.toJSON(),discount_toman:lineDiscount.toJSON(),tax_toman:lineTax.toJSON(),tax_rule_id:tr.rule_id,line_total_toman:final.add(lineTax).toJSON(),pricing_snapshot:{...p,tax:{rule_id:tr.rule_id,rate_basis_points:tr.rate_basis_points}}});
   }
   const pricingNet=subtotal.subtract(pricingDiscount);
   const hasCompletedPurchase=customerId?await this.purchaseHistory.hasCompletedPurchase(customerId):false;
   const marketing=await this.checkoutPromotions.evaluate({couponCode:input.coupon_code,customerId,subtotalToman:pricingNet.toJSON(),isWholesale:customerType==='wholesale',hasCompletedPurchase});
   const marketingDiscount=MoneyToman.from(marketing.totalDiscountToman),totalDiscount=pricingDiscount.add(marketingDiscount);
   let shippingMoney:MoneyToman;try{shippingMoney=MoneyToman.from(shipping.fee_toman);}catch{throw new DomainError('SHIPPING_PRICE_INVALID','هزینه ارسال خارج از محدوده امن محاسباتی است.');}
   const pricingOnlyTotal=subtotal.subtract(pricingDiscount).add(tax).add(shippingMoney),total=subtotal.subtract(totalDiscount).add(tax).add(shippingMoney),ct=newToken(),checkoutId=randomUUID(),expiresAt=new Date(Date.now()+(await this.checkoutTtlMinutes())*60_000);
   await this.repo.insertCheckout(ex,{id:checkoutId,cartId:id,cartVersion:Number(c.version),customerId:c.customer_id,tokenHash:hashToken(ct),shippingId:shipping.id,subtotal:subtotal.toJSON(),discount:pricingDiscount.toJSON(),shipping:shippingMoney.toJSON(),tax:tax.toJSON(),total:pricingOnlyTotal.toJSON(),expiresAt},lines);
   await this.marketingSnapshot.apply(ex,{checkoutId,pricingDiscountToman:pricingDiscount.toJSON(),marketingDiscountToman:marketingDiscount.toJSON(),marketingSnapshot:{applications:marketing.applications,pricing_net_toman:pricingNet.toJSON()},totalToman:total.toJSON()});
   await this.repo.extendCartExpiry(ex,id,expiresAt);
   return{checkout_id:checkoutId,checkout_token:ct,customer_type:customerType,subtotal_toman:subtotal.toJSON(),pricing_discount_toman:pricingDiscount.toJSON(),marketing_discount_toman:marketingDiscount.toJSON(),discount_toman:totalDiscount.toJSON(),shipping_toman:shippingMoney.toJSON(),tax_toman:tax.toJSON(),total_toman:total.toJSON(),marketing_snapshot:{applications:marketing.applications,pricing_net_toman:pricingNet.toJSON()},expires_at:expiresAt,items:lines};
  });
 }
 async reserve(checkoutId:string,token:string){await this.assertGlobalSalesEnabled();if(!token)throw new DomainError('CHECKOUT_ACCESS_REQUIRED','توکن Checkout الزامی است.');return this.tx.run(async ex=>{const co=await this.repo.checkout(checkoutId,ex,true);if(!co||co.status!=='quoted'||new Date(co.expires_at)<=new Date()||hashToken(token)!==co.token_hash)throw new DomainError('CHECKOUT_INVALID','Checkout معتبر نیست.');const cart=await this.repo.cart(String(co.cart_id),ex,true);if(!cart||cart.status!=='active')throw new DomainError('CART_NOT_ACTIVE','سبد خرید دیگر فعال نیست.');if(Number(cart.version)!==Number(co.cart_version_snapshot))throw new DomainError('CART_CHANGED_SINCE_QUOTE','سبد بعد از Quote تغییر کرده است.');for(const i of await this.repo.items(String(co.cart_id),ex))this.assertSellableItem(i);if(!await this.repo.shipping(String(co.shipping_method_id),ex))throw new DomainError('SHIPPING_METHOD_UNAVAILABLE','روش ارسال دیگر در دسترس نیست.');const advanced=await sql<any>`SELECT id FROM cart.checkouts WHERE cart_id=${co.cart_id}::uuid AND id<>${checkoutId}::uuid AND status IN ('reserved','order_created') LIMIT 1`.execute(ex);if(advanced.rows[0])throw new DomainError('CART_ALREADY_IN_CHECKOUT','یک Checkout دیگر از این سبد وارد مرحله نهایی شده است.');const items=await this.repo.checkoutItems(checkoutId,ex);const plan=await this.availability.planOnlineReservation(items.map((i:any)=>({variant_id:String(i.variant_id),quantity:Number(i.quantity)})));const expiry=new Date(Date.now()+(await this.reservationTtlMinutes())*60_000);const r=await this.reservation.reserveInTransaction(ex,{cart_id:String(co.cart_id),customer_id:co.customer_id?String(co.customer_id):undefined,expires_at:expiry.toISOString(),items:plan});await ex.updateTable('cart.checkouts' as any).set({status:'reserved',reservation_id:r.id,expires_at:expiry,updated_at:new Date()} as any).where('id' as any,'=',checkoutId as any).execute();await this.repo.extendCartExpiry(ex,String(co.cart_id),expiry);return{checkout_id:checkoutId,reservation_id:r.id,status:'reserved',expires_at:expiry};});}
 async expireCartsDue(limit=100){const ids=await this.repo.expiredCartIds(limit);const out=[] as any[];for(const id of ids){try{out.push(await this.tx.run(async ex=>({id,status:(await this.repo.expireCartIfDue(ex,id))?'expired':'unchanged'})));}catch(e){out.push({id,status:'failed',error:e instanceof Error?e.message:'unknown'});}}return out;}
 async expireDue(limit=100){
  const ids=await this.repo.expiredCheckoutIds(limit);
  const out=[] as any[];
  for(const id of ids){try{out.push(await this.tx.run(async ex=>{const co=await this.repo.checkout(id,ex,true);if(!co||!['quoted','reserved'].includes(co.status)||new Date(co.expires_at)>new Date())return{id,status:co?.status??'missing'};if(co.status==='reserved'&&co.reservation_id)await this.reservation.releaseInTransaction(ex,String(co.reservation_id),'expired');await ex.updateTable('cart.checkouts' as any).set({status:'expired',updated_at:new Date()} as any).where('id' as any,'=',id as any).execute();return{id,status:'expired'};}));}catch(e){out.push({id,status:'failed',error:e instanceof Error?e.message:'unknown'});}}
  return out;
 }
 private assertSellableItem(i:any){if(!i.global_sales_enabled||i.brand_sales_enabled===false||!i.category_sales_enabled||!i.product_sales_enabled||!i.variant_sales_enabled||i.product_status!=='published'||i.variant_status!=='active')throw new DomainError('PRODUCT_NOT_SELLABLE','یکی از اقلام سبد دیگر قابل فروش نیست.');}
 private async assertNotAdvanced(ex:any,cartId:string){const r=await sql<any>`SELECT 1 FROM cart.checkouts WHERE cart_id=${cartId}::uuid AND status IN ('reserved','order_created') LIMIT 1`.execute(ex);if(r.rows[0])throw new DomainError('CART_ALREADY_IN_CHECKOUT','سبد وارد مرحله نهایی Checkout شده است.');}
}
