import {Body,Controller,Get,Headers,Param,Patch,Post,Query} from '@nestjs/common';import { ConfigService } from '@nestjs/config';import { Permissions,Public,RequireIdempotency,RequireStepUp,StaffOnly } from '../../../platform/auth/auth.decorators';import { DomainError } from '../../../shared/errors/domain-error';import { ConfigurationService } from '../application/configuration.service';import { FeatureFlagService } from '../application/feature-flag.service';
@Controller() export class ConfigurationController{constructor(private readonly settings:ConfigurationService,private readonly flags:FeatureFlagService,private readonly env:ConfigService){}
 @StaffOnly() @Permissions('configuration.view') @Get('admin/configuration') list(){return this.settings.list();}
 @StaffOnly() @Permissions('configuration.view') @Get('admin/configuration/:key') get(@Param('key')key:string){return this.settings.get(key);}
 @StaffOnly() @Permissions('configuration.edit') @RequireIdempotency('configuration.patch') @Patch('admin/configuration/:key') patch(@Param('key')key:string,@Body()body:any){return this.settings.patch(key,body);}
 @StaffOnly() @Permissions('configuration.view') @Post('admin/configuration/:key/preview') preview(@Param('key')key:string,@Body()body:any){return this.settings.preview(key,body);}
 @StaffOnly() @Permissions('configuration.edit') @RequireIdempotency('configuration.change_request.create') @Post('admin/configuration/:key/change-requests') createChange(@Param('key')key:string,@Body()body:any){return this.settings.createChange(key,body);}
 @StaffOnly() @Permissions('configuration.review') @Get('admin/configuration/change-requests') changes(@Query('status')status?:string){return this.settings.listChanges(status);}
 @StaffOnly() @Permissions('configuration.review') @Get('admin/configuration/change-requests/:id') change(@Param('id')id:string){return this.settings.getChange(id);}
 @StaffOnly() @Permissions('configuration.review') @RequireStepUp() @RequireIdempotency('configuration.change_request.approve') @Post('admin/configuration/change-requests/:id/approve') approve(@Param('id')id:string,@Body()b:any){return this.settings.approve(id,b?.comment);}
 @StaffOnly() @Permissions('configuration.review') @RequireIdempotency('configuration.change_request.reject') @Post('admin/configuration/change-requests/:id/reject') reject(@Param('id')id:string,@Body()b:any){return this.settings.reject(id,b?.reason);}
 @StaffOnly() @Permissions('configuration.edit') @RequireIdempotency('configuration.change_request.cancel') @Post('admin/configuration/change-requests/:id/cancel') cancel(@Param('id')id:string,@Body()b:any){return this.settings.cancel(id,b?.reason);}
 @StaffOnly() @Permissions('configuration.apply') @RequireStepUp() @RequireIdempotency('configuration.change.apply') @Post('admin/configuration/change-requests/:id/apply') apply(@Param('id')id:string,@Body()b:any){return this.settings.apply(id,b);}
 @StaffOnly() @Permissions('configuration.apply') @RequireStepUp() @RequireIdempotency('configuration.rollback') @Post('admin/configuration/:key/rollback') rollback(@Param('key')key:string,@Body()b:any){return this.settings.rollback(key,b);}
 @StaffOnly() @Permissions('configuration.view') @Get('admin/feature-flags') listFlags(){return this.flags.list();}
 @StaffOnly() @Permissions('configuration.feature_flags.manage') @RequireIdempotency('feature_flag.create') @Post('admin/feature-flags') createFlag(@Body()b:any){return this.flags.create(b);}
 @StaffOnly() @Permissions('configuration.view') @Get('admin/feature-flags/:key') getFlag(@Param('key')key:string){return this.flags.get(key);}
 @StaffOnly() @Permissions('configuration.feature_flags.manage') @RequireIdempotency('feature_flag.patch') @Patch('admin/feature-flags/:key') patchFlag(@Param('key')key:string,@Body()b:any){return this.flags.patch(key,b);}
 @StaffOnly() @Permissions('configuration.view') @Post('admin/feature-flags/:key/preview') previewFlag(@Param('key')key:string,@Body()b:any){return this.flags.preview(key,b);}
 @StaffOnly() @Permissions('configuration.feature_flags.manage') @RequireStepUp() @RequireIdempotency('feature_flag.rollout') @Post('admin/feature-flags/:key/rollout') rollout(@Param('key')key:string,@Body()b:any){return this.flags.rollout(key,b?.percentage);}
 @StaffOnly() @Permissions('configuration.feature_flags.manage') @RequireStepUp() @RequireIdempotency('feature_flag.enable') @Post('admin/feature-flags/:key/enable') enable(@Param('key')key:string){return this.flags.enable(key);}
 @StaffOnly() @Permissions('configuration.feature_flags.manage') @RequireIdempotency('feature_flag.disable') @Post('admin/feature-flags/:key/disable') disable(@Param('key')key:string){return this.flags.disable(key);}
 @StaffOnly() @Permissions('configuration.feature_flags.manage') @RequireStepUp() @RequireIdempotency('feature_flag.retire') @Post('admin/feature-flags/:key/retire') retire(@Param('key')key:string){return this.flags.retire(key);}
 @StaffOnly() @Permissions('configuration.feature_flags.manage') @RequireIdempotency('feature_flag.emergency_disable') @Post('admin/feature-flags/:key/emergency-disable') emergency(@Param('key')key:string){return this.flags.emergencyDisable(key);}
 @Public() @Post('internal/feature-flags/evaluate') async internalEvaluate(@Headers('authorization')auth:string,@Body()b:any){const expected=this.env.get<string>('INTERNAL_SERVICE_BEARER','');if(!expected||auth!==`Bearer ${expected}`)throw new DomainError('INTERNAL_AUTH_REQUIRED','احراز هویت سرویس داخلی معتبر نیست.');return this.flags.evaluate(b);}
}
