import { Injectable } from '@nestjs/common';import { createHash } from 'node:crypto';import { TransactionManager } from '../../../platform/database/transaction-manager';import { RequestContextStore } from '../../../platform/request-context/request-context.store';import { AuditWriter } from '../../../platform/audit/audit.writer';import { OutboxWriter } from '../../../platform/outbox/outbox-writer';import { DomainError } from '../../../shared/errors/domain-error';import { ConfigurationRepository } from '../infrastructure/configuration.repository';import { featureFlagEvent } from '../domain/configuration.events';
@Injectable() export class FeatureFlagService{constructor(private readonly tx:TransactionManager,private readonly repo:ConfigurationRepository,private readonly ctx:RequestContextStore,private readonly audit:AuditWriter,private readonly outbox:OutboxWriter){}
 private staff(){const a=this.ctx.get()?.actor;if(a?.type!=='staff'||!a.id)throw new DomainError('STAFF_REQUIRED','دسترسی مدیر الزامی است.');return a.id;}
 private key(v:unknown){const x=String(v??'').trim();if(!/^[a-z0-9_.-]{1,150}$/.test(x))throw new DomainError('VALIDATION_ERROR','کلید Feature Flag معتبر نیست.');return x;}
 async list(){this.staff();return{items:await this.repo.flags()};} async get(key:string){this.staff();const r=await this.repo.flag(this.key(key));if(!r)throw new DomainError('FEATURE_FLAG_NOT_FOUND','Feature Flag پیدا نشد.');return r;}
 async create(i:any){const actor=this.staff(),key=this.key(i?.key),nameFa=String(i?.name_fa??'').trim(),flagType=String(i?.flag_type??''),defaultVariant=String(i?.default_variant??'').trim(),riskLevel=String(i?.risk_level??'');if(!nameFa||nameFa.length>200||!['boolean','variant'].includes(flagType)||!defaultVariant||defaultVariant.length>100||!['low','medium','high','critical'].includes(riskLevel))throw new DomainError('VALIDATION_ERROR','مشخصات Feature Flag معتبر نیست.');return this.tx.run(async ex=>this.repo.createFlag(ex,{key,nameFa,flagType,defaultVariant,riskLevel,actorId:actor}));}
 async patch(keyRaw:string,i:any){const actor=this.staff(),key=this.key(keyRaw);if(i?.risk_level!=null&&!['low','medium','high','critical'].includes(String(i.risk_level)))throw new DomainError('VALIDATION_ERROR','سطح ریسک معتبر نیست.');const r=await this.tx.run(ex=>this.repo.patchFlag(ex,key,{nameFa:i?.name_fa??undefined,defaultVariant:i?.default_variant??undefined,riskLevel:i?.risk_level??undefined},actor));if(!r)throw new DomainError('FEATURE_FLAG_NOT_FOUND','Feature Flag پیدا نشد یا بازنشسته است.');return r;}
 async preview(keyRaw:string,i:any){const key=this.key(keyRaw),flag=await this.repo.flag(key);if(!flag)throw new DomainError('FEATURE_FLAG_NOT_FOUND','Feature Flag پیدا نشد.');const rollout=i?.rollout_percent==null?Number(flag.rollout_percent):Number(i.rollout_percent);if(!Number.isFinite(rollout)||rollout<0||rollout>100)throw new DomainError('VALIDATION_ERROR','درصد Rollout معتبر نیست.');return{key,current_status:flag.status,current_rollout_percent:Number(flag.rollout_percent),proposed_rollout_percent:rollout,variant:i?.variant??flag.default_variant,target_type:i?.target_type??null,target_ids:i?.target_ids??[],risk_level:flag.risk_level};}
 async rollout(key:string,percentage:unknown){return this.mutate(key,{rollout:Number(percentage)},'configuration.feature_flag.rollout','feature_flag.rollout_changed.v1');}
 async enable(key:string){return this.mutate(key,{status:'enabled'},'configuration.feature_flag.enable','feature_flag.enabled.v1');}
 async disable(key:string){return this.mutate(key,{status:'disabled'},'configuration.feature_flag.disable','feature_flag.disabled.v1');}
 async retire(key:string){return this.mutate(key,{status:'retired',rollout:0},'configuration.feature_flag.retire','feature_flag.retired.v1');}
 async emergencyDisable(key:string){return this.mutate(key,{status:'disabled',rollout:0},'configuration.feature_flag.emergency_disable','feature_flag.emergency_disabled.v1');}
 private async mutate(keyRaw:string,patch:any,action:string,eventType:string){const actor=this.staff(),key=this.key(keyRaw),ctx=this.ctx.require();if(patch.rollout!=null&&(!Number.isFinite(patch.rollout)||patch.rollout<0||patch.rollout>100))throw new DomainError('VALIDATION_ERROR','درصد Rollout معتبر نیست.');return this.tx.run(async ex=>{const before=await this.repo.flag(key,ex,true);if(!before)throw new DomainError('FEATURE_FLAG_NOT_FOUND','Feature Flag پیدا نشد.');if(before.status==='retired'&&patch.status!=='retired')throw new DomainError('FEATURE_FLAG_RETIRED','Feature Flag بازنشسته قابل فعال‌سازی نیست.');const row=await this.repo.mutateFlag(ex,key,{...patch,actorId:actor});await this.outbox.append(ex,[featureFlagEvent(eventType,key,Number(row.version),{key,status:row.status,rollout_percent:Number(row.rollout_percent)})],ctx);await this.audit.writeWith(ex,{actorType:'staff',actorId:actor,action,resourceType:'feature_flag',beforeData:{key,status:before.status,rollout_percent:Number(before.rollout_percent)},afterData:{key,status:row.status,rollout_percent:Number(row.rollout_percent)},requestId:ctx.requestId,traceId:ctx.traceId});return row;});}
 async evaluate(input:any){const key=this.key(input?.flag_key),flag=await this.repo.flag(key);if(!flag||flag.status!=='enabled'||flag.status==='retired')return{flag_key:key,enabled:false,variant:flag?.default_variant??null,reason:'disabled'};const targetIds=Array.isArray(flag.target_ids)?flag.target_ids:[];if(targetIds.includes(String(input?.subject_id)))return{flag_key:key,enabled:true,variant:flag.default_variant,reason:'targeted'};const h=createHash('sha256').update(`${key}:${String(input?.subject_type)}:${String(input?.subject_id)}`).digest().readUInt32BE(0)%10000/100;const enabled=h<Number(flag.rollout_percent);return{flag_key:key,enabled,variant:enabled?flag.default_variant:null,reason:'rollout',bucket:h};}
}
