import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { TransactionManager } from '../../../platform/database/transaction-manager';
import { AuditWriter } from '../../../platform/audit/audit.writer';
import { OutboxWriter } from '../../../platform/outbox/outbox-writer';
import { RequestContextStore } from '../../../platform/request-context/request-context.store';
import { ScopePolicy } from '../../../platform/auth/scope-policy';
import { DomainError } from '../../../shared/errors/domain-error';
import { ProcurementRepository } from '../infrastructure/procurement.repository';
import { assertMoney, assertPositiveInt } from '../domain/procurement.rules';
import { procurementEvent } from '../domain/procurement.events';

@Injectable()
export class PurchaseService{
 constructor(private readonly tx:TransactionManager,private readonly repo:ProcurementRepository,private readonly audit:AuditWriter,private readonly outbox:OutboxWriter,private readonly ctx:RequestContextStore,private readonly scopes:ScopePolicy){}
 requests(){return this.repo.purchaseRequests(this.scopes.allowedIds(this.ctx.get()?.actor,'warehouse'));} async request(id:string){const r=await this.repo.purchaseRequest(id);if(r)this.scopes.assert(this.ctx.get()?.actor,'warehouse',String(r.warehouse_id));return r;}
 async createRequest(input:{warehouse_id:string;reason?:string;items:Array<{variant_id:string;requested_quantity:number;note?:string}>}){this.scopes.assert(this.ctx.get()?.actor,'warehouse',input.warehouse_id);if(!Array.isArray(input.items)||!input.items.length)throw new DomainError('VALIDATION_ERROR','حداقل یک قلم الزامی است.');const seen=new Set<string>();for(const x of input.items){assertPositiveInt(x.requested_quantity);if(seen.has(x.variant_id))throw new DomainError('DUPLICATE_ITEM','کالای تکراری در درخواست خرید مجاز نیست.');seen.add(x.variant_id);}const c=this.ctx.require(),id=randomUUID();await this.tx.run(async trx=>{const number=await this.repo.nextNumber(trx,'PR');await this.repo.createPurchaseRequest(trx,{id,number,warehouseId:input.warehouse_id,requestedBy:c.actor.id,reason:input.reason,items:input.items.map(x=>({id:randomUUID(),variant_id:x.variant_id,quantity:x.requested_quantity,note:x.note}))});await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.request.create',resourceType:'purchase_request',resourceId:id,afterData:input,requestId:c.requestId,traceId:c.traceId});});return this.request(id);}
 async updateRequest(id:string,input:{reason?:string;items?:Array<{variant_id:string;requested_quantity:number;note?:string}>},expected:number){if(input.reason===undefined&&input.items===undefined)throw new DomainError('VALIDATION_ERROR','حداقل یک تغییر الزامی است.');const c=this.ctx.require();if(input.items){if(!input.items.length)throw new DomainError('VALIDATION_ERROR','حداقل یک قلم الزامی است.');const seen=new Set<string>();for(const x of input.items){assertPositiveInt(x.requested_quantity);if(seen.has(x.variant_id))throw new DomainError('DUPLICATE_ITEM','کالای تکراری مجاز نیست.');seen.add(x.variant_id);}}await this.tx.run(async trx=>{const before=await this.repo.purchaseRequestForUpdate(trx,id);if(!before)throw new DomainError('PURCHASE_REQUEST_NOT_FOUND','درخواست خرید پیدا نشد.');this.scopes.assert(c.actor,'warehouse',String(before.warehouse_id));await this.repo.replacePurchaseRequestDraft(trx,id,{reason:input.reason,items:input.items?.map(x=>({id:randomUUID(),variant_id:x.variant_id,quantity:x.requested_quantity,note:x.note}))},expected);await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.request.update',resourceType:'purchase_request',resourceId:id,beforeData:before,afterData:input,requestId:c.requestId,traceId:c.traceId});});return this.request(id);}
 async transitionRequest(id:string,target:'submitted'|'approved'|'rejected'|'cancelled',expected:number,reason?:string){const c=this.ctx.require();await this.tx.run(async trx=>{const r=await this.repo.purchaseRequestForUpdate(trx,id);if(!r)throw new DomainError('PURCHASE_REQUEST_NOT_FOUND','درخواست خرید پیدا نشد.');this.scopes.assert(c.actor,'warehouse',String(r.warehouse_id));const current=String(r.status);const allowed:{[k:string]:string[]}={submitted:['draft'],approved:['submitted'],rejected:['submitted'],cancelled:['draft','submitted']};if(!(allowed[target]?.includes(current)??false))throw new DomainError('INVALID_STATE_TRANSITION','تغییر وضعیت درخواست خرید مجاز نیست.');if(target==='approved'&&c.actor.id&&String(r.requested_by??'')===c.actor.id)throw new DomainError('SEPARATION_OF_DUTIES','درخواست‌کننده نمی‌تواند درخواست خرید خود را تایید کند.');if((target==='rejected'||target==='cancelled')&&!String(reason??'').trim())throw new DomainError('REASON_REQUIRED','دلیل الزامی است.');await this.repo.updateRequestStatus(trx,id,target,expected,c.actor.id,reason);await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:`procurement.request.${target}`,resourceType:'purchase_request',resourceId:id,beforeData:r,afterData:{status:target},reason,requestId:c.requestId,traceId:c.traceId});if(target==='approved')await this.outbox.append(trx,[procurementEvent('procurement.purchase_request.approved.v1','purchase_request',id,expected+1,{purchase_request_id:id,warehouse_id:r.warehouse_id})],c);});return this.request(id);}

 orders(){return this.repo.purchaseOrders(this.scopes.allowedIds(this.ctx.get()?.actor,'warehouse'));} async order(id:string){const r=await this.repo.purchaseOrder(id);if(r)this.scopes.assert(this.ctx.get()?.actor,'warehouse',String(r.warehouse_id));return r;}
 async createOrder(input:{supplier_id:string;warehouse_id:string;purchase_request_id?:string;expected_at?:string;items:Array<{variant_id:string;ordered_quantity:number;unit_cost_toman:number;discount_toman?:number;tax_toman?:number}>}){this.scopes.assert(this.ctx.get()?.actor,'warehouse',input.warehouse_id);const supplier=await this.repo.supplier(input.supplier_id);if(!supplier||String(supplier.status)!=='active')throw new DomainError('SUPPLIER_INACTIVE','تامین‌کننده فعال نیست.');if(!Array.isArray(input.items)||!input.items.length)throw new DomainError('VALIDATION_ERROR','حداقل یک قلم الزامی است.');const seen=new Set<string>();for(const x of input.items){assertPositiveInt(x.ordered_quantity);assertMoney(x.unit_cost_toman);assertMoney(x.discount_toman??0);assertMoney(x.tax_toman??0);if((x.discount_toman??0)>x.ordered_quantity*x.unit_cost_toman)throw new DomainError('INVALID_DISCOUNT','تخفیف از مبلغ قلم بیشتر است.');if(seen.has(x.variant_id))throw new DomainError('DUPLICATE_ITEM','کالای تکراری در سفارش خرید مجاز نیست.');seen.add(x.variant_id);}const c=this.ctx.require(),id=randomUUID();await this.tx.run(async trx=>{if(input.purchase_request_id){const pr=await this.repo.purchaseRequestForUpdate(trx,input.purchase_request_id);if(!pr||String(pr.status)!=='approved')throw new DomainError('PURCHASE_REQUEST_NOT_APPROVED','درخواست خرید تاییدشده نیست.');if(String(pr.warehouse_id)!==input.warehouse_id)throw new DomainError('WAREHOUSE_MISMATCH','انبار سفارش با درخواست خرید یکسان نیست.');await this.repo.updateRequestStatus(trx,input.purchase_request_id,'converted',Number(pr.version),c.actor.id);}const number=await this.repo.nextNumber(trx,'PO');await this.repo.createPurchaseOrder(trx,{id,number,supplierId:input.supplier_id,warehouseId:input.warehouse_id,requestId:input.purchase_request_id,expectedAt:input.expected_at,createdBy:c.actor.id,items:input.items.map(x=>({id:randomUUID(),variant_id:x.variant_id,quantity:x.ordered_quantity,unit_cost_toman:x.unit_cost_toman,discount_toman:x.discount_toman??0,tax_toman:x.tax_toman??0}))});await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.po.create',resourceType:'purchase_order',resourceId:id,afterData:input,requestId:c.requestId,traceId:c.traceId});});return this.order(id);}
 async updateOrder(id:string,input:{expected_at?:string;items?:Array<{variant_id:string;ordered_quantity:number;unit_cost_toman:number;discount_toman?:number;tax_toman?:number}>},expected:number){if(input.expected_at===undefined&&input.items===undefined)throw new DomainError('VALIDATION_ERROR','حداقل یک تغییر الزامی است.');const c=this.ctx.require();if(input.items){if(!input.items.length)throw new DomainError('VALIDATION_ERROR','حداقل یک قلم الزامی است.');const seen=new Set<string>();for(const x of input.items){assertPositiveInt(x.ordered_quantity);assertMoney(x.unit_cost_toman);assertMoney(x.discount_toman??0);assertMoney(x.tax_toman??0);if((x.discount_toman??0)>x.ordered_quantity*x.unit_cost_toman)throw new DomainError('INVALID_DISCOUNT','تخفیف از مبلغ قلم بیشتر است.');if(seen.has(x.variant_id))throw new DomainError('DUPLICATE_ITEM','کالای تکراری مجاز نیست.');seen.add(x.variant_id);}}await this.tx.run(async trx=>{const before=await this.repo.purchaseOrderForUpdate(trx,id);if(!before)throw new DomainError('PURCHASE_ORDER_NOT_FOUND','سفارش خرید پیدا نشد.');this.scopes.assert(c.actor,'warehouse',String(before.warehouse_id));await this.repo.replacePurchaseOrderDraft(trx,id,{expectedAt:input.expected_at,items:input.items?.map(x=>({id:randomUUID(),variant_id:x.variant_id,quantity:x.ordered_quantity,unit_cost_toman:x.unit_cost_toman,discount_toman:x.discount_toman??0,tax_toman:x.tax_toman??0}))},expected);await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.po.update',resourceType:'purchase_order',resourceId:id,beforeData:before,afterData:input,requestId:c.requestId,traceId:c.traceId});});return this.order(id);}
 async transitionOrder(id:string,target:'submitted'|'approved'|'sent'|'cancelled'|'closed',expected:number,reason?:string){const c=this.ctx.require();await this.tx.run(async trx=>{const po=await this.repo.purchaseOrderForUpdate(trx,id);if(!po)throw new DomainError('PURCHASE_ORDER_NOT_FOUND','سفارش خرید پیدا نشد.');this.scopes.assert(c.actor,'warehouse',String(po.warehouse_id));const current=String(po.status);const allowed:{[k:string]:string[]}={submitted:['draft'],approved:['submitted'],sent:['approved'],cancelled:['draft','submitted','approved','sent'],closed:['received','partially_received']};if(!(allowed[target]?.includes(current)??false))throw new DomainError('INVALID_STATE_TRANSITION','تغییر وضعیت سفارش خرید مجاز نیست.');if(target==='approved'&&c.actor.id&&String(po.created_by??'')===c.actor.id)throw new DomainError('SEPARATION_OF_DUTIES','سازنده سفارش خرید نمی‌تواند آن را تایید کند.');if(target==='cancelled'&&current==='partially_received')throw new DomainError('PO_PARTIALLY_RECEIVED_CANNOT_CANCEL','سفارش دارای دریافت باید با بستن مانده خاتمه یابد.');if(target==='cancelled'&&!String(reason??'').trim())throw new DomainError('REASON_REQUIRED','دلیل لغو الزامی است.');if(target==='closed'){await this.repo.assertPOClosable(trx,id);if(current==='partially_received'){if(!String(reason??'').trim())throw new DomainError('REASON_REQUIRED','برای بستن سفارش با مانده دریافت‌نشده، دلیل الزامی است.');await this.repo.cancelPORemainder(trx,id);}}await this.repo.updatePOStatus(trx,id,target,expected,c.actor.id,reason);await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:`procurement.po.${target}`,resourceType:'purchase_order',resourceId:id,beforeData:po,afterData:{status:target},reason,requestId:c.requestId,traceId:c.traceId});if(['approved','sent'].includes(target))await this.outbox.append(trx,[procurementEvent(`procurement.purchase_order.${target}.v1`,'purchase_order',id,expected+1,{purchase_order_id:id,supplier_id:po.supplier_id,warehouse_id:po.warehouse_id})],c);});return this.order(id);}
}
