import { Inject, Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { sql } from 'kysely';
import { TransactionManager } from '../../../platform/database/transaction-manager';
import { AuditWriter } from '../../../platform/audit/audit.writer';
import { OutboxWriter } from '../../../platform/outbox/outbox-writer';
import { RequestContextStore } from '../../../platform/request-context/request-context.store';
import { ScopePolicy } from '../../../platform/auth/scope-policy';
import { DomainError } from '../../../shared/errors/domain-error';
import { INVENTORY_PROCUREMENT_PORT, type InventoryProcurementPort } from '../../inventory/application/ports/inventory-procurement.port';
import { ProcurementRepository } from '../infrastructure/procurement.repository';
import { procurementEvent } from '../domain/procurement.events';
import type { DatabaseExecutor } from '../../../platform/database/transaction-manager';

@Injectable()
export class PurchaseReturnService{
 constructor(private readonly tx:TransactionManager,private readonly repo:ProcurementRepository,@Inject(INVENTORY_PROCUREMENT_PORT)private readonly inventory:InventoryProcurementPort,private readonly audit:AuditWriter,private readonly outbox:OutboxWriter,private readonly ctx:RequestContextStore,private readonly scopes:ScopePolicy){}
 async list(){const allowed=this.scopes.allowedIds(this.ctx.get()?.actor,'warehouse');return (await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_returns WHERE (${allowed}::uuid[] IS NULL OR warehouse_id=ANY(${allowed}::uuid[])) ORDER BY created_at DESC LIMIT 500`.execute(this.tx.readonly())).rows;}
 async get(id:string){const h=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_returns WHERE id=${id}::uuid`.execute(this.tx.readonly())).rows[0];if(!h)return null;this.scopes.assert(this.ctx.get()?.actor,'warehouse',String(h.warehouse_id));const items=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_return_items WHERE purchase_return_id=${id}::uuid ORDER BY variant_id`.execute(this.tx.readonly())).rows;return {...h,items};}
 private async lock(ex:DatabaseExecutor,id:string):Promise<(Record<string,unknown>&{items:Record<string,unknown>[]})|null>{const h=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_returns WHERE id=${id}::uuid FOR UPDATE`.execute(ex)).rows[0];if(!h)return null;const items=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_return_items WHERE purchase_return_id=${id}::uuid`.execute(ex)).rows;return {...h,items};}
 async create(input:{supplier_id:string;warehouse_id:string;goods_receipt_id?:string;reason:string;items:Array<{variant_id:string;quantity:number;stock_bucket?:'sellable'|'quarantine'|'damaged'}>}){const supplier=await this.repo.supplier(input.supplier_id);if(!supplier||String(supplier.status)!=='active')throw new DomainError('SUPPLIER_INACTIVE','تامین‌کننده فعال نیست.');this.scopes.assert(this.ctx.get()?.actor,'warehouse',input.warehouse_id);if(!String(input.reason??'').trim()||!input.items?.length)throw new DomainError('VALIDATION_ERROR','دلیل و اقلام مرجوعی الزامی است.');const seen=new Set<string>();for(const x of input.items){if(!Number.isSafeInteger(x.quantity)||x.quantity<=0)throw new DomainError('INVALID_QUANTITY','مقدار مرجوعی نامعتبر است.');if(seen.has(x.variant_id))throw new DomainError('DUPLICATE_ITEM','کالای تکراری مجاز نیست.');seen.add(x.variant_id);}const c=this.ctx.require(),id=randomUUID();await this.tx.run(async trx=>{if(input.goods_receipt_id){const gr=await this.repo.receiptForUpdate(trx,input.goods_receipt_id);if(!gr||String(gr.supplier_id)!==input.supplier_id||String(gr.warehouse_id)!==input.warehouse_id)throw new DomainError('PURCHASE_RETURN_RECEIPT_MISMATCH','رسید مبنا با مرجوعی سازگار نیست.');const base=new Map((gr.items as Array<Record<string,unknown>>).map(x=>[String(x.variant_id),Number(x.accepted_quantity)+Number(x.quarantine_quantity)]));for(const x of input.items){const prevRow=(await sql<{q:number}>`SELECT COALESCE(SUM(pri.quantity),0)::int q FROM procurement.purchase_return_items pri JOIN procurement.purchase_returns pr ON pr.id=pri.purchase_return_id WHERE pr.goods_receipt_id=${input.goods_receipt_id}::uuid AND pri.variant_id=${x.variant_id}::uuid AND pr.status IN ('approved','shipped','completed')`.execute(trx)).rows[0];if(!prevRow)throw new DomainError('PURCHASE_RETURN_AGGREGATE_FAILED','محاسبه مجموع مرجوعی ناموفق بود.');const prev=prevRow.q;if(x.quantity+Number(prev)>Number(base.get(x.variant_id)??0))throw new DomainError('PURCHASE_RETURN_QUANTITY_EXCEEDED','مقدار مرجوعی از مقدار متعلق به رسید بیشتر است.');}}const number=await this.repo.nextNumber(trx,'PRT');await sql`INSERT INTO procurement.purchase_returns(id,return_number,supplier_id,warehouse_id,goods_receipt_id,reason,created_by) VALUES(${id}::uuid,${number},${input.supplier_id}::uuid,${input.warehouse_id}::uuid,${input.goods_receipt_id??null}::uuid,${input.reason},${c.actor.id??null}::uuid)`.execute(trx);for(const x of input.items)await sql`INSERT INTO procurement.purchase_return_items(id,purchase_return_id,variant_id,quantity,stock_bucket) VALUES(${randomUUID()}::uuid,${id}::uuid,${x.variant_id}::uuid,${x.quantity},${x.stock_bucket??'quarantine'})`.execute(trx);await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.purchase_return.create',resourceType:'purchase_return',resourceId:id,afterData:input,requestId:c.requestId,traceId:c.traceId});});return this.get(id);}
 async approve(id:string,expected:number){const c=this.ctx.require();await this.tx.run(async trx=>{const r=await this.lock(trx,id);if(!r)throw new DomainError('PURCHASE_RETURN_NOT_FOUND','مرجوعی پیدا نشد.');this.scopes.assert(c.actor,'warehouse',String(r.warehouse_id));if(String(r.status)!=='draft'||Number(r.version)!==expected)throw new DomainError('VERSION_CONFLICT','مرجوعی قابل تایید نیست.');if(c.actor.id&&String(r.created_by??'')===c.actor.id)throw new DomainError('SEPARATION_OF_DUTIES','ایجادکننده نمی‌تواند مرجوعی خود را تایید کند.');await sql`UPDATE procurement.purchase_returns SET status='approved',approved_by=${c.actor.id??null}::uuid,version=version+1,updated_at=now() WHERE id=${id}::uuid`.execute(trx);await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.purchase_return.approve',resourceType:'purchase_return',resourceId:id,beforeData:r,afterData:{status:'approved'},requestId:c.requestId,traceId:c.traceId});});return this.get(id);}
 async ship(id:string,expected:number){const c=this.ctx.require();return this.tx.run(async trx=>{const r=await this.lock(trx,id);if(!r)throw new DomainError('PURCHASE_RETURN_NOT_FOUND','مرجوعی پیدا نشد.');this.scopes.assert(c.actor,'warehouse',String(r.warehouse_id));if(String(r.status)!=='approved'||Number(r.version)!==expected)throw new DomainError('VERSION_CONFLICT','مرجوعی قابل ارسال نیست.');const result=await this.inventory.returnToSupplier(trx,{purchase_return_id:id,warehouse_id:String(r.warehouse_id),actor_id:c.actor.id,items:(r.items as Array<Record<string,unknown>>).map(x=>({variant_id:String(x.variant_id),quantity:Number(x.quantity),stock_bucket:String(x.stock_bucket) as 'sellable'|'quarantine'|'damaged'}))});await sql`UPDATE procurement.purchase_returns SET status='shipped',version=version+1,updated_at=now() WHERE id=${id}::uuid`.execute(trx);await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.purchase_return.ship',resourceType:'purchase_return',resourceId:id,beforeData:r,afterData:{status:'shipped',...result},requestId:c.requestId,traceId:c.traceId});await this.outbox.append(trx,[procurementEvent('procurement.purchase_return.shipped.v1','purchase_return',id,expected+1,{purchase_return_id:id,supplier_id:r.supplier_id,warehouse_id:r.warehouse_id,...result})],c);return {id,status:'shipped',...result};});}
 async complete(id:string,expected:number){const c=this.ctx.require();await this.tx.run(async trx=>{const r=await this.lock(trx,id);if(!r||String(r.status)!=='shipped'||Number(r.version)!==expected)throw new DomainError('VERSION_CONFLICT','مرجوعی قابل تکمیل نیست.');this.scopes.assert(c.actor,'warehouse',String(r.warehouse_id));await sql`UPDATE procurement.purchase_returns SET status='completed',version=version+1,updated_at=now() WHERE id=${id}::uuid`.execute(trx);await this.outbox.append(trx,[procurementEvent('procurement.purchase_return.completed.v1','purchase_return',id,expected+1,{purchase_return_id:id,supplier_id:r.supplier_id})],c);});return this.get(id);}
}
