import { Inject, Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { TransactionManager } from '../../../platform/database/transaction-manager';
import { AuditWriter } from '../../../platform/audit/audit.writer';
import { OutboxWriter } from '../../../platform/outbox/outbox-writer';
import { RequestContextStore } from '../../../platform/request-context/request-context.store';
import { ScopePolicy } from '../../../platform/auth/scope-policy';
import { DomainError } from '../../../shared/errors/domain-error';
import { INVENTORY_PROCUREMENT_PORT, type InventoryProcurementPort } from '../../inventory/application/ports/inventory-procurement.port';
import { ProcurementRepository } from '../infrastructure/procurement.repository';
import { allocateByQuantity, allocateByValue, assertMoney, validateReceiptItem, type ReceiptItemInput } from '../domain/procurement.rules';
import { procurementEvent } from '../domain/procurement.events';

@Injectable()
export class ReceiptCostService{
 constructor(private readonly tx:TransactionManager,private readonly repo:ProcurementRepository,@Inject(INVENTORY_PROCUREMENT_PORT)private readonly inventory:InventoryProcurementPort,private readonly audit:AuditWriter,private readonly outbox:OutboxWriter,private readonly ctx:RequestContextStore,private readonly scopes:ScopePolicy){}
 receipts(){return this.repo.receipts(this.scopes.allowedIds(this.ctx.get()?.actor,'warehouse'));} async receipt(id:string){const r=await this.repo.receipt(id);if(r)this.scopes.assert(this.ctx.get()?.actor,'warehouse',String(r.warehouse_id));return r;}
 async createReceipt(input:{purchase_order_id?:string;supplier_id:string;warehouse_id:string;items:ReceiptItemInput[]}){const supplier=await this.repo.supplier(input.supplier_id);if(!supplier||String(supplier.status)!=='active')throw new DomainError('SUPPLIER_INACTIVE','تامین‌کننده فعال نیست.');this.scopes.assert(this.ctx.get()?.actor,'warehouse',input.warehouse_id);if(!input.items?.length)throw new DomainError('VALIDATION_ERROR','حداقل یک قلم رسید الزامی است.');for(const x of input.items)validateReceiptItem(x);const seen=new Set<string>();for(const x of input.items){if(seen.has(x.variant_id))throw new DomainError('DUPLICATE_ITEM','کالای تکراری در رسید مجاز نیست.');seen.add(x.variant_id);}const c=this.ctx.require(),id=randomUUID();await this.tx.run(async trx=>{if(input.purchase_order_id){const po=await this.repo.purchaseOrderForUpdate(trx,input.purchase_order_id);if(!po||!['sent','partially_received'].includes(String(po.status)))throw new DomainError('PURCHASE_ORDER_NOT_RECEIVABLE','سفارش خرید در وضعیت قابل دریافت نیست.');if(String(po.supplier_id)!==input.supplier_id||String(po.warehouse_id)!==input.warehouse_id)throw new DomainError('RECEIPT_PO_MISMATCH','تامین‌کننده یا انبار رسید با سفارش خرید سازگار نیست.');const poItems=new Map((po.items as Array<Record<string,unknown>>).map(x=>[String(x.id),x]));for(const x of input.items){if(!x.purchase_order_item_id)throw new DomainError('PO_ITEM_REQUIRED','شناسه قلم سفارش خرید برای رسید وابسته الزامی است.');const pi=poItems.get(x.purchase_order_item_id);if(!pi||String(pi.variant_id)!==x.variant_id)throw new DomainError('PO_ITEM_MISMATCH','قلم رسید با سفارش خرید سازگار نیست.');const owned=x.accepted_quantity+x.quarantine_quantity;const netUnit=Math.floor((Number(pi.ordered_quantity)*Number(pi.unit_cost_toman)-Number(pi.discount_toman))/Number(pi.ordered_quantity));if(owned>0 && x.unit_cost_toman!==netUnit)throw new DomainError('RECEIPT_COST_MISMATCH','بهای واحد رسید باید برابر بهای خالص سفارش پس از تخفیف باشد؛ هزینه جانبی از مسیر Landed Cost انجام می‌شود.');}}
 const number=await this.repo.nextNumber(trx,'GR');await this.repo.createReceipt(trx,{id,number,poId:input.purchase_order_id,supplierId:input.supplier_id,warehouseId:input.warehouse_id,createdBy:c.actor.id,items:input.items.map(x=>({id:randomUUID(),po_item_id:x.purchase_order_item_id??undefined,variant_id:x.variant_id,received:x.received_quantity,accepted:x.accepted_quantity,quarantine:x.quarantine_quantity,rejected:x.rejected_quantity,unit_cost_toman:x.unit_cost_toman}))});await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.receipt.create',resourceType:'goods_receipt',resourceId:id,afterData:input,requestId:c.requestId,traceId:c.traceId});});return this.receipt(id);}
 async updateReceipt(id:string,input:{items:ReceiptItemInput[]},expected:number){if(!input.items?.length)throw new DomainError('VALIDATION_ERROR','حداقل یک قلم رسید الزامی است.');for(const x of input.items)validateReceiptItem(x);const c=this.ctx.require();await this.tx.run(async trx=>{const before=await this.repo.receiptForUpdate(trx,id);if(!before)throw new DomainError('GOODS_RECEIPT_NOT_FOUND','رسید کالا پیدا نشد.');this.scopes.assert(c.actor,'warehouse',String(before.warehouse_id));if(before.purchase_order_id){const po=await this.repo.purchaseOrderForUpdate(trx,String(before.purchase_order_id));const poItems=new Map(((po?.items??[]) as Array<Record<string,unknown>>).map(x=>[String(x.id),x]));for(const x of input.items){if(!x.purchase_order_item_id)throw new DomainError('PO_ITEM_REQUIRED','قلم سفارش خرید الزامی است.');const pi=poItems.get(x.purchase_order_item_id);if(!pi||String(pi.variant_id)!==x.variant_id)throw new DomainError('PO_ITEM_MISMATCH','قلم رسید با سفارش سازگار نیست.');const netUnit=Math.floor((Number(pi.ordered_quantity)*Number(pi.unit_cost_toman)-Number(pi.discount_toman))/Number(pi.ordered_quantity));if(x.unit_cost_toman!==netUnit)throw new DomainError('RECEIPT_COST_MISMATCH','بهای رسید باید برابر بهای خالص سفارش باشد.');}}await this.repo.replaceReceiptDraft(trx,id,input.items.map(x=>({id:randomUUID(),po_item_id:x.purchase_order_item_id??undefined,variant_id:x.variant_id,received:x.received_quantity,accepted:x.accepted_quantity,quarantine:x.quarantine_quantity,rejected:x.rejected_quantity,unit_cost_toman:x.unit_cost_toman})),expected);await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.receipt.update',resourceType:'goods_receipt',resourceId:id,beforeData:before,afterData:input,requestId:c.requestId,traceId:c.traceId});});return this.receipt(id);}
 async transitionReceipt(id:string,target:'submitted'|'posted'|'reversed',expected:number,reason?:string){const c=this.ctx.require();await this.tx.run(async trx=>{const gr=await this.repo.receiptForUpdate(trx,id);if(!gr)throw new DomainError('GOODS_RECEIPT_NOT_FOUND','رسید کالا پیدا نشد.');this.scopes.assert(c.actor,'warehouse',String(gr.warehouse_id));const current=String(gr.status);if(target==='submitted'&&current!=='draft')throw new DomainError('INVALID_STATE_TRANSITION','فقط رسید پیش‌نویس قابل ارسال است.');if(target==='posted'&&current!=='submitted')throw new DomainError('INVALID_STATE_TRANSITION','فقط رسید ارسال‌شده قابل ثبت قطعی است.');if(target==='reversed'&&current!=='posted')throw new DomainError('INVALID_STATE_TRANSITION','فقط رسید ثبت‌شده قابل برگشت است.');if(target==='reversed'&&!String(reason??'').trim())throw new DomainError('REASON_REQUIRED','دلیل برگشت رسید الزامی است.');const items=gr.items as Array<Record<string,unknown>>;
  if(target==='posted'){
   if(gr.purchase_order_id){for(const x of items){const owned=Number(x.accepted_quantity)+Number(x.quarantine_quantity);if(owned>0)await this.repo.incrementReceived(trx,String(x.purchase_order_item_id),owned);}}
   await this.inventory.receiveGoods(trx,{warehouse_id:String(gr.warehouse_id),goods_receipt_id:id,actor_id:c.actor.id,items:items.map(x=>({goods_receipt_item_id:String(x.id),variant_id:String(x.variant_id),accepted_quantity:Number(x.accepted_quantity),quarantine_quantity:Number(x.quarantine_quantity),unit_cost_toman:Number(x.unit_cost_toman)}))});
  }
  if(target==='reversed'){
   if(gr.purchase_order_id){const po=await this.repo.purchaseOrderForUpdate(trx,String(gr.purchase_order_id));if(po&&String(po.status)==='closed')throw new DomainError('PO_CLOSED_RECEIPT_REVERSE_BLOCKED','رسید سفارش خرید بسته‌شده قابل برگشت مستقیم نیست.');}
   await this.inventory.reverseGoodsReceipt(trx,{goods_receipt_id:id,warehouse_id:String(gr.warehouse_id),actor_id:c.actor.id,items:items.map(x=>({goods_receipt_item_id:String(x.id),variant_id:String(x.variant_id),accepted_quantity:Number(x.accepted_quantity),quarantine_quantity:Number(x.quarantine_quantity)}))});
   if(gr.purchase_order_id){for(const x of items){const owned=Number(x.accepted_quantity)+Number(x.quarantine_quantity);if(owned>0)await this.repo.decrementReceived(trx,String(x.purchase_order_item_id),owned);}}
  }
  await this.repo.updateReceiptStatus(trx,id,target,expected,c.actor.id,reason);if(gr.purchase_order_id)await this.repo.refreshPOReceiptStatus(trx,String(gr.purchase_order_id));await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:`procurement.receipt.${target}`,resourceType:'goods_receipt',resourceId:id,beforeData:gr,afterData:{status:target},reason,requestId:c.requestId,traceId:c.traceId});if(target==='posted'||target==='reversed')await this.outbox.append(trx,[procurementEvent(`procurement.goods_receipt.${target}.v1`,'goods_receipt',id,expected+1,{goods_receipt_id:id,purchase_order_id:gr.purchase_order_id,warehouse_id:gr.warehouse_id})],c);
 });return this.receipt(id);}

 landedCosts(){return this.repo.landedCosts(this.scopes.allowedIds(this.ctx.get()?.actor,'warehouse'));} async landedCost(id:string){const r=await this.repo.landedCost(id);if(r?.warehouse_id)this.scopes.assert(this.ctx.get()?.actor,'warehouse',String(r.warehouse_id));return r;}
 async createLandedCost(input:{purchase_order_id?:string;goods_receipt_id?:string;cost_type:string;amount_toman:number;allocation_method?:'quantity'|'value'|'manual'}){assertMoney(input.amount_toman);if(!['shipping','insurance','customs','handling','other'].includes(input.cost_type))throw new DomainError('INVALID_LANDED_COST_TYPE','نوع هزینه جانبی معتبر نیست.');if(input.allocation_method&&!['quantity','value','manual'].includes(input.allocation_method))throw new DomainError('INVALID_ALLOCATION_METHOD','روش تخصیص معتبر نیست.');if(!input.purchase_order_id&&!input.goods_receipt_id)throw new DomainError('VALIDATION_ERROR','سفارش خرید یا رسید کالا الزامی است.');const c=this.ctx.require(),id=randomUUID();await this.tx.run(async trx=>{let warehouseId:string|undefined;let resolvedPoId=input.purchase_order_id;if(input.goods_receipt_id){const r=await this.repo.receiptForUpdate(trx,input.goods_receipt_id);if(!r||String(r.status)!=='posted')throw new DomainError('GOODS_RECEIPT_NOT_POSTED','رسید کالا ثبت قطعی نشده است.');warehouseId=String(r.warehouse_id);if(r.purchase_order_id){if(resolvedPoId&&resolvedPoId!==String(r.purchase_order_id))throw new DomainError('LANDED_COST_PO_MISMATCH','سفارش خرید و رسید کالا با هم سازگار نیستند.');resolvedPoId=String(r.purchase_order_id);}}else if(resolvedPoId){const po=await this.repo.purchaseOrderForUpdate(trx,resolvedPoId);if(!po)throw new DomainError('PURCHASE_ORDER_NOT_FOUND','سفارش خرید پیدا نشد.');warehouseId=String(po.warehouse_id);}if(warehouseId)this.scopes.assert(c.actor,'warehouse',warehouseId);const ref=await this.repo.nextNumber(trx,'LC');await this.repo.createLandedCost(trx,{id,reference:ref,poId:resolvedPoId,receiptId:input.goods_receipt_id,costType:input.cost_type,amount:input.amount_toman,method:input.allocation_method??'quantity',createdBy:c.actor.id});});return this.landedCost(id);}
 async previewAllocation(id:string,manual?:Array<{goods_receipt_item_id:string;allocated_amount_toman:number}>){return this.tx.run(async trx=>{const lc=await this.repo.landedCostForUpdate(trx,id);if(!lc)throw new DomainError('LANDED_COST_NOT_FOUND','هزینه جانبی پیدا نشد.');if(String(lc.status)!=='draft')throw new DomainError('STATE_ALREADY_FINALIZED','هزینه جانبی قبلاً نهایی شده است.');const candidates=await this.repo.allocationCandidates(trx,lc);let allocations;if(String(lc.allocation_method)==='manual'){if(!manual?.length)throw new DomainError('MANUAL_ALLOCATION_REQUIRED','تخصیص دستی الزامی است.');for(const x of manual)assertMoney(x.allocated_amount_toman);if(new Set(manual.map(x=>x.goods_receipt_item_id)).size!==manual.length)throw new DomainError('DUPLICATE_ALLOCATION_ITEM','قلم تخصیص دستی تکراری است.');const allowed=new Set(candidates.map(x=>String(x.id)));if(manual.some(x=>!allowed.has(x.goods_receipt_item_id)))throw new DomainError('INVALID_ALLOCATION_ITEM','قلم تخصیص متعلق به رسیدهای این هزینه نیست.');if(manual.reduce((s,x)=>s+x.allocated_amount_toman,0)!==Number(lc.amount_toman))throw new DomainError('LANDED_COST_ALLOCATION_MISMATCH','جمع تخصیص باید دقیقاً برابر هزینه جانبی باشد.');allocations=manual;}else if(String(lc.allocation_method)==='value')allocations=allocateByValue(Number(lc.amount_toman),candidates.map(x=>({id:String(x.id),quantity:Number(x.accepted_quantity)+Number(x.quarantine_quantity),unit_cost_toman:Number(x.unit_cost_toman)})).filter(x=>x.quantity>0));else allocations=allocateByQuantity(Number(lc.amount_toman),candidates.map(x=>({id:String(x.id),quantity:Number(x.accepted_quantity)+Number(x.quarantine_quantity)})).filter(x=>x.quantity>0));return {landed_cost_id:id,amount_toman:Number(lc.amount_toman),allocations};});}
 async finalizeLandedCost(id:string,expected:number,manual?:Array<{goods_receipt_item_id:string;allocated_amount_toman:number}>){const c=this.ctx.require();return this.tx.run(async trx=>{const lc=await this.repo.landedCostForUpdate(trx,id);if(!lc)throw new DomainError('LANDED_COST_NOT_FOUND','هزینه جانبی پیدا نشد.');if(Number(lc.version)!==expected||String(lc.status)!=='draft')throw new DomainError('VERSION_CONFLICT','هزینه جانبی همزمان تغییر کرده یا نهایی شده است.');const candidates=await this.repo.allocationCandidates(trx,lc);let allocations;if(String(lc.allocation_method)==='manual'){if(!manual?.length||manual.reduce((s,x)=>s+x.allocated_amount_toman,0)!==Number(lc.amount_toman))throw new DomainError('LANDED_COST_ALLOCATION_MISMATCH','تخصیص دستی نامعتبر است.');for(const x of manual)assertMoney(x.allocated_amount_toman);if(new Set(manual.map(x=>x.goods_receipt_item_id)).size!==manual.length)throw new DomainError('DUPLICATE_ALLOCATION_ITEM','قلم تخصیص دستی تکراری است.');const allowed=new Set(candidates.map(x=>String(x.id)));if(manual.some(x=>!allowed.has(x.goods_receipt_item_id)))throw new DomainError('INVALID_ALLOCATION_ITEM','قلم تخصیص نامعتبر است.');allocations=manual;}else if(String(lc.allocation_method)==='value')allocations=allocateByValue(Number(lc.amount_toman),candidates.map(x=>({id:String(x.id),quantity:Number(x.accepted_quantity)+Number(x.quarantine_quantity),unit_cost_toman:Number(x.unit_cost_toman)})).filter(x=>x.quantity>0));else allocations=allocateByQuantity(Number(lc.amount_toman),candidates.map(x=>({id:String(x.id),quantity:Number(x.accepted_quantity)+Number(x.quarantine_quantity)})).filter(x=>x.quantity>0));await this.repo.replaceAllocations(trx,id,allocations);let inventory=0,cogs=0;for(const a of allocations){const r=await this.inventory.revalueReceiptItem(trx,{goods_receipt_item_id:a.goods_receipt_item_id,additional_total_toman:a.allocated_amount_toman,source_landed_cost_id:id});inventory+=r.inventory_revaluation_toman;cogs+=r.consumed_cogs_revaluation_toman;}await this.repo.finalizeLandedCost(trx,id,expected);await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.landed_cost.finalize',resourceType:'landed_cost',resourceId:id,beforeData:lc,afterData:{allocations,inventory_revaluation_toman:inventory,consumed_cogs_revaluation_toman:cogs},requestId:c.requestId,traceId:c.traceId});await this.outbox.append(trx,[procurementEvent('procurement.landed_cost.finalized.v1','landed_cost',id,expected+1,{landed_cost_id:id,amount_toman:lc.amount_toman,inventory_revaluation_toman:inventory,consumed_cogs_revaluation_toman:cogs})],c);return {id,status:'finalized',inventory_revaluation_toman:inventory,consumed_cogs_revaluation_toman:cogs,allocations};});}
 async invoices(){return this.repo.invoices(this.scopes.allowedIds(this.ctx.get()?.actor,'warehouse'));} async createInvoice(input:{supplier_id:string;purchase_order_id?:string;invoice_number:string;invoice_date:string;amount_toman:number}){assertMoney(input.amount_toman);if(!String(input.invoice_number??'').trim())throw new DomainError('VALIDATION_ERROR','شماره فاکتور الزامی است.');const supplier=await this.repo.supplier(input.supplier_id);if(!supplier||String(supplier.status)!=='active')throw new DomainError('SUPPLIER_INACTIVE','تامین‌کننده فعال نیست.');const c=this.ctx.require(),id=randomUUID();await this.tx.run(async trx=>{if(input.purchase_order_id){const po=await this.repo.purchaseOrderForUpdate(trx,input.purchase_order_id);if(!po||String(po.supplier_id)!==input.supplier_id)throw new DomainError('INVOICE_PO_MISMATCH','فاکتور با سفارش خرید سازگار نیست.');this.scopes.assert(c.actor,'warehouse',String(po.warehouse_id));}await this.repo.createInvoice(trx,{id,supplierId:input.supplier_id,poId:input.purchase_order_id,invoiceNumber:input.invoice_number,invoiceDate:input.invoice_date,amount:input.amount_toman});await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:'procurement.invoice.create',resourceType:'supplier_invoice',resourceId:id,afterData:input,requestId:c.requestId,traceId:c.traceId});});return {id};} async transitionInvoice(id:string,target:'matched'|'disputed'|'cancelled',expected:number,reason?:string){if((target==='disputed'||target==='cancelled')&&!String(reason??'').trim())throw new DomainError('REASON_REQUIRED','دلیل الزامی است.');const c=this.ctx.require();return this.tx.run(async trx=>{const inv=await this.repo.invoiceForUpdate(trx,id);if(!inv)throw new DomainError('SUPPLIER_INVOICE_NOT_FOUND','فاکتور تامین‌کننده پیدا نشد.');if(String(inv.status)!=='recorded')throw new DomainError('INVALID_STATE_TRANSITION','فاکتور در وضعیت قابل بررسی نیست.');if(target==='matched'&&!inv.purchase_order_id)throw new DomainError('SUPPLIER_INVOICE_PO_REQUIRED','برای تطبیق فاکتور، سفارش خرید مبنا الزامی است.');if(inv.purchase_order_id){const po=await this.repo.purchaseOrderForUpdate(trx,String(inv.purchase_order_id));if(po)this.scopes.assert(c.actor,'warehouse',String(po.warehouse_id));if(target==='matched'&&po&&Number(inv.amount_toman)!==Number(po.total_toman))throw new DomainError('SUPPLIER_INVOICE_AMOUNT_MISMATCH','مبلغ فاکتور با مبلغ سفارش خرید برابر نیست.');}await this.repo.updateInvoiceStatus(trx,id,target,expected,reason);await this.audit.writeWith(trx,{actorType:c.actor.type,actorId:c.actor.id,action:`procurement.invoice.${target}`,resourceType:'supplier_invoice',resourceId:id,beforeData:inv,afterData:{status:target},reason,requestId:c.requestId,traceId:c.traceId});return{id,status:target};});}
}
