import { Inject,Injectable } from '@nestjs/common';
import { Kysely,sql } from 'kysely';
import { KYSELY_DB } from '../../../platform/database/database.tokens';
import { DatabaseSchema } from '../../../platform/database/database.types';
import { DatabaseExecutor } from '../../../platform/database/transaction-manager';
@Injectable() export class NotificationTemplateRepository{
 constructor(@Inject(KYSELY_DB)private readonly db:Kysely<DatabaseSchema>){}
 async list(filter:{key?:string;channel?:string;locale?:string}={}){return (await sql<any>`SELECT * FROM notifications.templates WHERE (${filter.key??null}::text IS NULL OR template_key=${filter.key??null}) AND (${filter.channel??null}::text IS NULL OR channel=${filter.channel??null}) AND (${filter.locale??null}::text IS NULL OR locale=${filter.locale??null}) ORDER BY template_key,channel,locale,version DESC LIMIT 500`.execute(this.db)).rows;}
 async byId(id:string,ex:DatabaseExecutor=this.db,lock=false){const q=lock?sql<any>`SELECT * FROM notifications.templates WHERE id=${id}::uuid FOR UPDATE`:sql<any>`SELECT * FROM notifications.templates WHERE id=${id}::uuid`;return (await q.execute(ex)).rows[0]??null;}
 async active(key:string,channel:string,locale:string,ex:DatabaseExecutor=this.db){return (await sql<any>`SELECT * FROM notifications.templates WHERE template_key=${key} AND channel=${channel} AND locale=${locale} AND status='active' LIMIT 1`.execute(ex)).rows[0]??null;}
 async nextVersion(ex:DatabaseExecutor,key:string,channel:string,locale:string){const lockKey=`${key}|${channel}|${locale}`;await sql`SELECT pg_advisory_xact_lock(hashtext(${lockKey}))`.execute(ex);const r=(await sql<any>`SELECT COALESCE(MAX(version),0)+1 next_version FROM notifications.templates WHERE template_key=${key} AND channel=${channel} AND locale=${locale}`.execute(ex)).rows[0];return Number(r?.next_version??1);}
 async create(ex:DatabaseExecutor,i:any){await sql`INSERT INTO notifications.templates(id,template_key,name_fa,channel,locale,version,status,subject_template,body_template,required_variables,allowed_variables,strict_variables,created_by) VALUES(${i.id}::uuid,${i.key},${i.nameFa??null},${i.channel},${i.locale},${i.version},'draft',${i.subject??null},${i.body},${JSON.stringify(i.required)}::jsonb,${JSON.stringify(i.allowed)}::jsonb,${i.strict},${i.actorId}::uuid)`.execute(ex);return this.byId(i.id,ex);}
 async activate(ex:DatabaseExecutor,id:string,actorId:string){const row=await this.byId(id,ex,true);if(!row)return null;await sql`UPDATE notifications.templates SET status='retired',retired_by=${actorId}::uuid,retired_at=now() WHERE template_key=${row.template_key} AND channel=${row.channel} AND locale=${row.locale} AND status='active' AND id<>${id}::uuid`.execute(ex);const r=await sql<any>`UPDATE notifications.templates SET status='active',activated_by=${actorId}::uuid,activated_at=now(),retired_by=NULL,retired_at=NULL WHERE id=${id}::uuid AND status='draft' RETURNING *`.execute(ex);return r.rows[0]??null;}
 async retire(ex:DatabaseExecutor,id:string,actorId:string){const r=await sql<any>`UPDATE notifications.templates SET status='retired',retired_by=${actorId}::uuid,retired_at=now() WHERE id=${id}::uuid AND status IN ('draft','active') RETURNING *`.execute(ex);return r.rows[0]??null;}
}
