import { Inject,Injectable } from '@nestjs/common';
import { Kysely,sql } from 'kysely';
import { KYSELY_DB } from '../../../platform/database/database.tokens';
import { DatabaseSchema } from '../../../platform/database/database.types';
import { DatabaseExecutor } from '../../../platform/database/transaction-manager';
@Injectable()
export class NotificationDeliveryRepository{
 constructor(@Inject(KYSELY_DB)private readonly db:Kysely<DatabaseSchema>){}
 async claim(ex:DatabaseExecutor,limit:number){const rows=(await sql<any>`SELECT d.*,i.recipient_subject_type,i.recipient_subject_id,i.notification_kind FROM notifications.deliveries d JOIN notifications.notification_intents i ON i.id=d.notification_id WHERE d.channel IN ('sms','email') AND (i.scheduled_at IS NULL OR i.scheduled_at<=now()) AND (d.status='pending' OR (d.status='retry_wait' AND d.next_attempt_at<=now())) ORDER BY d.created_at,d.id FOR UPDATE OF d SKIP LOCKED LIMIT ${Math.min(Math.max(limit,1),100)}`.execute(ex)).rows;const out=[];for(const r of rows){const u=(await sql<any>`UPDATE notifications.deliveries SET status='processing',processing_started_at=now(),next_attempt_at=NULL WHERE id=${r.id}::uuid AND status IN ('pending','retry_wait') RETURNING *`.execute(ex)).rows[0];if(u){await sql`UPDATE notifications.notification_intents SET status='processing',updated_at=now() WHERE id=${r.notification_id}::uuid AND status IN ('queued','failed','partially_delivered')`.execute(ex);out.push({...r,...u});}}return out;}
 async startAttempt(ex:DatabaseExecutor,d:any,providerKey:string|null){const attemptNo=Number(d.retry_count)+1;const r=(await sql<any>`INSERT INTO notifications.delivery_attempts(delivery_id,attempt_no,provider_key,status) VALUES(${d.id}::uuid,${attemptNo},${providerKey},'started') RETURNING *`.execute(ex)).rows[0];return{...r,attemptNo};}
 async finishAttempt(ex:DatabaseExecutor,attemptId:string,status:string,i:any){await sql`UPDATE notifications.delivery_attempts SET status=${status},error_code=${i.errorCode??null},error_message=${i.errorMessage??null},provider_message_id=${i.providerMessageId??null},metadata=${JSON.stringify(i.metadata??{})}::jsonb,finished_at=now() WHERE id=${attemptId}::uuid AND status='started'`.execute(ex);}
 async delivered(ex:DatabaseExecutor,id:string,providerKey:string,providerMessageId:string|null){return (await sql<any>`UPDATE notifications.deliveries SET status='delivered',provider_key=${providerKey},provider_message_id=${providerMessageId},delivered_at=now(),last_error_code=NULL,last_error_message=NULL WHERE id=${id}::uuid AND status='processing' RETURNING *`.execute(ex)).rows[0]??null;}
 async retry(ex:DatabaseExecutor,id:string,attemptNo:number,next:Date,code:string,msg:string|null){return (await sql<any>`UPDATE notifications.deliveries SET status='retry_wait',retry_count=${attemptNo},next_attempt_at=${next},last_error_code=${code},last_error_message=${msg} WHERE id=${id}::uuid AND status='processing' RETURNING *`.execute(ex)).rows[0]??null;}
 async failed(ex:DatabaseExecutor,id:string,attemptNo:number,code:string,msg:string|null,dead=false){const status=dead?'dead_lettered':'failed',col=dead?sql`dead_lettered_at=now()`:sql`failed_at=now()`;return (await sql<any>`UPDATE notifications.deliveries SET status=${status},retry_count=${attemptNo},${col},last_error_code=${code},last_error_message=${msg} WHERE id=${id}::uuid AND status='processing' RETURNING *`.execute(ex)).rows[0]??null;}
 async blocked(ex:DatabaseExecutor,id:string,attemptNo:number,code:string,msg:string|null){return (await sql<any>`UPDATE notifications.deliveries SET status='blocked',retry_count=${attemptNo},blocked_at=now(),last_error_code=${code},last_error_message=${msg} WHERE id=${id}::uuid AND status='processing' RETURNING *`.execute(ex)).rows[0]??null;}
 async adminList(opt:any={}){const limit=Math.min(Math.max(Number(opt.limit??50),1),100),offset=Math.max(Number(opt.offset??0),0);return (await sql<any>`SELECT i.*,COALESCE(jsonb_agg(jsonb_build_object('id',d.id,'channel',d.channel,'status',d.status,'retry_count',d.retry_count,'max_attempts',d.max_attempts,'destination_masked',d.destination_masked,'last_error_code',d.last_error_code,'delivered_at',d.delivered_at,'failed_at',d.failed_at,'dead_lettered_at',d.dead_lettered_at)) FILTER (WHERE d.id IS NOT NULL),'[]'::jsonb) deliveries FROM notifications.notification_intents i LEFT JOIN notifications.deliveries d ON d.notification_id=i.id WHERE (${opt.status??null}::text IS NULL OR i.status=${opt.status??null}) AND (${opt.channel??null}::text IS NULL OR EXISTS(SELECT 1 FROM notifications.deliveries dx WHERE dx.notification_id=i.id AND dx.channel=${opt.channel??null})) GROUP BY i.id ORDER BY i.created_at DESC,i.id LIMIT ${limit} OFFSET ${offset}`.execute(this.db)).rows;}
 async adminGet(id:string,ex:DatabaseExecutor=this.db,lock=false){const iq=lock?sql<any>`SELECT * FROM notifications.notification_intents WHERE id=${id}::uuid FOR UPDATE`:sql<any>`SELECT * FROM notifications.notification_intents WHERE id=${id}::uuid`;const intent=(await iq.execute(ex)).rows[0];if(!intent)return null;const deliveries=(await sql<any>`SELECT d.*,COALESCE((SELECT jsonb_agg(a ORDER BY a.attempt_no) FROM notifications.delivery_attempts a WHERE a.delivery_id=d.id),'[]'::jsonb) attempts FROM notifications.deliveries d WHERE d.notification_id=${id}::uuid ORDER BY d.created_at,d.id`.execute(ex)).rows;return{...intent,deliveries};}
 async manualRetry(ex:DatabaseExecutor,notificationId:string){await sql`SELECT set_config('eqcofe.notification_manual_retry','1',true)`.execute(ex);const rows=(await sql<any>`UPDATE notifications.deliveries SET status='pending',next_attempt_at=NULL,processing_started_at=NULL,blocked_at=NULL,failed_at=NULL,dead_lettered_at=NULL,last_error_code=NULL,last_error_message=NULL WHERE notification_id=${notificationId}::uuid AND channel IN ('sms','email') AND status IN ('blocked','failed','dead_lettered','retry_wait') RETURNING *`.execute(ex)).rows;if(rows.length)await sql`UPDATE notifications.notification_intents SET status='queued',completed_at=NULL,updated_at=now() WHERE id=${notificationId}::uuid AND status IN ('failed','dead_lettered','partially_delivered','processing')`.execute(ex);return rows;}

 async recoverStaleProcessing(ex:DatabaseExecutor,cutoff:Date,limit:number){const rows=(await sql<any>`SELECT d.id,d.notification_id FROM notifications.deliveries d WHERE d.status='processing' AND d.processing_started_at<${cutoff} ORDER BY d.processing_started_at,d.id FOR UPDATE SKIP LOCKED LIMIT ${Math.min(Math.max(limit,1),100)}`.execute(ex)).rows;const recovered=[];for(const r of rows){await sql`UPDATE notifications.delivery_attempts SET status='retryable_failed',error_code='NOTIFICATION_WORKER_STALE',error_message='ارسال توسط بازیابی عملیاتی مجدداً صف شد.',finished_at=now() WHERE delivery_id=${r.id}::uuid AND status='started'`.execute(ex);const row=(await sql<any>`UPDATE notifications.deliveries SET status='retry_wait',next_attempt_at=now(),processing_started_at=NULL,last_error_code='NOTIFICATION_WORKER_STALE',last_error_message='ارسال توسط بازیابی عملیاتی مجدداً صف شد.' WHERE id=${r.id}::uuid AND status='processing' RETURNING *`.execute(ex)).rows[0];if(row){recovered.push(row);await this.refreshIntent(ex,r.notification_id);}}return recovered;}
 async operationsSummary(staleBefore:Date){const intents=(await sql<any>`SELECT status,count(*)::int count FROM notifications.notification_intents GROUP BY status ORDER BY status`.execute(this.db)).rows;const deliveries=(await sql<any>`SELECT channel,status,count(*)::int count FROM notifications.deliveries GROUP BY channel,status ORDER BY channel,status`.execute(this.db)).rows;const meta=(await sql<any>`SELECT (SELECT count(*)::int FROM notifications.notification_intents WHERE status='queued' AND scheduled_at>now()) scheduled_future,(SELECT count(*)::int FROM notifications.deliveries WHERE status='processing' AND processing_started_at<${staleBefore}) stale_processing,(SELECT count(*)::int FROM notifications.delivery_attempts WHERE status IN ('retryable_failed','permanent_failed','blocked') AND started_at>=now()-interval '24 hours') failed_attempts_24h,(SELECT EXTRACT(EPOCH FROM (now()-min(d.created_at)))::bigint FROM notifications.deliveries d JOIN notifications.notification_intents i ON i.id=d.notification_id WHERE d.status IN ('pending','retry_wait') AND (i.scheduled_at IS NULL OR i.scheduled_at<=now())) oldest_due_seconds`.execute(this.db)).rows[0];return{intents,deliveries,...meta};}

 async refreshIntent(ex:DatabaseExecutor,notificationId:string){const rows=(await sql<any>`SELECT status FROM notifications.deliveries WHERE notification_id=${notificationId}::uuid`.execute(ex)).rows.map((r:any)=>r.status);if(!rows.length)return;const delivered=rows.filter((s:string)=>s==='delivered').length,active=rows.some((s:string)=>['pending','processing','retry_wait'].includes(s)),dead=rows.every((s:string)=>['dead_lettered','cancelled'].includes(s));let status:string;if(delivered===rows.length)status='delivered';else if(delivered>0)status='partially_delivered';else if(active)status='processing';else if(dead)status='dead_lettered';else status='failed';await sql`UPDATE notifications.notification_intents SET status=${status},completed_at=CASE WHEN ${status} IN ('delivered','failed','dead_lettered') THEN now() ELSE completed_at END WHERE id=${notificationId}::uuid AND status<>${status}`.execute(ex);}
}
