import { Inject,Injectable } from '@nestjs/common';
import { Kysely,sql } from 'kysely';
import { KYSELY_DB } from '../../../platform/database/database.tokens';
import { DatabaseSchema } from '../../../platform/database/database.types';
import { DatabaseExecutor } from '../../../platform/database/transaction-manager';
@Injectable()
export class NotificationRepository{
 constructor(@Inject(KYSELY_DB)private readonly db:Kysely<DatabaseSchema>){}
 async byIdempotency(key:string,ex:DatabaseExecutor=this.db){return (await sql<any>`SELECT * FROM notifications.notification_intents WHERE idempotency_key=${key} LIMIT 1`.execute(ex)).rows[0]??null;}
 async bySource(ex:DatabaseExecutor,i:any){return (await sql<any>`SELECT * FROM notifications.notification_intents WHERE source_type=${i.sourceType} AND source_id=${i.sourceId} AND notification_kind=${i.kind} AND recipient_subject_type=${i.subjectType} AND recipient_subject_id=${i.subjectId} AND routing_revision=${i.routingRevision} LIMIT 1`.execute(ex)).rows[0]??null;}
 async createIntent(ex:DatabaseExecutor,i:any){const r=await sql<any>`INSERT INTO notifications.notification_intents(id,notification_kind,source_type,source_id,source_event_id,recipient_subject_type,recipient_subject_id,routing_revision,status,priority,locale,payload,idempotency_key,scheduled_at) VALUES(${i.id}::uuid,${i.kind},${i.sourceType},${i.sourceId},${i.sourceEventId??null}::uuid,${i.subjectType},${i.subjectId},${i.routingRevision},'queued',${i.priority},${i.locale},${JSON.stringify(i.payload)}::jsonb,${i.idempotencyKey??null},${i.scheduledAt??null}) ON CONFLICT DO NOTHING RETURNING *`.execute(ex);return r.rows[0]??null;}
 async createDelivery(ex:DatabaseExecutor,i:any){const r=await sql<any>`INSERT INTO notifications.deliveries(id,notification_id,channel,status,template_id,template_key,template_version,destination_masked,rendered_subject,rendered_body,rendered_sha256,max_attempts,delivered_at) VALUES(${i.id}::uuid,${i.notificationId}::uuid,${i.channel},${i.status??'pending'},${i.templateId}::uuid,${i.templateKey},${i.templateVersion},${i.destinationMasked??null},${i.subject??null},${i.body},${i.sha256},${i.maxAttempts??5},${i.status==='delivered'?new Date():null}) ON CONFLICT(notification_id,channel) DO NOTHING RETURNING *`.execute(ex);return r.rows[0]??null;}
 async createInAppReceipt(ex:DatabaseExecutor,i:any){const r=await sql<any>`INSERT INTO notifications.in_app_receipts(delivery_id,recipient_subject_type,recipient_subject_id,title,body,payload) VALUES(${i.deliveryId}::uuid,${i.subjectType},${i.subjectId},${i.title??null},${i.body},${JSON.stringify(i.payload??{})}::jsonb) ON CONFLICT(delivery_id) DO NOTHING RETURNING *`.execute(ex);return r.rows[0]??null;}
 async inbox(subjectType:string,subjectId:string,opt:any={}){const limit=Math.min(Math.max(Number(opt.limit??50),1),100),offset=Math.max(Number(opt.offset??0),0);return (await sql<any>`SELECT r.*,d.notification_id,d.channel,i.notification_kind,i.created_at notification_created_at FROM notifications.in_app_receipts r JOIN notifications.deliveries d ON d.id=r.delivery_id JOIN notifications.notification_intents i ON i.id=d.notification_id WHERE r.recipient_subject_type=${subjectType} AND r.recipient_subject_id=${subjectId} AND (${Boolean(opt.unreadOnly)}=false OR r.read_at IS NULL) ORDER BY r.created_at DESC,r.id LIMIT ${limit} OFFSET ${offset}`.execute(this.db)).rows;}
 async markRead(ex:DatabaseExecutor,id:string,subjectType:string,subjectId:string){const r=await sql<any>`UPDATE notifications.in_app_receipts SET read_at=COALESCE(read_at,now()),updated_at=now() WHERE id=${id}::uuid AND recipient_subject_type=${subjectType} AND recipient_subject_id=${subjectId} RETURNING *`.execute(ex);return r.rows[0]??null;}
 async acknowledge(ex:DatabaseExecutor,id:string,subjectType:string,subjectId:string){const r=await sql<any>`UPDATE notifications.in_app_receipts SET read_at=COALESCE(read_at,now()),acknowledged_at=now(),updated_at=now() WHERE id=${id}::uuid AND recipient_subject_type=${subjectType} AND recipient_subject_id=${subjectId} AND acknowledged_at IS NULL RETURNING *`.execute(ex);return r.rows[0]??null;}
}
