import { Form, Link } from "react-router";
import type { CheckoutFlowMessage, CheckoutReviewPageData, CheckoutReviewPreparedData } from "./checkout-flow.server.js";
const toman = new Intl.NumberFormat("fa-IR");
export function CheckoutReviewView({loaderData,actionData,busy}:{loaderData:CheckoutReviewPageData;actionData:CheckoutReviewPreparedData|CheckoutFlowMessage|null;busy:boolean}) {
  if ("status" in loaderData) return <section className="checkout-flow"><h1>بازبینی سفارش</h1><p className="checkout-flow__alert" role="alert">{loaderData.message}</p><Link className="checkout-back-link" to="/checkout/delivery">بازگشت به روش تحویل</Link></section>;
  const prepared=actionData?.status==="prepared"?actionData:null;
  return <section className="checkout-flow" aria-labelledby="checkout-review-title">
    <header className="checkout-flow__intro"><p>مرحله ۵ از ۵</p><h1 id="checkout-review-title">بازبینی و ثبت سفارش</h1><p>Quote، موجودی، تخفیف، ارسال و رزرو پیش از ثبت سفارش دوباره از سرور گرفته می‌شوند.</p></header>
    {actionData?.status==="error"?<p className="checkout-flow__alert" role="alert">{actionData.message}</p>:null}
    <div className="checkout-review-grid"><div><article className="checkout-review-card"><h2>نشانی و تحویل</h2><p>{loaderData.address.recipient_name} — {loaderData.address.address_line}</p><p>{loaderData.shippingMethod.name_fa}</p></article>
      {prepared?<article className="checkout-review-card"><h2>اقلام و قیمت معتبر</h2><ul className="checkout-review-items">{prepared.quote.items.map(item=><li key={item.variant_id}><span>{item.product_name} × {toman.format(item.quantity)}</span><strong>{toman.format(item.line_total_toman)} تومان</strong></li>)}</ul><p>نوع مشتری: {prepared.quote.customer_type==="wholesale"?"عمده":"خرده"}</p><p>انقضای Quote: <bdi>{prepared.quote.expires_at}</bdi></p><p>رزرو: {prepared.reservation.status} — <bdi>{prepared.reservation.expires_at}</bdi></p></article>:
      <article className="checkout-review-card"><h2>بازسازی بازبینی</h2><p>مرور مجدد صفحه، نتیجه قبلی را موفق فرض نمی‌کند.</p><Form method="post"><input type="hidden" name="intent" value="prepare"/><input type="hidden" name="shipping_method_id" value={loaderData.shippingMethod.id}/><input type="hidden" name="quote_idempotency_key" value={loaderData.quoteIdempotencyKey}/><input type="hidden" name="reservation_idempotency_key" value={loaderData.reservationIdempotencyKey}/><button type="submit" disabled={busy}>بازسازی Quote و رزرو</button></Form></article>}</div>
      <aside className="checkout-review-summary"><h2>جمع سفارش</h2>{prepared?<><dl><div><dt>جمع کالاها</dt><dd>{toman.format(prepared.quote.subtotal_toman)} تومان</dd></div><div><dt>تخفیف</dt><dd>{toman.format(prepared.quote.discount_toman)} تومان</dd></div><div><dt>ارسال</dt><dd>{toman.format(prepared.quote.shipping_toman)} تومان</dd></div><div><dt>مالیات</dt><dd>{toman.format(prepared.quote.tax_toman)} تومان</dd></div><div className="checkout-review-summary__total"><dt>مبلغ نهایی</dt><dd>{toman.format(prepared.quote.total_toman)} تومان</dd></div></dl><Form method="post"><input type="hidden" name="intent" value="create-order"/><input type="hidden" name="order_idempotency_key" value={prepared.orderIdempotencyKey}/><button type="submit" disabled={busy}>ثبت سفارش</button></Form><p className="checkout-review-note">پرداخت در Stage 63-G آغاز می‌شود؛ این مرحله نتیجه پرداخت را جعل نمی‌کند.</p></>:<p>ابتدا بازبینی معتبر را بسازید.</p>}</aside>
    </div><Link className="checkout-back-link" to="/checkout/delivery">بازگشت به روش تحویل</Link>
  </section>;
}
