import { Form, Link } from "react-router";
import type { OrderOutcomeLoaderData, PaymentActionResult } from "./checkout-payment.server.js";
export function OrderOutcomeView({ data, actionData, busy }: { data: OrderOutcomeLoaderData; actionData: PaymentActionResult | null; busy: boolean }) {
  const order=data.order,payment=data.payment,state=outcome(order.payment_status,payment?.status??null);
  const safeOrderRetry=["unpaid","failed","cancelled"].includes(order.payment_status);
  const safePaymentRetry=payment?["failed","cancelled"].includes(payment.status):safeOrderRetry;
  const canRetry=order.order_status==="pending_confirmation"&&safePaymentRetry;
  return <div className="checkout-flow order-outcome"><header className="checkout-flow__intro"><p className="checkout-flow__step">نتیجه سفارش</p><h1>{state.title}</h1><p>{state.message}</p></header>
    {order.customer_type==="wholesale"?<div className="checkout-flow__alert" role="status"><strong>سفارش عمده</strong><span>این برچسب از customer_type ذخیره‌شده در Checkout همین سفارش می‌آید و از وضعیت فعلی حساب یا محاسبه مرورگر حدس زده نمی‌شود.</span></div>:null}
    {actionData?.kind==="data"?<div className="checkout-flow__feedback" role="alert">{actionData.message}{actionData.requestId?<span>شناسه پیگیری: <bdi dir="ltr">{actionData.requestId}</bdi></span>:null}</div>:null}
    <div className="order-outcome__grid"><section className="checkout-flow__card"><h2>سفارش</h2><dl className="payment-state__refs"><div><dt>شماره سفارش</dt><dd><bdi dir="ltr">{order.order_number}</bdi></dd></div><div><dt>وضعیت سفارش</dt><dd><bdi dir="ltr">{order.order_status}</bdi></dd></div><div><dt>وضعیت پرداخت سفارش</dt><dd><bdi dir="ltr">{order.payment_status}</bdi></dd></div><div><dt>مبلغ نهایی</dt><dd>{new Intl.NumberFormat("fa-IR").format(order.grand_total_toman)} تومان</dd></div></dl></section>
    <section className="checkout-flow__card"><h2>پرداخت ثبت‌شده</h2>{payment?<dl className="payment-state__refs"><div><dt>شناسه پرداخت</dt><dd><bdi dir="ltr">{payment.payment_id}</bdi></dd></div><div><dt>وضعیت</dt><dd><bdi dir="ltr">{payment.status}</bdi></dd></div><div><dt>مرجع درگاه</dt><dd>{payment.provider_reference?<bdi dir="ltr">{payment.provider_reference}</bdi>:"—"}</dd></div></dl>:<p>شناسه پرداخت قابل اتکا در handoff موجود نیست؛ وضعیت سفارش authoritative باقی می‌ماند.</p>}</section></div>
    <div className="checkout-flow__actions"><Link to={"/account/orders/" + encodeURIComponent(order.order_number)}>مشاهده جزئیات سفارش</Link>{payment?<Link to={"/payment/return?payment_id=" + encodeURIComponent(payment.payment_id)}>بررسی همان پرداخت</Link>:null}{canRetry?<Form method="post"><input type="hidden" name="intent" value="retry-payment"/><button type="submit" disabled={busy}>تلاش کنترل‌شده برای پرداخت</button></Form>:null}</div>
    {(payment?.reconciliation_required||payment?.manual_review_required)?<div className="checkout-flow__alert" role="status">این پرداخت نیازمند reconciliation یا بررسی دستی است؛ نتیجه ساختگی نمایش داده نمی‌شود.</div>:null}{busy?<p role="status" aria-live="polite">در حال بررسی وضعیت قبلی پیش از هر تلاش تازه…</p>:null}</div>;
}
function outcome(orderPayment:string,payment:string|null){if(orderPayment==="paid"||payment==="paid"||payment==="late_received")return{title:"سفارش ثبت و پرداخت تأیید شد",message:"نتیجه authoritative سفارش و پرداخت ثبت شده است."};if(payment==="refund_required"||payment==="refunded"||orderPayment==="refunded"||orderPayment==="partially_refunded")return{title:"سفارش نیازمند پیگیری بازپرداخت است",message:"پرداخت موفق فرض نمی‌شود؛ وضعیت بازپرداخت و سفارش را از مسیر جزئیات دنبال کنید."};if(orderPayment==="failed"||orderPayment==="cancelled"||payment==="failed"||payment==="cancelled")return{title:"پرداخت تأیید نشد",message:"سفارش حفظ شده است؛ تلاش تازه فقط پس از وضعیت terminal پرداخت قبلی مجاز است."};return{title:"نتیجه سفارش هنوز قطعی نیست",message:"تا تعیین authoritative وضعیت پرداخت، موفقیت یا شکست نمایش داده نمی‌شود."};}
