import { Form, Link } from "react-router";
import type { PaymentActionResult, PaymentReturnLoaderData } from "./checkout-payment.server.js";
export function PaymentReturnView({ data, actionData, busy }: { data: PaymentReturnLoaderData; actionData: PaymentActionResult | null; busy: boolean }) {
  const currentStatus = actionData?.kind === "data" && actionData.status ? actionData.status : data.status.status, state = copy(currentStatus);
  return <div className="checkout-flow payment-return"><header className="checkout-flow__intro"><p className="checkout-flow__step">بررسی پرداخت</p><h1>بررسی نتیجه پرداخت</h1><p>بازگشت از درگاه به‌تنهایی نتیجه پرداخت نیست؛ وضعیت فقط از سرویس authoritative تعیین می‌شود.</p></header>
    {data.callbackHint === "unconfirmed" ? <div className="checkout-flow__alert" role="alert">پردازش callback قطعی نشد؛ نتیجه از status/verify بررسی می‌شود و پرداخت تازه ساخته نمی‌شود.</div> : null}
    {actionData?.kind === "data" ? <div className="checkout-flow__feedback" role="status">{actionData.message}{actionData.requestId ? <span>شناسه پیگیری: <bdi dir="ltr">{actionData.requestId}</bdi></span> : null}</div> : null}
    <section className="checkout-flow__card payment-state" data-payment-state={currentStatus} aria-live="polite"><h2>{state.title}</h2><p>{state.message}</p>
      <dl className="payment-state__refs"><div><dt>شماره سفارش</dt><dd><bdi dir="ltr">{data.handoff.orderNumber}</bdi></dd></div><div><dt>شناسه پرداخت</dt><dd><bdi dir="ltr">{data.handoff.paymentId}</bdi></dd></div><div><dt>وضعیت</dt><dd><bdi dir="ltr">{currentStatus}</bdi></dd></div></dl>
      <div className="checkout-flow__actions"><Form method="post"><input type="hidden" name="intent" value="refresh-status"/><button type="submit" disabled={busy}>استعلام وضعیت</button></Form><Form method="post"><input type="hidden" name="intent" value="verify-payment"/><button type="submit" disabled={busy}>تأیید با درگاه</button></Form><Link to={"/order/" + encodeURIComponent(data.handoff.orderNumber) + "/outcome"}>نتیجه سفارش</Link></div>
    </section><p className="checkout-review__payment-note">در وضعیت pending یا unknown، ایجاد پرداخت جدید مجاز نیست تا نتیجه پرداخت فعلی authoritative شود.</p>{busy ? <p role="status" aria-live="polite">در حال بررسی امن وضعیت پرداخت…</p> : null}</div>;
}
function copy(status:string){if(status==="paid"||status==="late_received")return{title:"پرداخت تأیید شد",message:"وضعیت authoritative پرداخت موفق است؛ نتیجه سفارش را بررسی کنید."};if(status==="failed"||status==="cancelled")return{title:"پرداخت تأیید نشد",message:"پرداخت قبلی terminal است؛ در نتیجه سفارش می‌توانید مسیر تلاش کنترل‌شده را ببینید."};if(status==="refund_required"||status==="refunded")return{title:"پرداخت نیازمند پیگیری بازپرداخت است",message:"موفقیت سفارش فرض نمی‌شود و نتیجه authoritative باید از سفارش/پشتیبانی دنبال شود."};if(status==="unknown")return{title:"نتیجه پرداخت هنوز مشخص نیست",message:"موفقیت یا شکست اعلام نمی‌شود؛ استعلام و verify همان پرداخت امن است."};return{title:"در حال بررسی نتیجه پرداخت",message:"پرداخت هنوز در وضعیت initiating/pending است و پرداخت تازه ساخته نمی‌شود."};}
