import {MediaPatterns} from './MediaPatterns.jsx';
import {useRef,useState} from 'react';
import {House,ShoppingCart,Tag,Stack,Users,ChartBar,ShieldCheck,List,X} from '@phosphor-icons/react';
import coverage from './coverage.json';
import './surface.css';
const groups={overview:['نمای کلی',House],orders:['فروش و سفارش',ShoppingCart],catalog:['کالا و قیمت',Tag],inventory:['موجودی و تأمین',Stack],customers:['مشتریان',Users],finance:['مالی و گزارش‌ها',ChartBar],settings:['تنظیمات و کنترل',ShieldCheck],security:['امنیت و عملیات',ShieldCheck]};
function groupOf(s){const [_,g,n]=s.id.split('-'),v=Number(n);return g==='B'?'overview':g==='C'||(g==='D'&&v<=5)?'catalog':g==='D'?'inventory':g==='E'?'orders':g==='F'?'customers':v<=11?'finance':v<=18?'settings':'security';}
export function AdminSurface(){
 const requested=new URLSearchParams(location.search).get('id'),initial=coverage.screens.find(s=>s.id===requested&&s.area==='admin')||coverage.screens.find(s=>s.id==='AD-B-03');
 const [screen,setScreen]=useState(initial),[viewId,setViewId]=useState(initial.views[0].id),[menu,setMenu]=useState(false),[values,setValues]=useState({}),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState('');
 const dialog=useRef(null),cancel=useRef(null),head=useRef(null),err=useRef(null);
 const view=screen.views.find(v=>v.id===viewId)||screen.views[0],group=groupOf(screen),mapped=screen.operationViews.filter(o=>o.view===view.id),unavailable=view.kind==='unavailable'||mapped.some(o=>screen.blockedOperations.includes(o.operation)||o.executionAuthority?.startsWith('NO_ACTION'));
 const fields=(view.items||[]).slice(0,view.fieldCount||0),rest=(view.items||[]).slice(fields.length),form=fields.length>0;
 function change(s){setScreen(s);setViewId(s.views[0].id);setValues({});setNotice('');setError('');setQuery('');setMenu(false);requestAnimationFrame(()=>head.current?.focus());}
 function choose(id){setViewId(id);setValues({});setNotice('');setError('');requestAnimationFrame(()=>head.current?.focus());}
 function review(e){e?.preventDefault();if(unavailable)return;if(fields.some((f,i)=>!f.includes('اختیاری')&&!values[i]?.trim())){setError('فیلدهای نمایش‌داده‌شده را برای مرور نمونه تکمیل کنید.');requestAnimationFrame(()=>err.current?.focus());return;}if(fields.some((f,i)=>f.includes('تومان')&&values[i]&&!/^-?\d+$/.test(values[i].replace(/[۰-۹٠-٩]/g,c=>String(c.charCodeAt(0)-(c>='۰'?1776:1632)))))){setError('مبلغ تومان باید عدد صحیح باشد.');requestAnimationFrame(()=>err.current?.focus());return;}setError('');dialog.current.showModal();cancel.current.focus();}
 return <div className="admin-surface" dir="rtl"><a className="skip" href="#surface-main">رفتن به محتوای اصلی</a><aside className={'surface-sidebar '+(menu?'open':'')}><a className="surface-brand" href="/review">EQCOFE <small>مدیریت · نمونهٔ طراحی</small></a><nav aria-label="بخش‌های مدیریت">{Object.entries(groups).map(([key,[label,Icon]])=><div key={key}><button className={key===group?'active':''} onClick={()=>change(coverage.screens.find(s=>s.area==='admin'&&groupOf(s)===key))}><Icon size={24}/>{label}</button>{key===group&&<div className="surface-destinations">{coverage.screens.filter(s=>s.area==='admin'&&groupOf(s)===key).map(s=><button key={s.id} aria-current={s.id===screen.id?'page':undefined} onClick={()=>change(s)}>{s.title}</button>)}</div>}</div>)}</nav></aside><div className="surface-workspace"><header className="surface-header"><button className="surface-menu" aria-label="منوی مدیریت" aria-expanded={menu} onClick={()=>setMenu(!menu)}><List size={24}/></button><a href="/review">بازگشت به مرکز بازبینی</a><span>داده‌ها و اقدام‌ها آزمایشی‌اند</span></header><main id="surface-main" className="surface-main"><p className="breadcrumb">مدیریت / {groups[group][0]} / {screen.title}</p><h1 ref={head} tabIndex={-1}>{screen.title}</h1><label className="surface-view-select">نمای کار<select value={view.id} onChange={e=>choose(e.target.value)}>{screen.views.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label><div role="status">{notice}</div>{error&&<p className="flow-error" ref={err} tabIndex={-1} role="alert">{error}</p>}<section className={'surface-body kind-'+view.kind} aria-label={view.title}><div className="surface-body-heading"><h2>{view.title}</h2><span className="sample">نمونهٔ طراحی</span></div>
 {unavailable?<div className="surface-unavailable"><ShieldCheck size={40}/><h3>این اقدام در دسترس نیست</h3><p>پیش‌نیازهای اجرایی این اقدام هنوز تأیید نشده‌اند. امکان ثبت یا دور زدن محدودیت وجود ندارد.</p><button disabled>{view.action||'ادامه'}</button></div>:['media','tree','reorder','upload'].includes(view.kind)?<MediaPatterns key={screen.id+view.id} kind={view.kind}/>:form?<form onSubmit={review} noValidate><div className="surface-form-grid">{fields.map((f,i)=><label key={i}>{f}<input value={values[i]||''} onChange={e=>setValues({...values,[i]:e.target.value})} maxLength={500} autoComplete="off"/></label>)}</div>{rest.length>0&&<ul className="surface-notes">{rest.map((t,i)=><li key={i}>{t}</li>)}</ul>}<button className="primary">مرور اطلاعات نمونه</button></form>:view.kind==='table'||view.kind==='list'?<><label className="surface-search">جست‌وجو در همین نمونه<input value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="surface-table-wrap" tabIndex={0} role="region" aria-label="جدول نمونه"><table><thead><tr>{(view.items||[]).map((t,i)=><th key={i}>{t}</th>)}</tr></thead><tbody>{!query||'نمونهٔ نمایشی'.includes(query)?<tr>{(view.items||[]).map((t,i)=><td key={i}>{view.exampleRow?.[i]||(i===0?'نمونهٔ نمایشی':'ارائه نشده')}</td>)}</tr>:<tr><td colSpan={view.items.length}>موردی با این عبارت در نمونه نیست.</td></tr>}</tbody></table></div>{view.note&&<p className="surface-notes">{view.note}</p>}<button onClick={()=>setNotice('نمای نمونه بازخوانی شد؛ هیچ درخواست واقعی ارسال نشد.')}>بازخوانی نمونه</button></>:view.kind==='error'||view.kind==='empty'?<div className="surface-recovery"><h3>{view.kind==='empty'?'اطلاعاتی برای نمایش نیست':'برای ادامه، وضعیت را بررسی کنید'}</h3><ul>{rest.map((t,i)=><li key={i}>{t}</li>)}</ul><button onClick={()=>choose(screen.views[0].id)}>بازگشت به بررسی</button></div>:view.kind==='navigation'||view.kind==='search'?<div className="surface-task-grid">{coverage.screens.filter(s=>s.area==='admin').map(s=><button key={s.id} onClick={()=>change(s)}>{s.title}</button>)}</div>:<><div className="surface-info-grid">{rest.map((t,i)=><article key={i}><span className="surface-index">{(i+1).toLocaleString('fa-IR')}</span><p>{t}</p></article>)}</div>{view.kind==='dialog'||view.kind==='review'?<button className="primary" onClick={review}>مرور اقدام نمونه</button>:<button onClick={()=>{const next=screen.views.find(v=>v.id!==view.id&&v.kind!=='unavailable');if(next)choose(next.id);else setNotice('نمای دیگری در این نمونه موجود نیست.');}}>{view.action||'ادامهٔ بررسی'}</button>}</>}
 </section></main></div><dialog ref={dialog} aria-labelledby="surface-dialog-title"><h2 id="surface-dialog-title">مرور {view.title}</h2><p>هدف: {screen.title}</p><p>این مرور مجوز اجرا ایجاد نمی‌کند و هیچ درخواست واقعی ارسال نخواهد شد.</p>{Object.values(values).map((v,i)=><p key={i} className="preserve-lines">{fields[i]}: {v}</p>)}<div className="dialog-actions"><button ref={cancel} onClick={()=>dialog.current.close()}>انصراف</button><button onClick={()=>{dialog.current.close();setNotice('مرور نمونه پایان یافت؛ تغییری در سامانه اعمال نشد.');}}>پایان مرور آزمایشی</button></div></dialog></div>;
}
