import {useState,useRef,useEffect} from 'react';
export function CustomerProfile(){
 const [name,setName]=useState('مشتری نمونه'),[phone,setPhone]=useState(''),[otp,setOtp]=useState(''),[phase,setPhase]=useState('edit'),[error,setError]=useState('');const head=useRef(null),errors=useRef(null);
 useEffect(()=>head.current?.focus(),[phase]);
 const normalize=s=>s.replace(/[۰-۹٠-٩]/g,c=>String(c.charCodeAt(0)-(c>='۰'?1776:1632)));
 function fail(t){setError(t);requestAnimationFrame(()=>errors.current?.focus());}
 function review(e){e.preventDefault();if(!name.trim())return fail('نام نمایشی را وارد کنید.');if(phone&&!/^09\d{9}$/.test(phone))return fail('شمارهٔ نمونه باید ۱۱ رقم و با 09 شروع شود.');setError('');setPhase(phone?'step-up':'review');}
 return <section className='store-task'><h2 ref={head} tabIndex={-1}>پروفایل و امنیت حساب</h2><p>نشست نمایشی فعال · شمارهٔ فعلی: <b dir='ltr'>09•••••••89</b></p><p>این فرم به حساب واقعی متصل نیست. تغییر شماره به تأیید دوباره نیاز دارد.</p>{error&&<p id='profile-error' ref={errors} tabIndex={-1} role='alert' className='flow-error'>{error}</p>}{phase==='edit'?<form className='customer-form' onSubmit={review} noValidate><label>نام نمایشی<input value={name} onChange={e=>setName(e.target.value)} maxLength={120} aria-describedby={error?'profile-error':undefined}/></label><label>شمارهٔ تازهٔ نمونه — اختیاری<input value={phone} onChange={e=>setPhone(normalize(e.target.value))} inputMode='tel' dir='ltr' maxLength={11} aria-describedby='phone-help'/></label><p id='phone-help'>برای حفظ شمارهٔ فعلی، این فیلد را خالی بگذارید. فقط دادهٔ ساختگی وارد کنید.</p><button className='primary'>مرور تغییرات</button></form>:phase==='step-up'?<form className='customer-form' onSubmit={e=>{e.preventDefault();if(otp!=='123456')return fail('کد آزمایشی 123456 را وارد کنید؛ شماره هنوز تغییر نکرده است.');setError('');setPhase('review');}}><h3>تأیید دوبارهٔ شماره</h3><p>پیامکی ارسال نمی‌شود؛ کد نمونه 123456 است. پیش از این مرحله تغییری ثبت نمی‌شود.</p><label>کد تأیید نمونه<input value={otp} onChange={e=>setOtp(normalize(e.target.value))} inputMode='numeric' dir='ltr' maxLength={6} aria-describedby={error?'profile-error':undefined}/></label><button type='button' onClick={()=>{setPhase('edit');setError('');setOtp('');}}>انصراف و اصلاح</button><button className='primary'>تأیید آزمایشی</button></form>:phase==='review'?<><h3>بازبینی تغییرات</h3><p>نام نمایشی: {name}</p><p>شماره: {phone?'شمارهٔ تازه در نمونه تأیید شد':'بدون تغییر'}</p><button onClick={()=>setPhase('edit')}>اصلاح اطلاعات</button><button className='primary' onClick={()=>setPhase('done')}>ثبت در نمونه</button></>:<><p role='status'>تغییرات فقط در نمونه ثبت شدند؛ حساب واقعی تغییر نکرده است.</p><button onClick={()=>setPhase('edit')}>بازگشت به پروفایل</button></>}</section>;
}
