import {useState,useRef,useEffect} from 'react';
import './flows.css';
const journeys=[['checkout','خرید و پرداخت','ورود، سبد، نشانی و بازیابی پرداخت','SJ-03 / SJ-04 / SJ-05'],['return','مرجوعی سفارش','ثبت و پیگیری درخواست مرجوعی','SJ-08'],['warranty','درخواست گارانتی','شرح مشکل و پیگیری درخواست','SJ-09'],['wholesale','همکاری عمده','ثبت درخواست و بررسی وضعیت','SJ-10']];
const money=n=>n.toLocaleString('fa-IR')+' تومان';
export function Flows({initialFlow=new URLSearchParams(location.search).get('flow')||'',initialStep='cart',initialQuantity=1,initialUnit=4890000,initialChangedUnit=5050000,minimumOrder=0,contextLabel='خرید نمونه'}={}){
 const [flow,setFlow]=useState(journeys.some(j=>j[0]===initialFlow)?initialFlow:''),[step,setStep]=useState(initialStep),[mobile,setMobile]=useState(''),[otp,setOtp]=useState(''),[quantity,setQuantity]=useState(initialQuantity),[address,setAddress]=useState(['delivery','review','payment','outcome'].includes(initialStep)?'نشانی ساختگی نمونه برای مرور طرح':''),[delivery,setDelivery]=useState(['review','payment','outcome'].includes(initialStep)?'standard':''),[error,setError]=useState(''),[changed,setChanged]=useState(false),[accepted,setAccepted]=useState(false),[payment,setPayment]=useState('unknown'),[detail,setDetail]=useState(''),[company,setCompany]=useState(''),[caseState,setCaseState]=useState('draft');
 const heading=useRef(null),errors=useRef(null);
 useEffect(()=>{heading.current?.focus();},[flow,caseState]);
 const unit=changed?initialChangedUnit:initialUnit;
 function go(next){setError('');setStep(next);requestAnimationFrame(()=>heading.current?.focus());}
 function fail(message){setError(message);requestAnimationFrame(()=>errors.current?.focus());}
 function start(value){setFlow(value);setCaseState('draft');setDetail('');setCompany('');setError('');setMobile('');setOtp('');setQuantity(initialQuantity);setAddress('');setDelivery('');setChanged(false);setAccepted(false);setPayment('unknown');go('cart');}
 function submit(e){e.preventDefault();if(flow==='checkout'){
  if(step==='phone'){if(!/^09\d{9}$/.test(mobile))return fail('شمارهٔ همراه را با ۱۱ رقم و شروع 09 وارد کنید.');go('otp');}
  else if(step==='otp'){if(otp!=='123456')return fail('کد آزمایشی درست نیست. برای این نمونه 123456 را وارد کنید.');go('merge');}
  else if(step==='address'){if(address.trim().length<10)return fail('نشانی کامل تحویل را وارد کنید.');go('delivery');}
  else if(step==='delivery'){if(!delivery)return fail('یک روش ارسال انتخاب کنید.');go('review');}
 }else{if(!detail.trim())return fail(flow==='wholesale'?'زمینهٔ فعالیت و نیاز خرید را بنویسید.':'شرح درخواست را وارد کنید.');if(flow==='wholesale'&&!company.trim())return fail('نام کسب‌وکار را وارد کنید.');setCaseState('review');setError('');}}
 const title=flow==='checkout'?({cart:'سبد خرید',phone:'ورود برای ادامهٔ خرید',otp:'تأیید شمارهٔ همراه',merge:'بازبینی ادغام سبدها',address:'نشانی تحویل',delivery:'روش ارسال',review:'بازبینی سفارش',payment:'پیگیری پرداخت',outcome:'نتیجهٔ آزمایشی سفارش'})[step]:journeys.find(j=>j[0]===flow)?.[1];
 return <div className="store-prototype" dir="rtl"><a className='skip' href='#flow-main'>رفتن به محتوای اصلی</a><header className="store-header"><a href="/flows" className="store-brand">EQCOFE</a><span>تجهیزات قهوه</span><a href="/review">مرکز بازبینی</a></header><div className="sample-strip">نمونهٔ تعاملی طراحی · بدون حساب، سفارش، پرداخت یا درخواست واقعی</div><main className="store-main" id="flow-main">
 {!flow?<><p className="eyebrow">مسیرهای تجربهٔ مشتری</p><h1 ref={heading} tabIndex={-1}>از انتخاب تا پیگیری</h1><p className="lead">یک مسیر را انتخاب کنید و مراحل آن را در نمونه تجربه کنید.</p><div className="journey-cards">{journeys.map(([key,label,desc,id])=><button key={key} onClick={()=>start(key)}><span className="journey-id">{id}</span><h2>{label}</h2><p>{desc}</p><span className="link-label">شروع مسیر</span></button>)}</div></>:<><button className="back-link" onClick={()=>{setFlow('');setError('');}}>بازگشت به مسیرها</button><h1 ref={heading} tabIndex={-1}>{title}</h1>{error&&<div id='flow-error' className="flow-error" ref={errors} tabIndex={-1} role="alert">{error}</div>}
 {flow==='checkout'?<div className="checkout-grid"><section className="flow-card">
 {step==='cart'&&<><div className="line-item"><div><span className="eyebrow">کالای نمونه</span><h2>آسیاب دستی حرفه‌ای مدل E-Q40</h2><p>مدل استیل · موجودی نمونه: ۸ عدد</p><strong>{money(unit)}</strong></div><label>تعداد<select value={quantity} onChange={e=>setQuantity(Number(e.target.value))}>{Array.from({length:8},(_,i)=><option key={i} value={i+1}>{(i+1).toLocaleString('fa-IR')}</option>)}</select></label></div>{unit*quantity<minimumOrder&&<p role='alert'>تعداد برای حداقل مبلغ کالاهای این نمونه کافی نیست.</p>}<button className="primary" disabled={unit*quantity<minimumOrder} onClick={()=>go('phone')}>ادامهٔ خرید</button></>}
 {step==='phone'&&<form onSubmit={submit} noValidate><p>برای ادامه، شمارهٔ همراه خود را وارد کنید. پیامکی ارسال نمی‌شود.</p><label>شمارهٔ همراه<input aria-describedby={error?'flow-error':undefined} aria-invalid={!!error} inputMode="tel" dir="ltr" value={mobile} onChange={e=>setMobile(e.target.value.replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))))} placeholder="09123456789" autoComplete="off"/></label><button className="primary">دریافت کد آزمایشی</button></form>}
 {step==='otp'&&<form onSubmit={submit} noValidate><p>کد این نمونه <b dir="ltr">123456</b> است؛ شماره‌ای تأیید یا حسابی ایجاد نمی‌شود.</p><label>کد تأیید<input aria-describedby={error?'flow-error':undefined} aria-invalid={!!error} dir="ltr" inputMode="numeric" value={otp} onChange={e=>setOtp(e.target.value.replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))))} maxLength={6}/></label><button className="primary">تأیید آزمایشی و ادامه</button><button type="button" onClick={()=>go('phone')}>تغییر شماره</button></form>}
 {step==='merge'&&<><h2>کالای مشترک در دو سبد</h2><p>سبد مهمان: {quantity.toLocaleString('fa-IR')} عدد؛ سبد حساب نمونه: ۱ عدد.</p><p>برای جلوگیری از افزایش ناخواسته، تعداد را صریحاً انتخاب کنید.</p><button onClick={()=>go('address')}>حفظ تعداد سبد مهمان</button><button disabled={quantity>=8} onClick={()=>{setQuantity(quantity+1);go('address');}}>جمع تعداد دو سبد</button>{quantity>=8&&<p>جمع تعداد از موجودی نمونه بیشتر است.</p>}</>}
 {step==='address'&&<form onSubmit={submit} noValidate><label>نشانی کامل تحویل<textarea aria-describedby={error?'flow-error':undefined} aria-invalid={!!error} value={address} onChange={e=>setAddress(e.target.value)} maxLength={500}/></label><p>از اطلاعات ساختگی استفاده کنید؛ نشانی فقط در حافظهٔ همین نمونه است.</p><button className="primary">انتخاب نشانی و ادامه</button></form>}
 {step==='delivery'&&<form onSubmit={submit}><fieldset><legend>ارسال به نشانی انتخاب‌شده</legend><label className="radio-option"><input type="radio" name="shipping" checked={delivery==='standard'} onChange={()=>setDelivery('standard')}/>ارسال استاندارد نمونه — {money(60000)}</label><label className="radio-option"><input type="radio" disabled/>ارسال فوری — برای این نشانی در دسترس نیست</label></fieldset><button className="primary">بازبینی سفارش</button></form>}
 {step==='review'&&<><h2>پیش از ادامه بررسی کنید</h2><p>{address}</p><p>ارسال استاندارد · {money(60000)}</p>{changed&&<div className="flow-warning"><h3>قیمت به‌روز شده است</h3><p>قیمت هر واحد از {money(initialUnit)} به {money(initialChangedUnit)} تغییر کرده است.</p><label className="radio-option"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>قیمت تازه را بررسی کردم</label></div>}<button className="primary" disabled={(changed&&!accepted)||unit*quantity<minimumOrder} onClick={()=>go('payment')}>ادامه به پرداخت آزمایشی</button><details className="test-controls"><summary>سناریوی بررسی طرح</summary><button onClick={()=>{setChanged(true);setAccepted(false);}}>شبیه‌سازی تغییر قیمت</button><button onClick={()=>{go('delivery');fail('اعتبار روش ارسال پایان یافت؛ دوباره آن را بررسی کنید.');}}>شبیه‌سازی پایان اعتبار</button></details></>}
 {step==='payment'&&<><h2>{payment==='unknown'?'نتیجه هنوز مشخص نیست':payment==='failed'?'پرداخت نمونه ناموفق بود':'پرداخت نمونه تأیید شد'}</h2><p>بازگشت از درگاه به‌تنهایی اثبات پرداخت نیست. در این نمونه هیچ اتصال بانکی وجود ندارد.</p>{payment==='unknown'?<><p role="status">تا روشن‌شدن نتیجه، پرداخت دیگری آغاز نکنید.</p><button onClick={()=>setPayment('paid')}>بررسی وضعیت — پاسخ موفق نمونه</button><button onClick={()=>setPayment('failed')}>بررسی وضعیت — پاسخ ناموفق نمونه</button></>:payment==='paid'?<button className="primary" onClick={()=>go('outcome')}>مشاهده نتیجه</button>:<button onClick={()=>setPayment('unknown')}>تلاش مجدد آزمایشی پس از نتیجهٔ قطعی</button>}</>}
 {step==='outcome'&&<><span className="success-tag">فقط شبیه‌سازی</span><h2>مسیر خرید نمونه پایان یافت</h2><p>هیچ سفارش یا پرداخت واقعی ثبت نشده است. اطلاعات با بازخوانی صفحه پاک می‌شوند.</p><button onClick={()=>start('checkout')}>شروع دوباره</button></>}
 </section><aside className="order-summary"><h2>خلاصهٔ سبد</h2><p>{contextLabel}</p><p>آسیاب دستی حرفه‌ای</p><dl><div><dt>تعداد</dt><dd>{quantity.toLocaleString('fa-IR')}</dd></div><div><dt>کالاها</dt><dd>{money(unit*quantity)}</dd></div><div><dt>ارسال نمونه</dt><dd>{delivery?money(60000):'پس از انتخاب ارسال'}</dd></div><div className="total"><dt>جمع</dt><dd>{money(unit*quantity+(delivery?60000:0))}</dd></div></dl><small>تمام مبلغ‌ها تومان صحیح و آزمایشی‌اند.</small></aside></div>:
 <section className="flow-card case-card">{caseState==='draft'?<form onSubmit={submit} noValidate>{flow!=='wholesale'?<><span className="eyebrow">سفارش نمونه EQ-1001</span><h2>آسیاب دستی حرفه‌ای</h2><p>واجد شرایط بودن در سامانهٔ واقعی باید بررسی شود؛ این سناریو فرض آزمایشی واجد شرایط بودن دارد.</p></>:<><h2>معرفی کسب‌وکار</h2><label>نام کسب‌وکار<input value={company} onChange={e=>setCompany(e.target.value)} maxLength={120}/></label></>}<label>{flow==='wholesale'?'زمینهٔ فعالیت و نیاز خرید':'شرح درخواست'}<textarea value={detail} onChange={e=>setDetail(e.target.value)} maxLength={1000}/></label><button className="primary">بازبینی درخواست</button><details className="test-controls"><summary>سناریوی بررسی طرح</summary><button type="button" onClick={()=>setCaseState('ineligible')}>نمایش حالت عدم احراز شرایط</button></details></form>:caseState==='review'?<><h2>بازبینی پیش از ثبت آزمایشی</h2>{company&&<p>{company}</p>}<p className="preserve-lines">{detail}</p><p>ثبت درخواست به معنی پذیرش {flow==='wholesale'?'عضویت عمده':flow==='return'?'مرجوعی':'گارانتی'} نیست.</p><button onClick={()=>setCaseState('draft')}>اصلاح اطلاعات</button><button className="primary" onClick={()=>setCaseState('submitted')}>ثبت آزمایشی برای بررسی</button></>:caseState==='ineligible'?<><h2>امکان ثبت این درخواست وجود ندارد</h2><p>شرایط این سناریوی نمونه احراز نشده است. اقدامی ثبت نشد.</p><button onClick={()=>setCaseState('draft')}>بازگشت به اطلاعات درخواست</button></>:<><span className="success-tag">{caseState==='cancelled'?'لغوشده — نمونه':'در انتظار بررسی — نمونه'}</span><h2>درخواست آزمایشی دریافت شد</h2><ol className="timeline"><li>ثبت درخواست نمونه</li><li>{caseState==='cancelled'?'لغو درخواست نمونه':'در انتظار بررسی'}</li></ol><p>هیچ تأیید، بازپرداخت یا دسترسی عمده‌ای ایجاد نشده است.</p><button onClick={()=>setError('وضعیت نمونه بازخوانی شد؛ نتیجه تغییری نکرده است.')}>بازخوانی وضعیت نمونه</button>{flow==='return'&&caseState!=='cancelled'&&<button onClick={()=>setCaseState('cancel-review')}>بررسی لغو درخواست</button>}{caseState==='cancel-review'&&<div className="flow-warning"><p>لغو این درخواست نمونه را تأیید می‌کنید؟</p><button onClick={()=>setCaseState('submitted')}>انصراف از لغو</button><button onClick={()=>setCaseState('cancelled')}>تأیید لغو آزمایشی</button></div>}{caseState==='cancelled'&&<p role="status">درخواست نمونه لغو شد؛ هیچ درخواست واقعی تغییر نکرده است.</p>}</>}</section>}
 </>}
 </main><footer className="store-footer">EQCOFE · نمونهٔ طراحی قدم ۵۷ · فارسی و راست‌به‌چپ</footer></div>;
}
