import React,{lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {App} from './App.jsx';
import './design-tokens.css';
import './styles.css';
const Review=lazy(()=>import('./Review.jsx').then(m=>({default:m.Review})));
const Flows=lazy(()=>import('./Flows.jsx').then(m=>({default:m.Flows})));
const AdminSurface=lazy(()=>import('./AdminSurface.jsx').then(m=>({default:m.AdminSurface})));
const StoreSurface=lazy(()=>import('./StoreSurface.jsx').then(m=>({default:m.StoreSurface})));
document.title='EQCOFE — نمونهٔ طراحی قدم ۵۷';
const route=location.pathname;
createRoot(document.getElementById('root')).render(<React.StrictMode><Suspense fallback={<p role="status" dir="rtl">در حال آماده‌سازی نمونه…</p>}>{route==='/store'?<StoreSurface/>:route==='/admin'?<AdminSurface/>:route==='/review'?<Review/>:route==='/flows'?<Flows/>:<App/>}</Suspense></React.StrictMode>);
