import { Injectable } from '@nestjs/common';
import { TransactionManager } from '../../../platform/database/transaction-manager';
import { RequestContextStore } from '../../../platform/request-context/request-context.store';
import { OutboxWriter } from '../../../platform/outbox/outbox-writer';
import { AuditWriter } from '../../../platform/audit/audit.writer';
import { DomainError } from '../../../shared/errors/domain-error';
import { customerEvent,customerWholesaleEvent } from '../domain/customer.events';
import { CustomerWholesaleApplicationRow,CustomerWholesaleRepository } from '../infrastructure/customer-wholesale.repository';

export interface WholesaleApplicationInput{
  business_name?:unknown;manager_name?:unknown;business_type?:unknown;province_id?:unknown;city_id?:unknown;business_identifier?:unknown;note?:unknown;
}

@Injectable()
export class CustomerWholesaleService{
  constructor(private readonly tx:TransactionManager,private readonly repo:CustomerWholesaleRepository,private readonly ctx:RequestContextStore,private readonly outbox:OutboxWriter,private readonly audit:AuditWriter){}

  private customerId():string{const a=this.ctx.get()?.actor;if(a?.type!=='customer'||!a.id)throw new DomainError('CUSTOMER_REQUIRED','ورود مشتری الزامی است.');return a.id;}
  private staffId():string{const a=this.ctx.get()?.actor;if(a?.type!=='staff'||!a.id)throw new DomainError('STAFF_REQUIRED','دسترسی مدیر الزامی است.');return a.id;}
  private uuid(v:unknown):string{const x=String(v??'').trim();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x))throw new DomainError('VALIDATION_ERROR','شناسه معتبر نیست.');return x;}
  private text(v:unknown,max:number,min=1,nullable=false):string|null{if(v===null||v===undefined){if(nullable)return null;throw new DomainError('VALIDATION_ERROR','اطلاعات درخواست عمده کامل نیست.');}const x=String(v).trim().replace(/\s+/g,' ');if(!x){if(nullable)return null;throw new DomainError('VALIDATION_ERROR','اطلاعات درخواست عمده کامل نیست.');}if(x.length<min||x.length>max)throw new DomainError('VALIDATION_ERROR','طول اطلاعات درخواست عمده معتبر نیست.');return x;}
  private present(r:CustomerWholesaleApplicationRow){return{id:String(r.id),customer_id:String(r.customer_id),business_name:r.business_name,manager_name:r.manager_name,business_type:r.business_type,province_id:String(r.province_id),city_id:String(r.city_id),business_identifier:r.business_identifier??null,note:r.note??null,status:r.status,submitted_at:r.submitted_at,review_started_at:r.review_started_at,reviewed_at:r.reviewed_at,decision_note:r.decision_note??null,rejection_reason:r.rejection_reason??null};}

  async myApplication(){const customerId=this.customerId();const c=await this.repo.customer(customerId);if(!c||c.status!=='active')throw new DomainError('CUSTOMER_INACTIVE','حساب مشتری فعال نیست.');const row=await this.repo.latest(customerId);return row?this.present(row):null;}

  async submit(input:WholesaleApplicationInput){const customerId=this.customerId(),context=this.ctx.require();return this.tx.run(async ex=>{
    const c=await this.repo.customer(customerId,ex,true);if(!c||c.status!=='active')throw new DomainError('CUSTOMER_INACTIVE','حساب مشتری فعال نیست.');if(c.customer_type!=='retail')throw new DomainError('CUSTOMER_ALREADY_WHOLESALE','این مشتری قبلاً عمده تایید شده است.');
    if(await this.repo.active(customerId,ex))throw new DomainError('WHOLESALE_APPLICATION_ACTIVE','درخواست عمده فعال دیگری وجود دارد.');
    const row=await this.repo.create(ex,{customerId,businessName:this.text(input.business_name,250)!,managerName:this.text(input.manager_name,200)!,businessType:this.text(input.business_type,100)!,provinceId:this.uuid(input.province_id),cityId:this.uuid(input.city_id),businessIdentifier:this.text(input.business_identifier,100,1,true),note:this.text(input.note,4000,1,true)});
    await this.outbox.append(ex,[customerWholesaleEvent('customer.wholesale_application.submitted.v1',row.id,Number(row.version),customerId,row.status)],context);
    await this.audit.writeWith(ex,{actorType:'customer',actorId:customerId,action:'customer.wholesale_application.submit',resourceType:'customer_wholesale_application',resourceId:row.id,afterData:{status:row.status,business_name:row.business_name,business_type:row.business_type},requestId:context.requestId,traceId:context.traceId});
    return this.present(row);
  });}

  async listAdmin(statusRaw?:unknown){this.staffId();const status=statusRaw===undefined||statusRaw===null||statusRaw===''?null:String(statusRaw) as any;if(status!==null&&!['submitted','under_review','approved','rejected'].includes(status))throw new DomainError('VALIDATION_ERROR','وضعیت درخواست عمده معتبر نیست.');return{items:(await this.repo.list(status)).map(r=>this.present(r))};}
  async getAdmin(idRaw:string){this.staffId();const row=await this.repo.byId(this.uuid(idRaw));if(!row)throw new DomainError('WHOLESALE_APPLICATION_NOT_FOUND','درخواست عمده پیدا نشد.');return this.present(row);}

  async startReview(idRaw:string,comment?:unknown){const staffId=this.staffId(),id=this.uuid(idRaw),context=this.ctx.require(),reviewNote=this.text(comment,2000,1,true);return this.tx.run(async ex=>{const before=await this.repo.byId(id,ex,true);if(!before)throw new DomainError('WHOLESALE_APPLICATION_NOT_FOUND','درخواست عمده پیدا نشد.');if(before.status!=='submitted')throw new DomainError('WHOLESALE_INVALID_STATE','فقط درخواست ارسال‌شده قابل شروع بررسی است.');const row=await this.repo.startReview(ex,id,Number(before.version),staffId);if(!row)throw new DomainError('VERSION_CONFLICT','درخواست همزمان تغییر کرده است.');await this.outbox.append(ex,[customerWholesaleEvent('customer.wholesale_application.review_started.v1',id,Number(row.version),row.customer_id,row.status)],context);await this.audit.writeWith(ex,{actorType:'staff',actorId:staffId,action:'customer.wholesale_application.start_review',resourceType:'customer_wholesale_application',resourceId:id,beforeData:{status:before.status,version:Number(before.version)},afterData:{status:row.status,version:Number(row.version),reviewer_staff_id:staffId},reason:reviewNote??undefined,requestId:context.requestId,traceId:context.traceId});return this.present(row);});}

  async approve(idRaw:string,comment?:unknown){const staffId=this.staffId(),id=this.uuid(idRaw),context=this.ctx.require(),decisionNote=this.text(comment,2000,1,true);return this.tx.run(async ex=>{const before=await this.repo.byId(id,ex,true);if(!before)throw new DomainError('WHOLESALE_APPLICATION_NOT_FOUND','درخواست عمده پیدا نشد.');if(before.status!=='under_review')throw new DomainError('WHOLESALE_INVALID_STATE','فقط درخواست درحال بررسی قابل تایید است.');const customer=await this.repo.customer(before.customer_id,ex,true);if(!customer||customer.status!=='active'||customer.customer_type!=='retail')throw new DomainError('WHOLESALE_CUSTOMER_NOT_ELIGIBLE','مشتری برای تایید عمده واجد شرایط نیست.');const app=await this.repo.approve(ex,id,Number(before.version),decisionNote);if(!app)throw new DomainError('VERSION_CONFLICT','درخواست همزمان تغییر کرده است.');const promoted=await this.repo.promote(ex,before.customer_id,Number(customer.version));if(!promoted)throw new DomainError('VERSION_CONFLICT','وضعیت مشتری همزمان تغییر کرده است.');await this.outbox.append(ex,[customerWholesaleEvent('customer.wholesale_application.approved.v1',id,Number(app.version),app.customer_id,app.status),customerEvent('customer.type_changed.v1',promoted.id,Number(promoted.version),{customer_id:promoted.id,previous_type:'retail',customer_type:'wholesale'})],context);await this.audit.writeWith(ex,{actorType:'staff',actorId:staffId,action:'customer.wholesale_application.approve',resourceType:'customer_wholesale_application',resourceId:id,beforeData:{status:before.status,version:Number(before.version)},afterData:{status:app.status,version:Number(app.version),customer_type:'wholesale'},reason:decisionNote??undefined,requestId:context.requestId,traceId:context.traceId});await this.audit.writeWith(ex,{actorType:'staff',actorId:staffId,action:'customer.type.change',resourceType:'customer',resourceId:promoted.id,beforeData:{customer_type:'retail',version:Number(customer.version)},afterData:{customer_type:'wholesale',version:Number(promoted.version)},reason:'wholesale_application_approved',requestId:context.requestId,traceId:context.traceId});return this.present(app);});}

  async reject(idRaw:string,reasonRaw:unknown){const staffId=this.staffId(),id=this.uuid(idRaw),reason=this.text(reasonRaw,2000,2,false)!,context=this.ctx.require();return this.tx.run(async ex=>{const before=await this.repo.byId(id,ex,true);if(!before)throw new DomainError('WHOLESALE_APPLICATION_NOT_FOUND','درخواست عمده پیدا نشد.');if(before.status!=='under_review')throw new DomainError('WHOLESALE_INVALID_STATE','فقط درخواست درحال بررسی قابل رد است.');const row=await this.repo.reject(ex,id,Number(before.version),reason);if(!row)throw new DomainError('VERSION_CONFLICT','درخواست همزمان تغییر کرده است.');await this.outbox.append(ex,[customerWholesaleEvent('customer.wholesale_application.rejected.v1',id,Number(row.version),row.customer_id,row.status)],context);await this.audit.writeWith(ex,{actorType:'staff',actorId:staffId,action:'customer.wholesale_application.reject',resourceType:'customer_wholesale_application',resourceId:id,beforeData:{status:before.status,version:Number(before.version)},afterData:{status:row.status,version:Number(row.version)},reason,requestId:context.requestId,traceId:context.traceId});return this.present(row);});}
}
