import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { TransactionManager } from '../../../platform/database/transaction-manager';
import { RequestContextStore } from '../../../platform/request-context/request-context.store';
import { AuditWriter } from '../../../platform/audit/audit.writer';
import { OutboxWriter } from '../../../platform/outbox/outbox-writer';
import { DomainError } from '../../../shared/errors/domain-error';
import { contentArticleEvent } from '../domain/content.events';
import { ArticleRow,ArticleStatus,ContentRepository } from '../infrastructure/content.repository';

@Injectable()
export class ArticleEditorialService {
  constructor(private readonly tx:TransactionManager,private readonly repo:ContentRepository,private readonly ctx:RequestContextStore,private readonly audit:AuditWriter,private readonly outbox:OutboxWriter){}
  private staff(){const a=this.ctx.get()?.actor;if(a?.type!=='staff'||!a.id)throw new DomainError('STAFF_REQUIRED','دسترسی کارشناس محتوا الزامی است.');return a.id;}
  private ver(a:ArticleRow){const n=Number(a.version);if(!Number.isSafeInteger(n)||n<1)throw new DomainError('CONTENT_VERSION_INVALID','نسخه مقاله معتبر نیست.');return n;}
  private text(v:unknown,max:number,min=0){const s=String(v??'').trim();if(s.length<min||s.length>max)throw new DomainError('VALIDATION_ERROR','متن ورودی معتبر نیست.');return s;}
  private async mutate(id:string,from:ArticleStatus[],to:ArticleStatus,opts:{reason?:string|null;scheduledAt?:Date|null;publish?:boolean;archive?:boolean;action:string;event:string}){
    const staff=this.staff(),c=this.ctx.require();return this.tx.run(async ex=>{const before=await this.repo.byId(id,ex,true);if(!before)throw new DomainError('CONTENT_ARTICLE_NOT_FOUND','مقاله پیدا نشد.');if(before.status===to)return before;if(!from.includes(before.status))throw new DomainError('CONTENT_INVALID_STATE','وضعیت فعلی مقاله برای این عملیات مجاز نیست.');const current=await this.repo.currentVersion(before,ex);if(!current)throw new DomainError('CONTENT_ARTICLE_VERSION_MISSING','نسخه فعلی مقاله پیدا نشد.');if(['in_review','approved','scheduled','published'].includes(to)&&(!current.body||!current.title_fa||!current.slug))throw new DomainError('CONTENT_ARTICLE_INCOMPLETE','مقاله برای ادامه چرخه انتشار کامل نیست.');if(opts.publish){const owner=await this.repo.bySlug(current.slug,ex);if(owner&&owner.id!==id)throw new DomainError('CONTENT_SLUG_CONFLICT','اسلاگ نسخه قابل انتشار با مقاله دیگری تداخل دارد.');}
      const row=await this.repo.transition(ex,{articleId:id,expectedAggregateVersion:this.ver(before),from,to,staffId:staff,scheduledAt:opts.scheduledAt,reason:opts.reason,publish:opts.publish,archive:opts.archive});if(!row)throw new DomainError('VERSION_CONFLICT','مقاله همزمان تغییر کرده است.');await this.repo.addTransition(ex,{id:randomUUID(),articleId:id,fromStatus:before.status,toStatus:to,articleVersionId:current.id,staffId:staff,reason:opts.reason,scheduledAt:opts.scheduledAt});await this.audit.writeWith(ex,{actorType:'staff',actorId:staff,action:opts.action,resourceType:'content_article',resourceId:id,beforeData:{status:before.status,version:this.ver(before)},afterData:{status:row.status,version:this.ver(row),content_version:current.version_number},reason:opts.reason??undefined,requestId:c.requestId,traceId:c.traceId});await this.outbox.append(ex,[contentArticleEvent(opts.event,id,this.ver(row),{article_id:id,status:row.status,content_version:current.version_number,scheduled_at:opts.scheduledAt?.toISOString()??null})],c);return row;});
  }
  submitReview(id:string,comment?:unknown){return this.mutate(id,['draft','unpublished'],'in_review',{reason:comment==null?null:this.text(comment,2000),action:'content.article.submit_review',event:'content.article.review_submitted.v1'});}
  approve(id:string,comment?:unknown){return this.mutate(id,['in_review'],'approved',{reason:comment==null?null:this.text(comment,2000),action:'content.article.approve',event:'content.article.approved.v1'});}
  schedule(id:string,scheduledAtRaw:unknown){const d=new Date(String(scheduledAtRaw??''));if(!Number.isFinite(d.getTime())||d.getTime()<=Date.now())throw new DomainError('CONTENT_SCHEDULE_INVALID','زمان انتشار باید در آینده باشد.');return this.mutate(id,['approved'],'scheduled',{scheduledAt:d,action:'content.article.schedule',event:'content.article.scheduled.v1'});}
  publish(id:string){return this.mutate(id,['approved','scheduled'],'published',{publish:true,action:'content.article.publish',event:'content.article.published.v1'});}
  unpublish(id:string){return this.mutate(id,['published'],'unpublished',{action:'content.article.unpublish',event:'content.article.unpublished.v1'});}
  archive(id:string,reasonRaw:unknown){const reason=this.text(reasonRaw,1000,2);return this.mutate(id,['draft','in_review','approved','scheduled','published','unpublished'],'archived',{reason,archive:true,action:'content.article.archive',event:'content.article.archived.v1'});}
  async restoreVersion(id:string,versionNumber:number,reasonRaw?:unknown){const staff=this.staff(),c=this.ctx.require(),reason=reasonRaw==null?null:this.text(reasonRaw,1000);if(!Number.isSafeInteger(versionNumber)||versionNumber<1)throw new DomainError('CONTENT_VERSION_INVALID','نسخه مقاله معتبر نیست.');return this.tx.run(async ex=>{const a=await this.repo.byId(id,ex,true);if(!a)throw new DomainError('CONTENT_ARTICLE_NOT_FOUND','مقاله پیدا نشد.');if(['archived','approved','scheduled'].includes(a.status))throw new DomainError('CONTENT_RESTORE_LOCKED','در وضعیت فعلی بازیابی نسخه مجاز نیست.');const source=await this.repo.versionByNumber(id,versionNumber,ex);if(!source)throw new DomainError('CONTENT_ARTICLE_VERSION_NOT_FOUND','نسخه مقاله پیدا نشد.');const next=await this.repo.nextVersionNumber(id,ex);const v=await this.repo.createVersion(ex,{id:randomUUID(),articleId:id,versionNumber:next,titleFa:source.title_fa,slug:source.slug,body:source.body,seoTitle:source.seo_title,metaDescription:source.meta_description,restoredFromVersion:versionNumber,createdBy:staff});const canonical=a.status==='published'?a.slug:v.slug;const updated=await this.repo.setCurrentVersion(ex,{articleId:id,expectedAggregateVersion:this.ver(a),versionId:v.id,canonicalSlug:canonical,staffId:staff});if(!updated)throw new DomainError('VERSION_CONFLICT','مقاله همزمان تغییر کرده است.');await this.audit.writeWith(ex,{actorType:'staff',actorId:staff,action:'content.article.version.restore',resourceType:'content_article',resourceId:id,beforeData:{status:a.status,version:this.ver(a)},afterData:{status:updated.status,version:this.ver(updated),content_version:next,restored_from_version:versionNumber},reason:reason??undefined,requestId:c.requestId,traceId:c.traceId});await this.outbox.append(ex,[contentArticleEvent('content.article.version_restored.v1',id,this.ver(updated),{article_id:id,content_version:next,restored_from_version:versionNumber,status:updated.status})],c);return {article:updated,version:v};});}
}
