import { Inject, Injectable } from '@nestjs/common'; import { Kysely, sql } from 'kysely'; import { randomUUID } from 'node:crypto'; import { DatabaseSchema } from '../../../platform/database/database.types'; import { KYSELY_DB } from '../../../platform/database/database.tokens'; import { DatabaseExecutor } from '../../../platform/database/transaction-manager'; import { ProductAggregate } from '../domain/product.aggregate'; import { VariantAggregate } from '../domain/variant.aggregate'; import { BrandState, CategoryState, ProductState, VariantState } from '../domain/catalog.types'; import { DomainError } from '../../../shared/errors/domain-error';
const n=(x:unknown)=>Number(x); const d=(x:unknown)=>x?new Date(String(x)):null;
@Injectable() export class CatalogRepository { constructor(@Inject(KYSELY_DB) private readonly db:Kysely<DatabaseSchema>){}
 async productById(ex:DatabaseExecutor,id:string,lock=false):Promise<ProductAggregate|null>{const q=sql<any>`SELECT * FROM catalog.products WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`;const r=await q.execute(ex);return r.rows[0]?ProductAggregate.rehydrate(mapProduct(r.rows[0])):null;}
 async saveProduct(ex:DatabaseExecutor,p:ProductAggregate,expectedVersion:number):Promise<void>{const s=p.snapshot();const r=await sql`UPDATE catalog.products SET brand_id=${s.brandId}::uuid,primary_category_id=${s.primaryCategoryId}::uuid,name_fa=${s.nameFa},name_en=${s.nameEn},slug=${s.slug},short_description=${s.shortDescription},description=${s.description},status=${s.status},sales_enabled=${s.salesEnabled},published_at=${s.publishedAt},archived_at=${s.archivedAt},archive_reason=${s.archiveReason},version=${s.version},updated_at=now() WHERE id=${s.id}::uuid AND version=${expectedVersion}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','محصول همزمان تغییر کرده است.');}
 async insertProduct(ex:DatabaseExecutor,p:ProductAggregate){const s=p.snapshot();await sql`INSERT INTO catalog.products(id,brand_id,primary_category_id,name_fa,name_en,slug,short_description,description,status,sales_enabled,version) VALUES(${s.id}::uuid,${s.brandId}::uuid,${s.primaryCategoryId}::uuid,${s.nameFa},${s.nameEn},${s.slug},${s.shortDescription},${s.description},${s.status},${s.salesEnabled},${s.version})`.execute(ex);}
 async variantById(ex:DatabaseExecutor,id:string,lock=false){const r=await sql<any>`SELECT * FROM catalog.product_variants WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]?VariantAggregate.rehydrate(mapVariant(r.rows[0])):null;}
 async insertVariant(ex:DatabaseExecutor,v:VariantAggregate){const s=v.snapshot();await sql`INSERT INTO catalog.product_variants(id,product_id,sku,barcode,name_suffix,status,sales_enabled,weight_grams,version) VALUES(${s.id}::uuid,${s.productId}::uuid,${s.sku},${s.barcode},${s.nameSuffix},${s.status},${s.salesEnabled},${s.weightGrams},${s.version})`.execute(ex);}
 async saveVariant(ex:DatabaseExecutor,v:VariantAggregate,expectedVersion:number){const s=v.snapshot();const r=await sql`UPDATE catalog.product_variants SET sku=${s.sku},barcode=${s.barcode},name_suffix=${s.nameSuffix},status=${s.status},sales_enabled=${s.salesEnabled},weight_grams=${s.weightGrams},version=${s.version},updated_at=now() WHERE id=${s.id}::uuid AND version=${expectedVersion}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','واریانت همزمان تغییر کرده است.');}
 async hasActiveVariant(ex:DatabaseExecutor,productId:string){const r=await sql<any>`SELECT EXISTS(SELECT 1 FROM catalog.product_variants WHERE product_id=${productId}::uuid AND status='active') AS ok`.execute(ex);return !!r.rows[0]?.ok;}
 async listVariants(productId:string){const r=await sql<any>`SELECT v.*, (s.global_sales_enabled AND COALESCE(b.sales_enabled,true) AND c.sales_enabled AND p.sales_enabled AND p.status='published' AND v.status='active' AND v.sales_enabled) effective_sales_enabled FROM catalog.product_variants v JOIN catalog.products p ON p.id=v.product_id JOIN catalog.categories c ON c.id=p.primary_category_id LEFT JOIN catalog.brands b ON b.id=p.brand_id CROSS JOIN catalog.sales_settings s WHERE v.product_id=${productId}::uuid ORDER BY v.created_at,v.id`.execute(this.db);return r.rows.map((x:any)=>({...mapVariant(x),effectiveSalesEnabled:!!x.effective_sales_enabled}));}
 async brandById(ex:DatabaseExecutor,id:string,lock=false):Promise<BrandState|null>{const r=await sql<any>`SELECT * FROM catalog.brands WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]?mapBrand(r.rows[0]):null;}
 async insertBrand(ex:DatabaseExecutor,i:Omit<BrandState,'version'>){await sql`INSERT INTO catalog.brands(id,name_fa,name_en,slug,description,status,sales_enabled) VALUES(${i.id}::uuid,${i.nameFa},${i.nameEn},${i.slug},${i.description},${i.status},${i.salesEnabled})`.execute(ex);}
 async updateBrand(ex:DatabaseExecutor,s:BrandState,expected:number){const r=await sql`UPDATE catalog.brands SET name_fa=${s.nameFa},name_en=${s.nameEn},slug=${s.slug},description=${s.description},status=${s.status},sales_enabled=${s.salesEnabled},version=version+1,updated_at=now() WHERE id=${s.id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','برند همزمان تغییر کرده است.');}
 async categoryById(ex:DatabaseExecutor,id:string,lock=false):Promise<CategoryState|null>{const r=await sql<any>`SELECT * FROM catalog.categories WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]?mapCategory(r.rows[0]):null;}
 async insertCategory(ex:DatabaseExecutor,i:Omit<CategoryState,'version'>){await sql`INSERT INTO catalog.categories(id,parent_id,name_fa,slug,description,status,sales_enabled,sort_order) VALUES(${i.id}::uuid,${i.parentId}::uuid,${i.nameFa},${i.slug},${i.description},${i.status},${i.salesEnabled},${i.sortOrder})`.execute(ex);}
 async updateCategory(ex:DatabaseExecutor,s:CategoryState,expected:number){const r=await sql`UPDATE catalog.categories SET parent_id=${s.parentId}::uuid,name_fa=${s.nameFa},slug=${s.slug},description=${s.description},status=${s.status},sales_enabled=${s.salesEnabled},sort_order=${s.sortOrder},version=version+1,updated_at=now() WHERE id=${s.id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','دسته همزمان تغییر کرده است.');}
 async publicProductBySlug(slug:string){const r=await sql<any>`SELECT p.*,b.name_fa brand_name,b.slug brand_slug,c.name_fa category_name,c.slug category_slug,s.global_sales_enabled,(s.global_sales_enabled AND COALESCE(b.sales_enabled,true) AND c.sales_enabled AND p.sales_enabled AND EXISTS(SELECT 1 FROM catalog.product_variants ev WHERE ev.product_id=p.id AND ev.status='active' AND ev.sales_enabled=true)) effective_sales_enabled FROM catalog.products p JOIN catalog.categories c ON c.id=p.primary_category_id LEFT JOIN catalog.brands b ON b.id=p.brand_id CROSS JOIN catalog.sales_settings s WHERE lower(p.slug)=lower(${slug}) AND p.status='published'`.execute(this.db);return r.rows[0]??null;}
 async adminProductById(id:string){const r=await sql<any>`SELECT p.*,b.name_fa brand_name,c.name_fa category_name FROM catalog.products p JOIN catalog.categories c ON c.id=p.primary_category_id LEFT JOIN catalog.brands b ON b.id=p.brand_id WHERE p.id=${id}::uuid`.execute(this.db);return r.rows[0]??null;}
 async listPublic(opts:{category?:string;brand?:string;limit:number;cursor?:string}){const cursor=opts.cursor?new Date(Buffer.from(opts.cursor,'base64url').toString('utf8')):null;const r=await sql<any>`SELECT p.id,p.slug,p.name_fa,p.short_description,p.created_at,p.version,b.id brand_id,b.name_fa brand_name,b.slug brand_slug,c.id category_id,c.name_fa category_name,c.slug category_slug,(s.global_sales_enabled AND COALESCE(b.sales_enabled,true) AND c.sales_enabled AND p.sales_enabled AND EXISTS(SELECT 1 FROM catalog.product_variants ev WHERE ev.product_id=p.id AND ev.status='active' AND ev.sales_enabled=true)) effective_sales_enabled FROM catalog.products p JOIN catalog.categories c ON c.id=p.primary_category_id LEFT JOIN catalog.brands b ON b.id=p.brand_id CROSS JOIN catalog.sales_settings s WHERE p.status='published' AND (${opts.category??null}::text IS NULL OR lower(c.slug)=lower(${opts.category??null})) AND (${opts.brand??null}::text IS NULL OR lower(b.slug)=lower(${opts.brand??null})) AND (${cursor}::timestamptz IS NULL OR p.created_at < ${cursor}) ORDER BY p.created_at DESC,p.id DESC LIMIT ${opts.limit+1}`.execute(this.db);return paginate(r.rows,opts.limit);}
 async listAdmin(limit:number,cursor?:string){const cur=cursor?new Date(Buffer.from(cursor,'base64url').toString('utf8')):null;const r=await sql<any>`SELECT p.*,b.name_fa brand_name,c.name_fa category_name FROM catalog.products p JOIN catalog.categories c ON c.id=p.primary_category_id LEFT JOIN catalog.brands b ON b.id=p.brand_id WHERE (${cur}::timestamptz IS NULL OR p.created_at<${cur}) ORDER BY p.created_at DESC,p.id DESC LIMIT ${limit+1}`.execute(this.db);return paginate(r.rows,limit);}
 async listBrands(publicOnly:boolean){const r=await sql<any>`SELECT * FROM catalog.brands WHERE (${publicOnly}::boolean=false OR status='active') ORDER BY name_fa`.execute(this.db);return r.rows;}
 async brandBySlug(slug:string){const r=await sql<any>`SELECT * FROM catalog.brands WHERE lower(slug)=lower(${slug}) AND status='active'`.execute(this.db);return r.rows[0]??null;}
 async listCategories(publicOnly:boolean){const r=await sql<any>`SELECT * FROM catalog.categories WHERE (${publicOnly}::boolean=false OR status='active') ORDER BY parent_id NULLS FIRST,sort_order,name_fa`.execute(this.db);return r.rows;}
 async categoryBySlug(slug:string){const r=await sql<any>`SELECT * FROM catalog.categories WHERE lower(slug)=lower(${slug}) AND status='active'`.execute(this.db);return r.rows[0]??null;}
 async compare(productIds:string[]){const r=await sql<any>`SELECT p.id,p.name_fa,p.slug,p.primary_category_id,c.name_fa category_name,jsonb_agg(jsonb_build_object('variant_id',v.id,'sku',v.sku,'name_suffix',v.name_suffix) ORDER BY v.created_at) FILTER (WHERE v.id IS NOT NULL) variants FROM catalog.products p JOIN catalog.categories c ON c.id=p.primary_category_id LEFT JOIN catalog.product_variants v ON v.product_id=p.id AND v.status='active' WHERE p.id IN (${sql.join(productIds.map(id=>sql`${id}::uuid`))}) AND p.status='published' GROUP BY p.id,c.name_fa`.execute(this.db);return r.rows;}
 async createMedia(ex:DatabaseExecutor,i:{id:string;storageKey:string;filename:string;mimeType:string;sizeBytes:number;checksum:string;createdBy?:string}){await sql`INSERT INTO catalog.media_assets(id,storage_key,original_filename,mime_type,size_bytes,checksum_sha256,created_by) VALUES(${i.id}::uuid,${i.storageKey},${i.filename},${i.mimeType},${i.sizeBytes},${i.checksum},${i.createdBy??null}::uuid)`.execute(ex);}
 async mediaById(id:string){const r=await sql<any>`SELECT * FROM catalog.media_assets WHERE id=${id}::uuid`.execute(this.db);return r.rows[0]??null;}
 async completeMedia(ex:DatabaseExecutor,id:string,width:number|null,height:number|null){const r=await sql`UPDATE catalog.media_assets SET width=${width},height=${height},status='processing',version=version+1,updated_at=now() WHERE id=${id}::uuid AND status='uploading'`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('MEDIA_NOT_COMPLETABLE','فایل در وضعیت قابل تکمیل نیست.');}
 async activateMedia(ex:DatabaseExecutor,id:string){const r=await sql`UPDATE catalog.media_assets SET status='active',version=version+1,updated_at=now() WHERE id=${id}::uuid AND status IN ('processing','quarantine')`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('MEDIA_NOT_APPROVABLE','رسانه در وضعیت قابل تأیید نیست.');}
 async deleteMedia(ex:DatabaseExecutor,id:string){const refs=await sql<any>`SELECT count(*)::int c FROM catalog.product_media WHERE media_id=${id}::uuid`.execute(ex);if(n(refs.rows[0]?.c)>0)throw new DomainError('MEDIA_IN_USE','رسانه به محصول متصل است.');const r=await sql`UPDATE catalog.media_assets SET status='deleted',version=version+1,updated_at=now() WHERE id=${id}::uuid AND status<>'deleted'`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('MEDIA_NOT_FOUND','رسانه پیدا نشد.');}


 async getAttribute(id:string){const r=await sql<any>`SELECT * FROM catalog.attributes WHERE id=${id}::uuid`.execute(this.db);return r.rows[0]??null;}
 async attributeById(ex:DatabaseExecutor,id:string,lock=false){const r=await sql<any>`SELECT * FROM catalog.attributes WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]??null;}
 async updateAttribute(ex:DatabaseExecutor,id:string,i:any,expected:number){const r=await sql`UPDATE catalog.attributes SET category_id=${i.categoryId}::uuid,name_fa=${i.nameFa},key=${i.key},data_type=${i.dataType},unit=${i.unit},is_variant_attribute=${i.isVariant},is_filterable=${i.isFilterable},is_comparable=${i.isComparable},sort_order=${i.sortOrder},version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','ویژگی همزمان تغییر کرده است.');}
 async attributeValueById(ex:DatabaseExecutor,id:string,lock=false){const r=await sql<any>`SELECT * FROM catalog.attribute_values WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]??null;}
 async updateAttributeValue(ex:DatabaseExecutor,id:string,i:any,expected:number){const r=await sql`UPDATE catalog.attribute_values SET value_text=${i.valueText},value_numeric=${i.valueNumeric},value_boolean=${i.valueBoolean},normalized_value=${i.normalizedValue},sort_order=${i.sortOrder},version=version+1 WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','مقدار ویژگی همزمان تغییر کرده است.');}
 async setProductAttributes(ex:DatabaseExecutor,productId:string,items:any[]){const p=await sql<any>`SELECT primary_category_id FROM catalog.products WHERE id=${productId}::uuid FOR UPDATE`.execute(ex);if(!p.rows[0])throw new DomainError('PRODUCT_NOT_FOUND','محصول پیدا نشد.');for(const item of items){const a=await sql<any>`SELECT a.is_variant_attribute,a.category_id,v.attribute_id value_attribute_id FROM catalog.attributes a JOIN catalog.attribute_values v ON v.id=${item.attributeValueId}::uuid WHERE a.id=${item.attributeId}::uuid`.execute(ex);if(!a.rows[0])throw new DomainError('ATTRIBUTE_NOT_FOUND','ویژگی یا مقدار آن پیدا نشد.');if(a.rows[0].is_variant_attribute)throw new DomainError('ATTRIBUTE_SCOPE_MISMATCH','ویژگی واریانت را نمی‌توان به خود محصول اختصاص داد.');if(a.rows[0].value_attribute_id!==item.attributeId)throw new DomainError('ATTRIBUTE_VALUE_MISMATCH','مقدار ویژگی متعلق به این ویژگی نیست.');if(a.rows[0].category_id&&a.rows[0].category_id!==p.rows[0].primary_category_id)throw new DomainError('ATTRIBUTE_CATEGORY_MISMATCH','ویژگی متعلق به دسته اصلی این محصول نیست.');}
 await sql`DELETE FROM catalog.product_attribute_values WHERE product_id=${productId}::uuid`.execute(ex);for(const item of items)await sql`INSERT INTO catalog.product_attribute_values(product_id,attribute_id,attribute_value_id) VALUES(${productId}::uuid,${item.attributeId}::uuid,${item.attributeValueId}::uuid)`.execute(ex);}
 async productAttributes(productId:string){const r=await sql<any>`SELECT a.id attribute_id,a.key,a.name_fa,a.unit,a.data_type,a.is_filterable,a.is_comparable,v.id attribute_value_id,v.value_text,v.value_numeric,v.value_boolean,v.normalized_value FROM catalog.product_attribute_values pav JOIN catalog.attributes a ON a.id=pav.attribute_id JOIN catalog.attribute_values v ON v.id=pav.attribute_value_id WHERE pav.product_id=${productId}::uuid ORDER BY a.sort_order,a.name_fa`.execute(this.db);return r.rows;}
 async setVariantAttributes(ex:DatabaseExecutor,variantId:string,items:any[]){const v=await sql<any>`SELECT pv.product_id,p.primary_category_id FROM catalog.product_variants pv JOIN catalog.products p ON p.id=pv.product_id WHERE pv.id=${variantId}::uuid FOR UPDATE OF pv`.execute(ex);if(!v.rows[0])throw new DomainError('VARIANT_NOT_FOUND','واریانت پیدا نشد.');for(const item of items){const a=await sql<any>`SELECT a.is_variant_attribute,a.category_id,val.attribute_id value_attribute_id FROM catalog.attributes a JOIN catalog.attribute_values val ON val.id=${item.attributeValueId}::uuid WHERE a.id=${item.attributeId}::uuid`.execute(ex);if(!a.rows[0])throw new DomainError('ATTRIBUTE_NOT_FOUND','ویژگی یا مقدار آن پیدا نشد.');if(!a.rows[0].is_variant_attribute)throw new DomainError('ATTRIBUTE_SCOPE_MISMATCH','این ویژگی برای خود محصول است، نه واریانت.');if(a.rows[0].value_attribute_id!==item.attributeId)throw new DomainError('ATTRIBUTE_VALUE_MISMATCH','مقدار ویژگی متعلق به این ویژگی نیست.');if(a.rows[0].category_id&&a.rows[0].category_id!==v.rows[0].primary_category_id)throw new DomainError('ATTRIBUTE_CATEGORY_MISMATCH','ویژگی متعلق به دسته اصلی محصول نیست.');}
 await sql`DELETE FROM catalog.variant_attribute_values WHERE variant_id=${variantId}::uuid`.execute(ex);for(const item of items)await sql`INSERT INTO catalog.variant_attribute_values(variant_id,attribute_id,attribute_value_id) VALUES(${variantId}::uuid,${item.attributeId}::uuid,${item.attributeValueId}::uuid)`.execute(ex);}
 async variantAttributes(variantId:string){const r=await sql<any>`SELECT a.id attribute_id,a.key,a.name_fa,a.unit,a.data_type,v.id attribute_value_id,v.value_text,v.value_numeric,v.value_boolean,v.normalized_value FROM catalog.variant_attribute_values vav JOIN catalog.attributes a ON a.id=vav.attribute_id JOIN catalog.attribute_values v ON v.id=vav.attribute_value_id WHERE vav.variant_id=${variantId}::uuid ORDER BY a.sort_order,a.name_fa`.execute(this.db);return r.rows;}
 async categoryFilters(categoryId:string){const r=await sql<any>`SELECT a.id,a.key,a.name_fa,a.data_type,a.unit,a.is_variant_attribute,jsonb_agg(jsonb_build_object('id',v.id,'value_text',v.value_text,'value_numeric',v.value_numeric,'value_boolean',v.value_boolean,'normalized_value',v.normalized_value,'sort_order',v.sort_order) ORDER BY v.sort_order,v.id) FILTER (WHERE v.id IS NOT NULL) values FROM catalog.attributes a LEFT JOIN catalog.attribute_values v ON v.attribute_id=a.id WHERE a.is_filterable=true AND (a.category_id IS NULL OR a.category_id=${categoryId}::uuid) GROUP BY a.id ORDER BY a.sort_order,a.name_fa`.execute(this.db);return r.rows;}
 async rejectMedia(ex:DatabaseExecutor,id:string){const r=await sql`UPDATE catalog.media_assets SET status='rejected',version=version+1,updated_at=now() WHERE id=${id}::uuid AND status IN ('uploading','quarantine','processing')`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('MEDIA_NOT_REJECTABLE','رسانه در وضعیت قابل رد نیست.');}

 async createAttribute(ex:DatabaseExecutor,i:any){await sql`INSERT INTO catalog.attributes(id,category_id,name_fa,key,data_type,unit,is_variant_attribute,is_filterable,is_comparable,sort_order) VALUES(${i.id}::uuid,${i.categoryId}::uuid,${i.nameFa},${i.key},${i.dataType},${i.unit},${i.isVariant},${i.isFilterable},${i.isComparable},${i.sortOrder})`.execute(ex);}
 async listAttributes(categoryId?:string){const r=await sql<any>`SELECT * FROM catalog.attributes WHERE (${categoryId??null}::uuid IS NULL OR category_id=${categoryId??null}::uuid OR category_id IS NULL) ORDER BY sort_order,name_fa`.execute(this.db);return r.rows;}
 async createAttributeValue(ex:DatabaseExecutor,i:any){await sql`INSERT INTO catalog.attribute_values(id,attribute_id,value_text,value_numeric,value_boolean,normalized_value,sort_order) VALUES(${i.id}::uuid,${i.attributeId}::uuid,${i.valueText},${i.valueNumeric},${i.valueBoolean},${i.normalizedValue},${i.sortOrder})`.execute(ex);}
 async listAttributeValues(attributeId:string){const r=await sql<any>`SELECT * FROM catalog.attribute_values WHERE attribute_id=${attributeId}::uuid ORDER BY sort_order,id`.execute(this.db);return r.rows;}
 async attachProductMedia(ex:DatabaseExecutor,i:any){const p=await sql<any>`SELECT id FROM catalog.products WHERE id=${i.productId}::uuid`.execute(ex);if(!p.rows[0])throw new DomainError('PRODUCT_NOT_FOUND','محصول پیدا نشد.');const m=await sql<any>`SELECT status,mime_type FROM catalog.media_assets WHERE id=${i.mediaId}::uuid`.execute(ex);if(!m.rows[0])throw new DomainError('MEDIA_NOT_FOUND','رسانه پیدا نشد.');if(m.rows[0].status!=='active')throw new DomainError('MEDIA_NOT_ACTIVE','رسانه هنوز آماده استفاده نیست.');if(i.variantId){const v=await sql<any>`SELECT product_id FROM catalog.product_variants WHERE id=${i.variantId}::uuid`.execute(ex);if(!v.rows[0]||v.rows[0].product_id!==i.productId)throw new DomainError('MEDIA_VARIANT_PRODUCT_MISMATCH','واریانت متعلق به این محصول نیست.');}const expectedType=String(m.rows[0].mime_type).startsWith('image/')?'image':String(m.rows[0].mime_type).startsWith('video/')?'video':'document';if(i.mediaType!==expectedType)throw new DomainError('MEDIA_TYPE_MISMATCH','نوع رسانه با فایل بارگذاری‌شده سازگار نیست.');if(i.isPrimary)await sql`UPDATE catalog.product_media SET is_primary=false WHERE product_id=${i.productId}::uuid`.execute(ex);await sql`INSERT INTO catalog.product_media(id,product_id,variant_id,media_id,media_type,sort_order,is_primary,alt_text_fa) VALUES(${i.id}::uuid,${i.productId}::uuid,${i.variantId}::uuid,${i.mediaId}::uuid,${i.mediaType},${i.sortOrder},${i.isPrimary},${i.altText}) ON CONFLICT(product_id,media_id) DO UPDATE SET variant_id=EXCLUDED.variant_id,media_type=EXCLUDED.media_type,sort_order=EXCLUDED.sort_order,is_primary=EXCLUDED.is_primary,alt_text_fa=EXCLUDED.alt_text_fa`.execute(ex);}
 async productMedia(productId:string){const r=await sql<any>`SELECT pm.*,m.storage_key,m.mime_type,m.status FROM catalog.product_media pm JOIN catalog.media_assets m ON m.id=pm.media_id WHERE pm.product_id=${productId}::uuid ORDER BY pm.sort_order,pm.created_at`.execute(this.db);return r.rows;}
 async detachProductMedia(ex:DatabaseExecutor,productId:string,mediaId:string){const r=await sql`DELETE FROM catalog.product_media WHERE product_id=${productId}::uuid AND media_id=${mediaId}::uuid`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('MEDIA_NOT_ATTACHED','رسانه به این محصول متصل نیست.');}
 async reorderProductMedia(ex:DatabaseExecutor,productId:string,items:any[]){const primaries=items.filter(x=>x.is_primary);if(primaries.length>1)throw new DomainError('MULTIPLE_PRIMARY_MEDIA','فقط یک رسانه اصلی مجاز است.');for(const item of items){if(!Number.isInteger(Number(item.sort_order))||Number(item.sort_order)<0)throw new DomainError('VALIDATION_ERROR','ترتیب رسانه معتبر نیست.');const exists=await sql<any>`SELECT 1 ok FROM catalog.product_media WHERE product_id=${productId}::uuid AND media_id=${String(item.media_id)}::uuid`.execute(ex);if(!exists.rows[0])throw new DomainError('MEDIA_NOT_ATTACHED','یکی از رسانه‌ها به این محصول متصل نیست.');}if(primaries.length)await sql`UPDATE catalog.product_media SET is_primary=false WHERE product_id=${productId}::uuid`.execute(ex);for(const item of items)await sql`UPDATE catalog.product_media SET sort_order=${Number(item.sort_order)},is_primary=${!!item.is_primary} WHERE product_id=${productId}::uuid AND media_id=${String(item.media_id)}::uuid`.execute(ex);}
 async syncAdditionalCategories(ex:DatabaseExecutor,productId:string,categoryIds:string[]){const p=await sql<any>`SELECT primary_category_id FROM catalog.products WHERE id=${productId}::uuid`.execute(ex);if(!p.rows[0])throw new DomainError('PRODUCT_NOT_FOUND','محصول پیدا نشد.');if(categoryIds.includes(p.rows[0].primary_category_id))throw new DomainError('PRIMARY_CATEGORY_DUPLICATED','دسته اصلی نباید دوباره به‌عنوان دسته اضافی ثبت شود.');await sql`DELETE FROM catalog.product_categories WHERE product_id=${productId}::uuid`.execute(ex);if(categoryIds.length)await sql`INSERT INTO catalog.product_categories(product_id,category_id) SELECT ${productId}::uuid,x FROM unnest(ARRAY[${sql.join(categoryIds.map(id=>sql`${id}::uuid`))}]) AS x ON CONFLICT DO NOTHING`.execute(ex);}
 async additionalCategories(productId:string){const r=await sql<any>`SELECT c.id,c.name_fa,c.slug FROM catalog.product_categories pc JOIN catalog.categories c ON c.id=pc.category_id WHERE pc.product_id=${productId}::uuid ORDER BY c.name_fa`.execute(this.db);return r.rows;}
 async primaryMedia(productId:string){const r=await sql<any>`SELECT m.id,m.storage_key,pm.alt_text_fa FROM catalog.product_media pm JOIN catalog.media_assets m ON m.id=pm.media_id WHERE pm.product_id=${productId}::uuid AND pm.is_primary=true AND m.status='active' LIMIT 1`.execute(this.db);return r.rows[0]??null;}
 async applyScopedSales(ex:DatabaseExecutor,scopeType:string,scopeId:string|null,enabled:boolean){if(scopeType==='global')return this.setGlobalSales(ex,enabled);if(scopeType==='brand'){await sql`UPDATE catalog.brands SET sales_enabled=${enabled},version=version+1,updated_at=now() WHERE id=${scopeId}::uuid`.execute(ex);return;}if(scopeType==='category'){await sql`UPDATE catalog.categories SET sales_enabled=${enabled},version=version+1,updated_at=now() WHERE id=${scopeId}::uuid`.execute(ex);return;}if(scopeType==='product'){await sql`UPDATE catalog.products SET sales_enabled=${enabled},version=version+1,updated_at=now() WHERE id=${scopeId}::uuid AND status<>'archived'`.execute(ex);return;}if(scopeType==='variant'){await sql`UPDATE catalog.product_variants SET sales_enabled=${enabled},version=version+1,updated_at=now() WHERE id=${scopeId}::uuid AND status='active'`.execute(ex);return;}throw new DomainError('INVALID_SALES_SCOPE','دامنه توقف فروش معتبر نیست.');}
 async isCategoryDescendant(candidateParent:string,categoryId:string){const r=await sql<any>`WITH RECURSIVE tree AS (SELECT id,parent_id FROM catalog.categories WHERE id=${candidateParent}::uuid UNION ALL SELECT c.id,c.parent_id FROM catalog.categories c JOIN tree t ON c.id=t.parent_id) SELECT EXISTS(SELECT 1 FROM tree WHERE id=${categoryId}::uuid) ok`.execute(this.db);return !!r.rows[0]?.ok;}
 async salesControlCount(scopeType:string,scopeId:string|null){const r=await sql<any>`SELECT CASE ${scopeType} WHEN 'global' THEN (SELECT count(*) FROM catalog.products) WHEN 'brand' THEN (SELECT count(*) FROM catalog.products WHERE brand_id=${scopeId}::uuid) WHEN 'category' THEN (SELECT count(*) FROM catalog.products WHERE primary_category_id=${scopeId}::uuid OR id IN (SELECT product_id FROM catalog.product_categories WHERE category_id=${scopeId}::uuid)) WHEN 'product' THEN (SELECT count(*) FROM catalog.products WHERE id=${scopeId}::uuid) WHEN 'variant' THEN (SELECT count(*) FROM catalog.product_variants WHERE id=${scopeId}::uuid) ELSE 0 END::int affected_count`.execute(this.db);return Number(r.rows[0]?.affected_count??0);}
 async createSalesPreview(ex:DatabaseExecutor,i:{id:string;scopeType:string;scopeId:string|null;salesEnabled:boolean;affectedCount:number;requestedBy?:string}){await sql`INSERT INTO catalog.sales_control_previews(id,scope_type,scope_id,sales_enabled,affected_count,requested_by,expires_at) VALUES(${i.id}::uuid,${i.scopeType},${i.scopeId}::uuid,${i.salesEnabled},${i.affectedCount},${i.requestedBy??null}::uuid,now()+interval '10 minutes')`.execute(ex);}
 async consumeSalesPreview(ex:DatabaseExecutor,id:string){const r=await sql<any>`UPDATE catalog.sales_control_previews SET consumed_at=now() WHERE id=${id}::uuid AND consumed_at IS NULL AND expires_at>now() RETURNING *`.execute(ex);return r.rows[0]??null;}
 async setGlobalSales(ex:DatabaseExecutor,enabled:boolean){await sql`UPDATE catalog.sales_settings SET global_sales_enabled=${enabled},version=version+1,updated_at=now() WHERE singleton=true`.execute(ex);}
}
function mapProduct(r:any):ProductState{return{id:r.id,brandId:r.brand_id??null,primaryCategoryId:r.primary_category_id,nameFa:r.name_fa,nameEn:r.name_en??null,slug:r.slug,shortDescription:r.short_description??null,description:r.description??null,status:r.status,salesEnabled:r.sales_enabled,publishedAt:d(r.published_at),archivedAt:d(r.archived_at),archiveReason:r.archive_reason??null,version:n(r.version)}}
function mapVariant(r:any):VariantState{return{id:r.id,productId:r.product_id,sku:r.sku,barcode:r.barcode??null,nameSuffix:r.name_suffix??null,status:r.status,salesEnabled:r.sales_enabled,weightGrams:r.weight_grams==null?null:n(r.weight_grams),version:n(r.version)}}
function mapBrand(r:any):BrandState{return{id:r.id,nameFa:r.name_fa,nameEn:r.name_en??null,slug:r.slug,description:r.description??null,status:r.status,salesEnabled:r.sales_enabled,version:n(r.version)}}
function mapCategory(r:any):CategoryState{return{id:r.id,parentId:r.parent_id??null,nameFa:r.name_fa,slug:r.slug,description:r.description??null,status:r.status,salesEnabled:r.sales_enabled,sortOrder:n(r.sort_order),version:n(r.version)}}
function paginate(rows:any[],limit:number){const more=rows.length>limit;const data=more?rows.slice(0,limit):rows;const last=data.at(-1);return{data,nextCursor:more&&last?.created_at?Buffer.from(new Date(last.created_at).toISOString()).toString('base64url'):null,hasMore:more};}
