import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { TransactionManager } from '../../../platform/database/transaction-manager';
import { RequestContextStore } from '../../../platform/request-context/request-context.store';
import { AuditWriter } from '../../../platform/audit/audit.writer';
import { DomainError } from '../../../shared/errors/domain-error';
import { NotificationTemplateRepository } from '../infrastructure/notification-template.repository';
import { NotificationTemplateRenderer,TemplateChannel } from '../domain/notification-template.renderer';
@Injectable() export class NotificationTemplateService{
 constructor(private readonly tx:TransactionManager,private readonly repo:NotificationTemplateRepository,private readonly ctx:RequestContextStore,private readonly audit:AuditWriter,private readonly renderer:NotificationTemplateRenderer){}
 private staff(){const a=this.ctx.get()?.actor;if(a?.type!=='staff'||!a.id)throw new DomainError('STAFF_REQUIRED','دسترسی مدیر الزامی است.');return a.id;}
 private uuid(v:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v))throw new DomainError('VALIDATION_ERROR','شناسه معتبر نیست.');return v;}
 private key(v:unknown){const s=String(v??'').trim();if(!/^[a-z][a-z0-9_.-]{2,159}$/.test(s))throw new DomainError('NOTIFICATION_TEMPLATE_KEY_INVALID','کلید قالب نامعتبر است.');return s;}
 private locale(v:unknown){const s=String(v??'fa-IR').trim();if(!/^[a-z]{2,3}(?:-[A-Z]{2})?$/.test(s))throw new DomainError('NOTIFICATION_TEMPLATE_LOCALE_INVALID','زبان قالب نامعتبر است.');return s;}
 private channel(v:unknown){const s=String(v??'') as TemplateChannel;if(!['sms','email','in_app'].includes(s))throw new DomainError('NOTIFICATION_TEMPLATE_CHANNEL_INVALID','کانال قالب نامعتبر است.');return s;}
 async list(filter:any={}){this.staff();return{items:await this.repo.list({key:filter.key?this.key(filter.key):undefined,channel:filter.channel?this.channel(filter.channel):undefined,locale:filter.locale?this.locale(filter.locale):undefined})};}
 async get(id:string){this.staff();const r=await this.repo.byId(this.uuid(id));if(!r)throw new DomainError('NOTIFICATION_TEMPLATE_NOT_FOUND','قالب پیدا نشد.');return r;}
 async create(input:any){const actor=this.staff(),key=this.key(input?.template_key??input?.key),channel=this.channel(input?.channel),locale=this.locale(input?.locale),nameFa=input?.name_fa==null?null:String(input.name_fa).trim(),subject=input?.subject_template==null?null:String(input.subject_template),body=String(input?.body_template??''),strict=input?.strict_variables!==false,vars=input?.variables??input?.allowed_variables??[],required=input?.required_variables??vars;const meta=this.renderer.validateSource(channel,subject,body,required,vars),ctx=this.ctx.require(),id=randomUUID();if(nameFa!==null&&(nameFa.length<1||nameFa.length>200))throw new DomainError('VALIDATION_ERROR','نام فارسی قالب نامعتبر است.');return this.tx.run(async ex=>{const version=await this.repo.nextVersion(ex,key,channel,locale);const row=await this.repo.create(ex,{id,key,nameFa,channel,locale,version,subject,body,required:meta.required,allowed:meta.allowed,strict,actorId:actor});await this.audit.writeWith(ex,{actorType:'staff',actorId:actor,action:'notifications.template.create',resourceType:'notification_template',resourceId:id,afterData:{template_key:key,channel,locale,version,status:'draft',required_variables:meta.required,allowed_variables:meta.allowed,strict_variables:strict},requestId:ctx.requestId,traceId:ctx.traceId});return row;});}

 async revise(id:string,input:any){const actor=this.staff(),ctx=this.ctx.require();return this.tx.run(async ex=>{const before=await this.repo.byId(this.uuid(id),ex,true);if(!before)throw new DomainError('NOTIFICATION_TEMPLATE_NOT_FOUND','قالب پیدا نشد.');const nameFa=input?.name_fa===undefined?before.name_fa:(input.name_fa===null?null:String(input.name_fa).trim()),subject=input?.subject_template===undefined?before.subject_template:input.subject_template,body=input?.body_template===undefined?before.body_template:String(input.body_template),vars=input?.variables===undefined?before.allowed_variables:input.variables,required=input?.variables===undefined?before.required_variables:input.variables;const meta=this.renderer.validateSource(before.channel,subject,body,required,vars),newId=randomUUID(),version=await this.repo.nextVersion(ex,before.template_key,before.channel,before.locale);const row=await this.repo.create(ex,{id:newId,key:before.template_key,nameFa,channel:before.channel,locale:before.locale,version,subject,body,required:meta.required,allowed:meta.allowed,strict:before.strict_variables,actorId:actor});await this.audit.writeWith(ex,{actorType:'staff',actorId:actor,action:'notifications.template.revise',resourceType:'notification_template',resourceId:newId,beforeData:{template_id:before.id,version:before.version},afterData:{template_key:before.template_key,version,status:'draft'},requestId:ctx.requestId,traceId:ctx.traceId});return row;});}
 async activate(id:string){const actor=this.staff(),ctx=this.ctx.require();return this.tx.run(async ex=>{const before=await this.repo.byId(this.uuid(id),ex,true);if(!before)throw new DomainError('NOTIFICATION_TEMPLATE_NOT_FOUND','قالب پیدا نشد.');if(before.status!=='draft')throw new DomainError('NOTIFICATION_TEMPLATE_INVALID_STATE','فقط نسخه پیش‌نویس قابل فعال‌سازی است.');this.renderer.validateSource(before.channel,before.subject_template,before.body_template,before.required_variables,before.allowed_variables);const row=await this.repo.activate(ex,id,actor);if(!row)throw new DomainError('NOTIFICATION_TEMPLATE_CONFLICT','فعال‌سازی قالب انجام نشد.');await this.audit.writeWith(ex,{actorType:'staff',actorId:actor,action:'notifications.template.activate',resourceType:'notification_template',resourceId:id,beforeData:{status:before.status},afterData:{status:'active',template_key:row.template_key,channel:row.channel,locale:row.locale,version:row.version},requestId:ctx.requestId,traceId:ctx.traceId});return row;});}
 async retire(id:string){const actor=this.staff(),ctx=this.ctx.require();return this.tx.run(async ex=>{const before=await this.repo.byId(this.uuid(id),ex,true);if(!before)throw new DomainError('NOTIFICATION_TEMPLATE_NOT_FOUND','قالب پیدا نشد.');if(before.status==='retired')throw new DomainError('NOTIFICATION_TEMPLATE_INVALID_STATE','قالب قبلاً بازنشسته شده است.');const row=await this.repo.retire(ex,id,actor);await this.audit.writeWith(ex,{actorType:'staff',actorId:actor,action:'notifications.template.retire',resourceType:'notification_template',resourceId:id,beforeData:{status:before.status},afterData:{status:'retired'},requestId:ctx.requestId,traceId:ctx.traceId});return row;});}
 async preview(id:string,input:any){this.staff();const t=await this.repo.byId(this.uuid(id));if(!t)throw new DomainError('NOTIFICATION_TEMPLATE_NOT_FOUND','قالب پیدا نشد.');return{template_id:t.id,template_key:t.template_key,channel:t.channel,locale:t.locale,version:Number(t.version),recipient:input?.recipient??null,...this.renderer.render(t,input?.sample_variables??input?.variables??{})};}
 async renderActive(keyRaw:string,channelRaw:string,localeRaw:string,variables:Record<string,unknown>){const key=this.key(keyRaw),channel=this.channel(channelRaw),locale=this.locale(localeRaw);const t=await this.repo.active(key,channel,locale);if(!t)throw new DomainError('NOTIFICATION_TEMPLATE_ACTIVE_NOT_FOUND','نسخه فعال قالب پیدا نشد.');return{template:t,rendered:this.renderer.render(t,variables)};}
}
