import { Inject,Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { TransactionManager } from '../../../platform/database/transaction-manager';
import { RequestContextStore } from '../../../platform/request-context/request-context.store';
import { AuditWriter } from '../../../platform/audit/audit.writer';
import { OutboxWriter } from '../../../platform/outbox/outbox-writer';
import { STORE_CONFIGURATION_PORT,StoreConfigurationPort } from '../../configuration/application/ports/store-configuration.port';
import { NOTIFICATION_RECIPIENT_PORT,NotificationRecipientPort } from './ports/notification-recipient.port';
import { NotificationProviderRegistry } from '../infrastructure/notification-provider.registry';
import { NotificationDeliveryRepository } from '../infrastructure/notification-delivery.repository';
import { NotificationRetryPolicy } from '../domain/notification-retry.policy';
import { deliveryEvent } from '../domain/notification.events';
@Injectable()
export class NotificationDeliveryService{
 constructor(private readonly tx:TransactionManager,private readonly repo:NotificationDeliveryRepository,private readonly providers:NotificationProviderRegistry,@Inject(NOTIFICATION_RECIPIENT_PORT)private readonly recipients:NotificationRecipientPort,@Inject(STORE_CONFIGURATION_PORT)private readonly config:StoreConfigurationPort,private readonly retryPolicy:NotificationRetryPolicy,private readonly ctx:RequestContextStore,private readonly audit:AuditWriter,private readonly outbox:OutboxWriter){}
 private context(){return this.ctx.get()??{requestId:`notification-worker-${randomUUID()}`,correlationId:randomUUID(),actor:{type:'system' as const}};}
 async processBatch(limit=25){const claimed=await this.tx.run(ex=>this.repo.claim(ex,limit));const results=[];for(const d of claimed)results.push(await this.processOne(d));return results;}
 private async processOne(d:any){const channel=d.channel as 'sms'|'email',provider=this.providers.get(channel);if(!provider)return this.finalizeBlocked(d,null,'NOTIFICATION_PROVIDER_UNAVAILABLE','ارائه‌دهنده کانال پیکربندی نشده است.');const recipient=await this.recipients.resolve(d.recipient_subject_type,d.recipient_subject_id),destination=channel==='sms'?recipient?.mobile:recipient?.email;if(!recipient?.active||!destination)return this.finalizeBlocked(d,provider.key,'NOTIFICATION_DESTINATION_UNAVAILABLE','مقصد معتبر برای ارسال در دسترس نیست.');const attempt=await this.tx.run(ex=>this.repo.startAttempt(ex,d,provider.key));let result;try{result=await provider.send({deliveryId:d.id,channel,destination,subject:d.rendered_subject??null,body:d.rendered_body,idempotencyKey:d.id});}catch(e:any){result={status:'retryable_failure' as const,errorCode:'NOTIFICATION_PROVIDER_EXCEPTION',errorMessage:String(e?.message??'provider error')};}return this.finalize(d,attempt,provider.key,result);}
 private async finalizeBlocked(d:any,providerKey:string|null,code:string,msg:string){const attempt=await this.tx.run(ex=>this.repo.startAttempt(ex,d,providerKey));return this.tx.run(async ex=>{await this.repo.finishAttempt(ex,attempt.id,'blocked',{errorCode:code,errorMessage:msg});const row=await this.repo.blocked(ex,d.id,attempt.attemptNo,code,msg);await this.repo.refreshIntent(ex,d.notification_id);await this.record(ex,d,'failed',row,{code,status:'blocked'});return row;});}
 private async finalize(d:any,attempt:any,providerKey:string,result:any){const c=this.context();return this.tx.run(async ex=>{let row:any,eventType:'delivered'|'failed'|'dead_lettered'='failed';if(result.status==='delivered'){await this.repo.finishAttempt(ex,attempt.id,'succeeded',{providerMessageId:result.providerMessageId,metadata:result.metadata});row=await this.repo.delivered(ex,d.id,providerKey,result.providerMessageId??null);eventType='delivered';}else if(result.status==='blocked'){await this.repo.finishAttempt(ex,attempt.id,'blocked',result);row=await this.repo.blocked(ex,d.id,attempt.attemptNo,result.errorCode,result.errorMessage??null);}else if(result.status==='permanent_failure'){await this.repo.finishAttempt(ex,attempt.id,'permanent_failed',result);row=await this.repo.failed(ex,d.id,attempt.attemptNo,result.errorCode,result.errorMessage??null,false);}else{await this.repo.finishAttempt(ex,attempt.id,'retryable_failed',result);const cfgMax=Math.max(1,await this.config.getNumber('notifications.retry.max_attempts',Number(d.max_attempts??5))),maxAttempts=Math.min(Number(d.max_attempts??5),cfgMax);if(attempt.attemptNo>=maxAttempts){row=await this.repo.failed(ex,d.id,attempt.attemptNo,result.errorCode,result.errorMessage??null,true);eventType='dead_lettered';}else{const base=await this.config.getNumber('notifications.retry.base_seconds',30),cap=await this.config.getNumber('notifications.retry.max_seconds',3600),next=new Date(Date.now()+this.retryPolicy.backoffSeconds(attempt.attemptNo,base,cap)*1000);row=await this.repo.retry(ex,d.id,attempt.attemptNo,next,result.errorCode,result.errorMessage??null);}}
 await this.repo.refreshIntent(ex,d.notification_id);if(row&&['delivered','failed','dead_lettered'].includes(row.status))await this.record(ex,d,eventType,row,{provider_key:providerKey,error_code:result.errorCode??null});return row;});}
 private async record(ex:any,d:any,type:'delivered'|'failed'|'dead_lettered',row:any,extra:any){const c=this.context();await this.audit.writeWith(ex,{actorType:c.actor.type,actorId:c.actor.id,action:`notifications.delivery.${row.status}`,resourceType:'notification_delivery',resourceId:d.id,afterData:{channel:d.channel,status:row.status,...extra},requestId:c.requestId,traceId:c.traceId});await this.outbox.append(ex,[deliveryEvent(type,d.id,{notification_id:d.notification_id,channel:d.channel,status:row.status,...extra})],c);}
}
