import { Inject, Injectable } from '@nestjs/common';
import { Kysely, sql } from 'kysely';
import { DatabaseSchema } from '../../../platform/database/database.types';
import { KYSELY_DB } from '../../../platform/database/database.tokens';
import { DatabaseExecutor } from '../../../platform/database/transaction-manager';
import { DomainError } from '../../../shared/errors/domain-error';
import { EffectivePriceRule } from '../domain/pricing.types';

@Injectable() export class PricingRepository {
  constructor(@Inject(KYSELY_DB) private readonly db:Kysely<DatabaseSchema>){}
  async currentBasePrice(variantId:string,at=new Date(),ex:DatabaseExecutor=this.db){const r=await sql<any>`SELECT * FROM pricing.base_prices WHERE variant_id=${variantId}::uuid AND valid_from<=${at} AND (valid_until IS NULL OR valid_until>${at}) ORDER BY valid_from DESC LIMIT 1`.execute(ex);return r.rows[0]??null;}
  async basePriceHistory(variantId?:string){const r=await sql<any>`SELECT bp.*,v.sku,v.product_id FROM pricing.base_prices bp JOIN catalog.product_variants v ON v.id=bp.variant_id WHERE (${variantId??null}::uuid IS NULL OR bp.variant_id=${variantId??null}::uuid) ORDER BY bp.valid_from DESC LIMIT 500`.execute(this.db);return r.rows;}
  async insertBasePrice(ex:DatabaseExecutor,i:{id:string;variantId:string;amountToman:number;sourceType:string;validFrom:Date;validUntil:Date|null;createdBy:string|null}){await sql`INSERT INTO pricing.base_prices(id,variant_id,amount_toman,source_type,valid_from,valid_until,created_by) VALUES(${i.id}::uuid,${i.variantId}::uuid,${i.amountToman},${i.sourceType},${i.validFrom},${i.validUntil},${i.createdBy}::uuid)`.execute(ex);}
  async closeBasePriceAt(ex:DatabaseExecutor,variantId:string,effectiveAt:Date){await sql`UPDATE pricing.base_prices SET valid_until=${effectiveAt} WHERE variant_id=${variantId}::uuid AND valid_from<${effectiveAt} AND (valid_until IS NULL OR valid_until>${effectiveAt})`.execute(ex);}
  async variantContext(variantId:string){const r=await sql<any>`SELECT v.id variant_id,v.product_id,v.status variant_status,v.sales_enabled variant_sales_enabled,p.brand_id,p.primary_category_id,p.status product_status,p.sales_enabled product_sales_enabled,b.sales_enabled brand_sales_enabled,c.sales_enabled category_sales_enabled,s.global_sales_enabled FROM catalog.product_variants v JOIN catalog.products p ON p.id=v.product_id LEFT JOIN catalog.brands b ON b.id=p.brand_id JOIN catalog.categories c ON c.id=p.primary_category_id CROSS JOIN catalog.sales_settings s WHERE v.id=${variantId}::uuid`.execute(this.db);return r.rows[0]??null;}
  async batchVariantPriceInputs(productIds:string[]){if(!productIds.length)return[];const r=await sql<any>`SELECT v.id variant_id,v.product_id,bp.id base_price_id,bp.amount_toman FROM catalog.product_variants v LEFT JOIN LATERAL (SELECT id,amount_toman FROM pricing.base_prices b WHERE b.variant_id=v.id AND b.valid_from<=now() AND (b.valid_until IS NULL OR b.valid_until>now()) ORDER BY b.valid_from DESC LIMIT 1) bp ON true WHERE v.product_id=ANY(${productIds}::uuid[]) AND v.status='active' AND v.sales_enabled=true ORDER BY v.product_id,v.id`.execute(this.db);return r.rows;}
  async batchEffectiveRules(variantIds:string[]){if(!variantIds.length)return[];const r=await sql<any>`SELECT DISTINCT v.id variant_id,pr.id,pr.name_fa,pr.priority,pr.value_type,pr.value_numeric,pr.min_quantity,pr.max_quantity,pr.customer_type,pr.stacking_policy FROM catalog.product_variants v JOIN catalog.products p ON p.id=v.product_id JOIN pricing.price_rules pr ON pr.status='active' AND (pr.starts_at IS NULL OR pr.starts_at<=now()) AND (pr.ends_at IS NULL OR pr.ends_at>now()) WHERE v.id=ANY(${variantIds}::uuid[]) AND (pr.is_global OR EXISTS(SELECT 1 FROM pricing.price_rule_variants x WHERE x.price_rule_id=pr.id AND x.variant_id=v.id) OR EXISTS(SELECT 1 FROM pricing.price_rule_products x WHERE x.price_rule_id=pr.id AND x.product_id=p.id) OR (p.brand_id IS NOT NULL AND EXISTS(SELECT 1 FROM pricing.price_rule_brands x WHERE x.price_rule_id=pr.id AND x.brand_id=p.brand_id)) OR EXISTS(SELECT 1 FROM pricing.price_rule_categories x WHERE x.price_rule_id=pr.id AND x.category_id=p.primary_category_id)) ORDER BY v.id,pr.priority DESC,pr.id`.execute(this.db);return r.rows;}
  async productVariantIds(productId:string){const r=await sql<any>`SELECT id FROM catalog.product_variants WHERE product_id=${productId}::uuid AND status='active' AND sales_enabled=true ORDER BY id`.execute(this.db);return r.rows.map((x:any)=>String(x.id));}
  async effectiveRules(variantId:string,at=new Date()):Promise<EffectivePriceRule[]>{const r=await sql<any>`SELECT DISTINCT pr.id,pr.name_fa,pr.priority,pr.value_type,pr.value_numeric,pr.min_quantity,pr.max_quantity,pr.customer_type,pr.stacking_policy FROM pricing.price_rules pr JOIN catalog.product_variants v ON v.id=${variantId}::uuid JOIN catalog.products p ON p.id=v.product_id WHERE pr.status='active' AND (pr.starts_at IS NULL OR pr.starts_at<=${at}) AND (pr.ends_at IS NULL OR pr.ends_at>${at}) AND (pr.is_global OR EXISTS(SELECT 1 FROM pricing.price_rule_variants x WHERE x.price_rule_id=pr.id AND x.variant_id=v.id) OR EXISTS(SELECT 1 FROM pricing.price_rule_products x WHERE x.price_rule_id=pr.id AND x.product_id=p.id) OR (p.brand_id IS NOT NULL AND EXISTS(SELECT 1 FROM pricing.price_rule_brands x WHERE x.price_rule_id=pr.id AND x.brand_id=p.brand_id)) OR EXISTS(SELECT 1 FROM pricing.price_rule_categories x WHERE x.price_rule_id=pr.id AND x.category_id=p.primary_category_id)) ORDER BY pr.priority DESC,pr.id`.execute(this.db);return r.rows.map((x:any)=>({id:x.id,nameFa:x.name_fa,priority:Number(x.priority),valueType:x.value_type,valueNumeric:Number(x.value_numeric),minQuantity:x.min_quantity==null?null:Number(x.min_quantity),maxQuantity:x.max_quantity==null?null:Number(x.max_quantity),customerType:x.customer_type??null,stackingPolicy:x.stacking_policy}));}
  async insertRule(ex:DatabaseExecutor,i:any){await sql`INSERT INTO pricing.price_rules(id,name_fa,rule_type,priority,value_type,value_numeric,starts_at,ends_at,customer_type,min_quantity,max_quantity,stacking_policy,is_global,status,created_by) VALUES(${i.id}::uuid,${i.nameFa},${i.ruleType},${i.priority},${i.valueType},${i.valueNumeric},${i.startsAt},${i.endsAt},${i.customerType},${i.minQuantity},${i.maxQuantity},${i.stackingPolicy},${i.isGlobal},'draft',${i.createdBy}::uuid)`.execute(ex);await this.replaceScopes(ex,i.id,i.scopes);}
  async ruleById(id:string,ex:DatabaseExecutor=this.db,lock=false){const r=await sql<any>`SELECT * FROM pricing.price_rules WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]??null;}
  async listRules(){const r=await sql<any>`SELECT * FROM pricing.price_rules ORDER BY created_at DESC LIMIT 500`.execute(this.db);return r.rows;}
  async updateRule(ex:DatabaseExecutor,id:string,input:any,expected:number){const current=await this.ruleById(id,ex,true);if(!current)throw new DomainError('PRICE_RULE_NOT_FOUND','قانون قیمت پیدا نشد.');if(Number(current.version)!==expected)throw new DomainError('VERSION_CONFLICT','قانون قیمت همزمان تغییر کرده است.');const r=await sql`UPDATE pricing.price_rules SET name_fa=COALESCE(${input.nameFa??null},name_fa),priority=COALESCE(${input.priority??null},priority),value_numeric=COALESCE(${input.valueNumeric??null},value_numeric),starts_at=${input.startsAt===undefined?current.starts_at:input.startsAt},ends_at=${input.endsAt===undefined?current.ends_at:input.endsAt},min_quantity=${input.minQuantity===undefined?current.min_quantity:input.minQuantity},max_quantity=${input.maxQuantity===undefined?current.max_quantity:input.maxQuantity},stacking_policy=COALESCE(${input.stackingPolicy??null},stacking_policy),version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','قانون قیمت همزمان تغییر کرده است.');}
  async setRuleStatus(ex:DatabaseExecutor,id:string,status:string){const r=await sql<any>`UPDATE pricing.price_rules SET status=${status},version=version+1,updated_at=now() WHERE id=${id}::uuid RETURNING *`.execute(ex);if(!r.rows[0])throw new DomainError('PRICE_RULE_NOT_FOUND','قانون قیمت پیدا نشد.');return r.rows[0];}
  private async replaceScopes(ex:DatabaseExecutor,ruleId:string,scopes:any[]){for(const s of scopes){if(s.scope_type==='global')continue;if(!s.scope_id)throw new DomainError('VALIDATION_ERROR','scope_id برای دامنه انتخابی الزامی است.');const table=s.scope_type==='variant'?'price_rule_variants':s.scope_type==='product'?'price_rule_products':s.scope_type==='brand'?'price_rule_brands':s.scope_type==='category'?'price_rule_categories':null;if(!table)throw new DomainError('PRICE_RULE_SCOPE_UNSUPPORTED','دامنه این قانون قیمت هنوز پشتیبانی نمی‌شود.');const col=s.scope_type+'_id';await sql.raw(`INSERT INTO pricing.${table}(price_rule_id,${col}) VALUES ('${escapeUuid(ruleId)}'::uuid,'${escapeUuid(s.scope_id)}'::uuid) ON CONFLICT DO NOTHING`).execute(ex);}}
  async rateById(id:string){const r=await sql<any>`SELECT * FROM pricing.currency_rates WHERE id=${id}::uuid LIMIT 1`.execute(this.db);return r.rows[0]??null;}
  async selectedRate(code:string){const r=await sql<any>`SELECT * FROM pricing.currency_rates WHERE source_currency_code=${code} AND is_selected=true LIMIT 1`.execute(this.db);return r.rows[0]??null;}
  async listRates(code?:string){const r=await sql<any>`SELECT * FROM pricing.currency_rates WHERE (${code??null}::text IS NULL OR source_currency_code=${code??null}) ORDER BY observed_at DESC LIMIT 500`.execute(this.db);return r.rows;}
  async insertRate(ex:DatabaseExecutor,i:{id:string;code:string;rate:number;providerId:string|null;observedAt:Date;status:string}){await sql`INSERT INTO pricing.currency_rates(id,source_currency_code,rate_to_toman,source_provider_id,observed_at,status,validated_at) VALUES(${i.id}::uuid,${i.code},${i.rate},${i.providerId}::uuid,${i.observedAt},${i.status},CASE WHEN ${i.status}='validated' THEN now() ELSE NULL END)`.execute(ex);}
  async selectRate(ex:DatabaseExecutor,id:string){const r=await sql<any>`SELECT * FROM pricing.currency_rates WHERE id=${id}::uuid FOR UPDATE`.execute(ex);if(!r.rows[0])throw new DomainError('CURRENCY_RATE_NOT_FOUND','نرخ ارز پیدا نشد.');if(!['validated','active'].includes(r.rows[0].status))throw new DomainError('CURRENCY_RATE_NOT_VALIDATED','فقط نرخ معتبر قابل انتخاب است.');await sql`UPDATE pricing.currency_rates SET is_selected=false,status=CASE WHEN status='active' THEN 'validated' ELSE status END WHERE source_currency_code=${r.rows[0].source_currency_code} AND is_selected=true`.execute(ex);await sql`UPDATE pricing.currency_rates SET is_selected=true,status='active',validated_at=COALESCE(validated_at,now()) WHERE id=${id}::uuid`.execute(ex);return {...r.rows[0],is_selected:true,status:'active'};}
  async rejectRate(ex:DatabaseExecutor,id:string){const r=await sql<any>`UPDATE pricing.currency_rates SET status='rejected',is_selected=false WHERE id=${id}::uuid RETURNING *`.execute(ex);if(!r.rows[0])throw new DomainError('CURRENCY_RATE_NOT_FOUND','نرخ ارز پیدا نشد.');return r.rows[0];}
  async variantsForScope(scopeType:string,scopeIds:string[],includeInactive=false,limit=5_001){const ids=scopeIds??[];if(!Number.isSafeInteger(limit)||limit<1||limit>5_001)throw new DomainError('PRICING_BULK_LIMIT_INVALID','محدوده عملیات گروهی قیمت معتبر نیست.');let predicate=sql`TRUE`;if(scopeType==='product')predicate=sql`p.id = ANY(${ids}::uuid[])`;else if(scopeType==='brand')predicate=sql`p.brand_id = ANY(${ids}::uuid[])`;else if(scopeType==='category')predicate=sql`p.primary_category_id = ANY(${ids}::uuid[])`;else if(scopeType!=='all')throw new DomainError('VALIDATION_ERROR','دامنه عملیات گروهی معتبر نیست.');const r=await sql<any>`SELECT v.id variant_id,v.product_id,p.brand_id,p.primary_category_id FROM catalog.product_variants v JOIN catalog.products p ON p.id=v.product_id WHERE (${includeInactive} OR v.status='active') AND ${predicate} ORDER BY v.id LIMIT ${limit}`.execute(this.db);return r.rows;}
  async listCurrencyRules(){const r=await sql<any>`SELECT * FROM pricing.currency_rules ORDER BY created_at DESC`.execute(this.db);return r.rows;}
  async createCurrencyRule(ex:DatabaseExecutor,i:any){await sql`INSERT INTO pricing.currency_rules(id,name_fa,source_currency_code,coefficient,fixed_cost_toman,rounding_multiple_toman,is_global,status) VALUES(${i.id}::uuid,${i.nameFa},${i.code},${i.coefficient},${i.fixedCostToman},${i.roundingMultipleToman},${i.isGlobal},${i.status})`.execute(ex);for(const s of i.scopes??[]){if(s.scope_type==='global')continue;if(!s.scope_id)throw new DomainError('VALIDATION_ERROR','scope_id الزامی است.');const table=s.scope_type==='variant'?'currency_rule_variants':s.scope_type==='product'?'currency_rule_products':s.scope_type==='brand'?'currency_rule_brands':s.scope_type==='category'?'currency_rule_categories':null;if(!table)throw new DomainError('VALIDATION_ERROR','دامنه قانون ارزی معتبر نیست.');const col=s.scope_type+'_id';await sql.raw(`INSERT INTO pricing.${table}(currency_rule_id,${col}) VALUES ('${escapeUuid(i.id)}'::uuid,'${escapeUuid(s.scope_id)}'::uuid)`).execute(ex);}}
  async currencyRuleById(id:string,ex:DatabaseExecutor=this.db,lock=false){const r=await sql<any>`SELECT * FROM pricing.currency_rules WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]??null;}
  async updateCurrencyRule(ex:DatabaseExecutor,id:string,i:any,expected:number){const current=await this.currencyRuleById(id,ex,true);if(!current)throw new DomainError('CURRENCY_RULE_NOT_FOUND','قانون قیمت ارزی پیدا نشد.');if(Number(current.version)!==expected)throw new DomainError('VERSION_CONFLICT','قانون قیمت ارزی همزمان تغییر کرده است.');const r=await sql`UPDATE pricing.currency_rules SET name_fa=COALESCE(${i.nameFa??null},name_fa),coefficient=COALESCE(${i.coefficient??null},coefficient),fixed_cost_toman=COALESCE(${i.fixedCostToman??null},fixed_cost_toman),rounding_multiple_toman=COALESCE(${i.roundingMultipleToman??null},rounding_multiple_toman),version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','قانون قیمت ارزی همزمان تغییر کرده است.');}
  async setCurrencyRuleStatus(ex:DatabaseExecutor,id:string,status:'active'|'inactive'){const r=await sql<any>`UPDATE pricing.currency_rules SET status=${status},version=version+1,updated_at=now() WHERE id=${id}::uuid RETURNING *`.execute(ex);if(!r.rows[0])throw new DomainError('CURRENCY_RULE_NOT_FOUND','قانون قیمت ارزی پیدا نشد.');return r.rows[0];}
  async currencyRuleForVariant(variantId:string,code:string){const r=await sql<any>`SELECT cr.* FROM pricing.currency_rules cr JOIN catalog.product_variants v ON v.id=${variantId}::uuid JOIN catalog.products p ON p.id=v.product_id WHERE cr.status='active' AND cr.source_currency_code=${code} AND (cr.is_global OR EXISTS(SELECT 1 FROM pricing.currency_rule_variants x WHERE x.currency_rule_id=cr.id AND x.variant_id=v.id) OR EXISTS(SELECT 1 FROM pricing.currency_rule_products x WHERE x.currency_rule_id=cr.id AND x.product_id=p.id) OR (p.brand_id IS NOT NULL AND EXISTS(SELECT 1 FROM pricing.currency_rule_brands x WHERE x.currency_rule_id=cr.id AND x.brand_id=p.brand_id)) OR EXISTS(SELECT 1 FROM pricing.currency_rule_categories x WHERE x.currency_rule_id=cr.id AND x.category_id=p.primary_category_id)) ORDER BY CASE WHEN EXISTS(SELECT 1 FROM pricing.currency_rule_variants x WHERE x.currency_rule_id=cr.id AND x.variant_id=v.id) THEN 5 WHEN EXISTS(SELECT 1 FROM pricing.currency_rule_products x WHERE x.currency_rule_id=cr.id AND x.product_id=p.id) THEN 4 WHEN EXISTS(SELECT 1 FROM pricing.currency_rule_brands x WHERE x.currency_rule_id=cr.id AND x.brand_id=p.brand_id) THEN 3 WHEN EXISTS(SELECT 1 FROM pricing.currency_rule_categories x WHERE x.currency_rule_id=cr.id AND x.category_id=p.primary_category_id) THEN 2 ELSE 1 END DESC,cr.updated_at DESC LIMIT 1`.execute(this.db);return r.rows[0]??null;}
  async createBulkOperation(ex:DatabaseExecutor,i:{id:string;type:string;payload:any;affectedCount:number;warnings:any[];requestedBy:string|null;expiresAt:Date}){await sql`INSERT INTO pricing.bulk_operations(id,operation_type,request_payload,affected_count,warnings,requested_by,expires_at) VALUES(${i.id}::uuid,${i.type},${JSON.stringify(i.payload)}::jsonb,${i.affectedCount},${JSON.stringify(i.warnings)}::jsonb,${i.requestedBy}::uuid,${i.expiresAt})`.execute(ex);}
  async insertBulkItems(ex:DatabaseExecutor,operationId:string,items:any[]){if(!items.length)return;for(const x of items)await sql`INSERT INTO pricing.bulk_operation_items(operation_id,variant_id,old_price_toman,proposed_price_toman,guard_status,guard_reason) VALUES(${operationId}::uuid,${x.variantId}::uuid,${x.oldPriceToman},${x.proposedPriceToman},${x.guardStatus},${x.guardReason??null})`.execute(ex);}
  async bulkOperation(id:string,ex:DatabaseExecutor=this.db,lock=false){const r=await sql<any>`SELECT * FROM pricing.bulk_operations WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);if(!r.rows[0])return null;const items=await sql<any>`SELECT * FROM pricing.bulk_operation_items WHERE operation_id=${id}::uuid ORDER BY variant_id`.execute(ex);return {...r.rows[0],items:items.rows};}
  async markBulkApplied(ex:DatabaseExecutor,id:string){const r=await sql`UPDATE pricing.bulk_operations SET status='completed',applied_at=now(),updated_at=now() WHERE id=${id}::uuid AND status='previewed' AND expires_at>now()`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('PRICING_PREVIEW_EXPIRED','پیش‌نمایش قیمت منقضی یا قبلاً اعمال شده است.');}
}
function escapeUuid(v:string){if(!/^[0-9a-fA-F-]{36}$/.test(v))throw new DomainError('VALIDATION_ERROR','شناسه نامعتبر است.');return v;}
