import { Injectable } from '@nestjs/common';
import { PricingRepository } from '../infrastructure/pricing.repository';
import { PricingEngine } from '../domain/pricing-engine';
import { PricingPublicPort } from './ports/pricing-public.port';import { PricingQuotePort } from './ports/pricing-quote.port';import { ProfitGuardService } from './profit-guard.service';

@Injectable() export class PricingQueryService implements PricingPublicPort, PricingQuotePort {
  private readonly engine=new PricingEngine();
  constructor(private readonly repo:PricingRepository,private readonly guard:ProfitGuardService){}
  async hasSellablePrice(productId:string):Promise<boolean>{const ids=await this.repo.productVariantIds(productId);for(const id of ids){if(await this.repo.currentBasePrice(id))return true;}return false;}
  async getVariantPrice(variantId:string,quantity=1,customerType:'retail'|'wholesale'='retail'){const ctx=await this.repo.variantContext(variantId);if(!ctx||ctx.variant_status!=='active')return null;const bp=await this.repo.currentBasePrice(variantId);if(!bp)return null;const rules=await this.repo.effectiveRules(variantId);let out=this.engine.calculate(Number(bp.amount_toman),rules,quantity,customerType);let guardStatus='not_required';if(out.finalPriceToman<out.basePriceToman){const g=await this.guard.evaluate(variantId,out.finalPriceToman);guardStatus=g.status;if(g.status!=='passed')out={...out,discountToman:0,finalPriceToman:out.basePriceToman,appliedRuleIds:[],warnings:[...out.warnings,String(g.reason??'PROFIT_GUARD_UNAVAILABLE')]};}const appliedRules=rules.filter(r=>out.appliedRuleIds.includes(r.id)).map(r=>({id:r.id,name_fa:r.nameFa,value_type:r.valueType,value_numeric:r.valueNumeric,stacking_policy:r.stackingPolicy}));return{variant_id:variantId,base_price_id:bp.id,base_price_toman:out.basePriceToman,discount_toman:out.discountToman,current_toman:out.finalPriceToman,old_toman:out.discountToman>0?out.basePriceToman:null,discount_percent:out.basePriceToman>0&&out.discountToman>0?Math.round((out.discountToman/out.basePriceToman)*100):null,applied_rule_ids:out.appliedRuleIds,applied_rules:appliedRules,profit_guard_status:guardStatus,warnings:out.warnings,quantity,customer_type:customerType};}
  async getProductPrice(productId:string,quantity=1,customerType:'retail'|'wholesale'='retail'){const ids=await this.repo.productVariantIds(productId);const prices=(await Promise.all(ids.map(id=>this.getVariantPrice(id,quantity,customerType)))).filter(Boolean) as any[];if(!prices.length)return null;prices.sort((a,b)=>a.current_toman-b.current_toman);return{...prices[0],product_id:productId,from_price:prices.length>1};}
  async getProductPrices(productIds:string[],quantity=1,customerType:'retail'|'wholesale'='retail'){const unique=[...new Set(productIds)];const rows=await this.repo.batchVariantPriceInputs(unique),variantIds=rows.filter((x:any)=>x.base_price_id).map((x:any)=>String(x.variant_id)),ruleRows=await this.repo.batchEffectiveRules(variantIds);const byVariant=new Map<string,any[]>();for(const x of ruleRows){const a=byVariant.get(String(x.variant_id))??[];a.push({id:x.id,nameFa:x.name_fa,priority:Number(x.priority),valueType:x.value_type,valueNumeric:Number(x.value_numeric),minQuantity:x.min_quantity==null?null:Number(x.min_quantity),maxQuantity:x.max_quantity==null?null:Number(x.max_quantity),customerType:x.customer_type??null,stackingPolicy:x.stacking_policy});byVariant.set(String(x.variant_id),a);}const byProduct=new Map<string,any[]>();for(const row of rows){if(!row.base_price_id)continue;const rules=byVariant.get(String(row.variant_id))??[];let out=this.engine.calculate(Number(row.amount_toman),rules,quantity,customerType);let guardStatus='not_required';if(out.finalPriceToman<out.basePriceToman){const g=await this.guard.evaluate(String(row.variant_id),out.finalPriceToman);guardStatus=g.status;if(g.status!=='passed')out={...out,discountToman:0,finalPriceToman:out.basePriceToman,appliedRuleIds:[],warnings:[String(g.reason??'PROFIT_GUARD_UNAVAILABLE')]};}const price={variant_id:row.variant_id,base_price_id:row.base_price_id,base_price_toman:out.basePriceToman,discount_toman:out.discountToman,current_toman:out.finalPriceToman,old_toman:out.discountToman?out.basePriceToman:null,discount_percent:out.basePriceToman&&out.discountToman?Math.round(out.discountToman/out.basePriceToman*100):null,applied_rule_ids:out.appliedRuleIds,profit_guard_status:guardStatus,warnings:out.warnings,quantity,customer_type:customerType};const a=byProduct.get(String(row.product_id))??[];a.push(price);byProduct.set(String(row.product_id),a);}const result:Record<string,any|null>={};for(const id of unique){const prices=byProduct.get(id)??[];prices.sort((a,b)=>a.current_toman-b.current_toman);result[id]=prices.length?{...prices[0],product_id:id,from_price:prices.length>1}:null;}return result;}
  quoteVariant(input:{variantId:string;quantity:number;customerType?:'retail'|'wholesale'}){return this.getVariantPrice(input.variantId,input.quantity,input.customerType??'retail');}
  basePrices(variantId?:string){return this.repo.basePriceHistory(variantId);} rules(){return this.repo.listRules();} rule(id:string){return this.repo.ruleById(id);} rates(code?:string){return this.repo.listRates(code);} currentRate(code='USD'){return this.repo.selectedRate(code);} bulk(id:string){return this.repo.bulkOperation(id);}
}
