import { Inject, Injectable } from '@nestjs/common';
import { Kysely, sql } from 'kysely';
import { randomUUID } from 'node:crypto';
import { KYSELY_DB } from '../../../platform/database/database.tokens';
import { DatabaseSchema } from '../../../platform/database/database.types';
import { DatabaseExecutor } from '../../../platform/database/transaction-manager';
import { hashCapabilityToken, newCapabilityToken } from '../../../shared/security/capability-token';
export const hashToken=hashCapabilityToken;
export const newToken=newCapabilityToken;
@Injectable() export class CartRepository { constructor(@Inject(KYSELY_DB) private readonly db:Kysely<DatabaseSchema>){}
 async cart(id:string,ex:DatabaseExecutor=this.db,lock=false){const r=await sql<any>`SELECT * FROM cart.carts WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]??null;}
 async items(id:string,ex:DatabaseExecutor=this.db){const r=await sql<any>`SELECT ci.*,v.sku,v.product_id,p.name_fa product_name,p.brand_id,p.primary_category_id,p.sales_enabled product_sales_enabled,v.sales_enabled variant_sales_enabled,p.status product_status,v.status variant_status,b.sales_enabled brand_sales_enabled,c.sales_enabled category_sales_enabled,s.global_sales_enabled FROM cart.cart_items ci JOIN catalog.product_variants v ON v.id=ci.variant_id JOIN catalog.products p ON p.id=v.product_id LEFT JOIN catalog.brands b ON b.id=p.brand_id JOIN catalog.categories c ON c.id=p.primary_category_id CROSS JOIN catalog.sales_settings s WHERE ci.cart_id=${id}::uuid ORDER BY ci.created_at`.execute(ex);return r.rows;}
 async create(customerId:string|null,ttlHours=168){return this.createWith(this.db,customerId,ttlHours);}
 async createWith(ex:DatabaseExecutor,customerId:string|null,ttlHours=168){const token=newToken(),id=randomUUID();await sql`INSERT INTO cart.carts(id,customer_id,token_hash,expires_at) VALUES(${id}::uuid,${customerId}::uuid,${hashToken(token)},now()+(${ttlHours}||' hours')::interval)`.execute(ex);return{id,token};}
 async add(ex:DatabaseExecutor,cartId:string,variantId:string,q:number){await sql`INSERT INTO cart.cart_items(id,cart_id,variant_id,quantity) VALUES(${randomUUID()}::uuid,${cartId}::uuid,${variantId}::uuid,${q}) ON CONFLICT(cart_id,variant_id) DO UPDATE SET quantity=cart.cart_items.quantity+EXCLUDED.quantity,updated_at=now()`.execute(ex);await sql`UPDATE cart.carts SET version=version+1,updated_at=now() WHERE id=${cartId}::uuid`.execute(ex);}
 async setQty(ex:DatabaseExecutor,cartId:string,itemId:string,q:number){if(q===0)await sql`DELETE FROM cart.cart_items WHERE id=${itemId}::uuid AND cart_id=${cartId}::uuid`.execute(ex);else await sql`UPDATE cart.cart_items SET quantity=${q},updated_at=now() WHERE id=${itemId}::uuid AND cart_id=${cartId}::uuid`.execute(ex);await sql`UPDATE cart.carts SET version=version+1,updated_at=now() WHERE id=${cartId}::uuid`.execute(ex);}
 async shipping(id:string,ex:DatabaseExecutor=this.db){const r=await sql<any>`SELECT id,code,name_fa,fee_toman FROM cart.shipping_methods WHERE id=${id}::uuid AND active=true`.execute(ex);return r.rows[0]??null;}
 async activeShippingMethods(ex:DatabaseExecutor=this.db){const r=await sql<any>`SELECT id,code,name_fa,fee_toman FROM cart.shipping_methods WHERE active=true ORDER BY code`.execute(ex);return r.rows;}
 async checkout(id:string,ex:DatabaseExecutor=this.db,lock=false){const r=await sql<any>`SELECT * FROM cart.checkouts WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]??null;}
 async checkoutItems(id:string,ex:DatabaseExecutor=this.db){const r=await sql<any>`SELECT * FROM cart.checkout_items WHERE checkout_id=${id}::uuid ORDER BY id`.execute(ex);return r.rows;}
 async insertCheckout(ex:DatabaseExecutor,c:any,items:any[]){await sql`INSERT INTO cart.checkouts(id,cart_id,cart_version_snapshot,customer_id,token_hash,status,shipping_method_id,subtotal_toman,discount_toman,shipping_toman,tax_toman,total_toman,expires_at) VALUES(${c.id}::uuid,${c.cartId}::uuid,${c.cartVersion},${c.customerId}::uuid,${c.tokenHash},'quoted',${c.shippingId}::uuid,${c.subtotal},${c.discount},${c.shipping},${c.tax},${c.total},${c.expiresAt})`.execute(ex);for(const i of items)await sql`INSERT INTO cart.checkout_items(id,checkout_id,product_id,variant_id,sku,product_name,quantity,unit_base_toman,unit_final_toman,discount_toman,tax_toman,tax_rule_id,line_total_toman,pricing_snapshot) VALUES(${randomUUID()}::uuid,${c.id}::uuid,${i.product_id}::uuid,${i.variant_id}::uuid,${i.sku},${i.product_name},${i.quantity},${i.unit_base_toman},${i.unit_final_toman},${i.discount_toman},${i.tax_toman},${i.tax_rule_id}::uuid,${i.line_total_toman},${JSON.stringify(i.pricing_snapshot)}::jsonb)`.execute(ex);}

 async expireCustomerCartIfDue(ex:DatabaseExecutor,customerId:string){await sql`UPDATE cart.carts SET status='expired',version=version+1,updated_at=now() WHERE customer_id=${customerId}::uuid AND status='active' AND expires_at<=now()`.execute(ex);}
 async expiredCartIds(limit:number){const r=await sql<any>`SELECT id FROM cart.carts WHERE status='active' AND expires_at<=now() ORDER BY expires_at,id LIMIT ${Math.min(Math.max(limit,1),500)}`.execute(this.db);return r.rows.map((x:any)=>String(x.id));}
 async expireCartIfDue(ex:DatabaseExecutor,cartId:string){const r=await sql<any>`UPDATE cart.carts SET status='expired',version=version+1,updated_at=now() WHERE id=${cartId}::uuid AND status='active' AND expires_at<=now() RETURNING id`.execute(ex);return !!r.rows[0];}

 async activeCustomerCart(customerId:string,ex:DatabaseExecutor=this.db,lock=false){const r=await sql<any>`SELECT * FROM cart.carts WHERE customer_id=${customerId}::uuid AND status='active' ${sql.raw(lock?'FOR UPDATE':'')} LIMIT 1`.execute(ex);return r.rows[0]??null;}
 async rotateToken(ex:DatabaseExecutor,id:string,token:string){await sql`UPDATE cart.carts SET token_hash=${hashToken(token)},updated_at=now() WHERE id=${id}::uuid`.execute(ex);}
 async mergeItems(ex:DatabaseExecutor,sourceId:string,targetId:string){const rows=await this.items(sourceId,ex);for(const i of rows)await this.add(ex,targetId,String(i.variant_id),Number(i.quantity));await sql`UPDATE cart.carts SET status='converted',version=version+1,updated_at=now() WHERE id=${sourceId}::uuid AND status='active'`.execute(ex);}
 async issueAccessToken(ex:DatabaseExecutor,cartId:string,ttlHours=168,maxActive=5){const token=newToken();await sql`DELETE FROM cart.cart_access_tokens WHERE cart_id=${cartId}::uuid AND expires_at<=now()`.execute(ex);await sql`INSERT INTO cart.cart_access_tokens(id,cart_id,token_hash,expires_at) VALUES(${randomUUID()}::uuid,${cartId}::uuid,${hashToken(token)},now()+(${ttlHours}||' hours')::interval)`.execute(ex);await sql`DELETE FROM cart.cart_access_tokens WHERE cart_id=${cartId}::uuid AND id NOT IN (SELECT id FROM cart.cart_access_tokens WHERE cart_id=${cartId}::uuid AND expires_at>now() ORDER BY created_at DESC,id DESC LIMIT ${maxActive})`.execute(ex);return token;}
 async tokenValid(cartId:string,token:string,ex:DatabaseExecutor=this.db){if(!token)return false;const h=hashToken(token);const r=await sql<any>`SELECT 1 FROM cart.carts c WHERE c.id=${cartId}::uuid AND (c.token_hash=${h} OR EXISTS(SELECT 1 FROM cart.cart_access_tokens t WHERE t.cart_id=c.id AND t.token_hash=${h} AND t.expires_at>now())) LIMIT 1`.execute(ex);return !!r.rows[0];}
 async invalidatePrimaryToken(ex:DatabaseExecutor,cartId:string){await sql`UPDATE cart.carts SET token_hash=${hashToken(newToken())},updated_at=now() WHERE id=${cartId}::uuid`.execute(ex);}

 async openQuotedForCart(cartId:string,ex:DatabaseExecutor=this.db){const r=await sql<any>`SELECT id FROM cart.checkouts WHERE cart_id=${cartId}::uuid AND status='quoted' AND expires_at>now()`.execute(ex);return r.rows;}
 async expireQuotedForCart(ex:DatabaseExecutor,cartId:string){await sql`UPDATE cart.checkouts SET status='expired',updated_at=now() WHERE cart_id=${cartId}::uuid AND status='quoted'`.execute(ex);}
 async itemById(cartId:string,itemId:string,ex:DatabaseExecutor=this.db){const r=await sql<any>`SELECT ci.*,v.sku,v.product_id,p.name_fa product_name,p.brand_id,p.primary_category_id,p.sales_enabled product_sales_enabled,v.sales_enabled variant_sales_enabled,p.status product_status,v.status variant_status,b.sales_enabled brand_sales_enabled,c.sales_enabled category_sales_enabled,s.global_sales_enabled FROM cart.cart_items ci JOIN catalog.product_variants v ON v.id=ci.variant_id JOIN catalog.products p ON p.id=v.product_id LEFT JOIN catalog.brands b ON b.id=p.brand_id JOIN catalog.categories c ON c.id=p.primary_category_id CROSS JOIN catalog.sales_settings s WHERE ci.cart_id=${cartId}::uuid AND ci.id=${itemId}::uuid LIMIT 1`.execute(ex);return r.rows[0]??null;}
 async variantForCart(variantId:string,ex:DatabaseExecutor=this.db){const r=await sql<any>`SELECT v.id variant_id,v.sku,v.product_id,p.name_fa product_name,p.brand_id,p.primary_category_id,p.sales_enabled product_sales_enabled,v.sales_enabled variant_sales_enabled,p.status product_status,v.status variant_status,b.sales_enabled brand_sales_enabled,c.sales_enabled category_sales_enabled,s.global_sales_enabled FROM catalog.product_variants v JOIN catalog.products p ON p.id=v.product_id LEFT JOIN catalog.brands b ON b.id=p.brand_id JOIN catalog.categories c ON c.id=p.primary_category_id CROSS JOIN catalog.sales_settings s WHERE v.id=${variantId}::uuid LIMIT 1`.execute(ex);return r.rows[0]??null;}
 async currentItemQuantity(cartId:string,variantId:string,ex:DatabaseExecutor=this.db){const r=await sql<any>`SELECT quantity FROM cart.cart_items WHERE cart_id=${cartId}::uuid AND variant_id=${variantId}::uuid`.execute(ex);return Number(r.rows[0]?.quantity??0);}


 async checkoutHasUnsellableItems(checkoutId:string,ex:DatabaseExecutor=this.db){const r=await sql<any>`SELECT 1 FROM cart.checkout_items ci JOIN catalog.product_variants v ON v.id=ci.variant_id JOIN catalog.products p ON p.id=v.product_id LEFT JOIN catalog.brands b ON b.id=p.brand_id JOIN catalog.categories c ON c.id=p.primary_category_id CROSS JOIN catalog.sales_settings s WHERE ci.checkout_id=${checkoutId}::uuid AND (NOT s.global_sales_enabled OR COALESCE(b.sales_enabled,true)=false OR c.sales_enabled=false OR p.sales_enabled=false OR v.sales_enabled=false OR p.status<>'published' OR v.status<>'active') LIMIT 1`.execute(ex);return !!r.rows[0];}
 async extendCartExpiry(ex:DatabaseExecutor,cartId:string,until:Date){await sql`UPDATE cart.carts SET expires_at=GREATEST(expires_at,${until}::timestamptz),updated_at=now() WHERE id=${cartId}::uuid AND status='active'`.execute(ex);}
 async markOrderCreated(ex:DatabaseExecutor,checkoutId:string,cartId:string,guestAccessExpiresAt:string){const co=await sql<any>`UPDATE cart.checkouts SET status='order_created',guest_order_access_expires_at=CASE WHEN customer_id IS NULL THEN ${guestAccessExpiresAt}::timestamptz ELSE NULL END,updated_at=now() WHERE id=${checkoutId}::uuid AND status='reserved' RETURNING id`.execute(ex);if(!co.rows[0])return false;const ca=await sql<any>`UPDATE cart.carts SET status='converted',version=version+1,updated_at=now() WHERE id=${cartId}::uuid AND status='active' RETURNING id`.execute(ex);return !!ca.rows[0];}

 async expiredCheckoutIds(limit:number){const r=await sql<any>`SELECT id FROM cart.checkouts WHERE status IN ('quoted','reserved') AND expires_at<=now() ORDER BY expires_at,id LIMIT ${Math.min(Math.max(limit,1),500)}`.execute(this.db);return r.rows.map((x:any)=>String(x.id));}

}
