import {Inject,Injectable} from '@nestjs/common';import {Kysely,sql} from 'kysely';
import {KYSELY_DB} from '../../../../platform/database/database.tokens';import {DatabaseSchema} from '../../../../platform/database/database.types';import {DatabaseExecutor} from '../../../../platform/database/transaction-manager';
import {DomainError} from '../../../../shared/errors/domain-error';import {CART_ORDER_CHECKOUT_PORT,CartOrderCheckoutPort} from '../../../cart/application/ports/cart-order-checkout.port';
import {OrderPaymentPort,PayableOrder} from './order-payment.port';import {OutboxWriter} from '../../../../platform/outbox/outbox-writer';import {RequestContextStore} from '../../../../platform/request-context/request-context.store';import {randomUUID} from 'node:crypto';
@Injectable() export class OrderPaymentService implements OrderPaymentPort{
 constructor(@Inject(KYSELY_DB)private readonly db:Kysely<DatabaseSchema>,@Inject(CART_ORDER_CHECKOUT_PORT)private readonly checkout:CartOrderCheckoutPort,private readonly outbox:OutboxWriter,private readonly ctx:RequestContextStore){}
 private present(o:any):PayableOrder{return{id:String(o.id),order_number:String(o.order_number),customer_id:o.customer_id?String(o.customer_id):null,reservation_id:String(o.reservation_id),status:String(o.status),total_toman:Number(o.total_toman),confirmation_expires_at:new Date(o.confirmation_expires_at).toISOString(),version:Number(o.version)}}
 async loadPayable(orderNumber:string,access:{customerId?:string;checkoutToken?:string}){const r=await sql<any>`SELECT * FROM orders.orders WHERE order_number=${orderNumber} LIMIT 1`.execute(this.db);const o=r.rows[0];if(!o)throw new DomainError('ORDER_NOT_FOUND','سفارش پیدا نشد.');if(o.customer_id){if(!access.customerId||String(o.customer_id)!==access.customerId)throw new DomainError('ORDER_NOT_FOUND','سفارش پیدا نشد.');}else{if(!access.checkoutToken)throw new DomainError('CHECKOUT_ACCESS_REQUIRED','توکن Checkout الزامی است.');await this.checkout.assertGuestAccess(this.db,String(o.checkout_id),access.checkoutToken);}return this.present(o);}
 async loadById(orderId:string){const r=await sql<any>`SELECT * FROM orders.orders WHERE id=${orderId}::uuid LIMIT 1`.execute(this.db);if(!r.rows[0])throw new DomainError('ORDER_NOT_FOUND','سفارش پیدا نشد.');return this.present(r.rows[0]);}
 async markPaymentState(ex:DatabaseExecutor,orderId:string,state:'unpaid'|'pending'|'partially_refunded'|'refund_required'|'refunded',paymentId?:string){await sql`UPDATE orders.orders SET payment_status=${state},payment_id=CASE WHEN ${state}='unpaid' THEN NULL WHEN ${paymentId??null}::uuid IS NULL THEN payment_id ELSE ${paymentId??null}::uuid END,updated_at=now() WHERE id=${orderId}::uuid`.execute(ex);}
 async markPaymentAttemptFailed(ex:DatabaseExecutor,orderId:string,paymentId:string){await sql`UPDATE orders.orders SET payment_status='unpaid',payment_id=NULL,updated_at=now() WHERE id=${orderId}::uuid AND payment_id=${paymentId}::uuid AND settlement_payment_id IS NULL`.execute(ex);}
 async claimSettlement(ex:DatabaseExecutor,orderId:string,paymentId:string){const r=await sql<any>`SELECT settlement_payment_id FROM orders.orders WHERE id=${orderId}::uuid FOR UPDATE`.execute(ex);if(!r.rows[0])throw new DomainError('ORDER_NOT_FOUND','سفارش پیدا نشد.');const current=r.rows[0].settlement_payment_id?String(r.rows[0].settlement_payment_id):null;if(current&&current!==paymentId)return{owned:false,settlement_payment_id:current};if(!current)await sql`UPDATE orders.orders SET settlement_payment_id=${paymentId}::uuid,updated_at=now() WHERE id=${orderId}::uuid`.execute(ex);return{owned:true,settlement_payment_id:paymentId};}
 async confirmPaid(ex:DatabaseExecutor,orderId:string,paymentId:string){const r=await sql<any>`SELECT * FROM orders.orders WHERE id=${orderId}::uuid FOR UPDATE`.execute(ex);const o=r.rows[0];if(!o)throw new DomainError('ORDER_NOT_FOUND','سفارش پیدا نشد.');if(o.status==='confirmed'||o.status==='completed')return{order_id:orderId,status:String(o.status),reservation_id:String(o.reservation_id),late:false};const late=o.status==='expired'||new Date(o.confirmation_expires_at).getTime()<=Date.now();if(!['pending_confirmation','expired'].includes(String(o.status)))throw new DomainError('ORDER_NOT_CONFIRMABLE','سفارش در این وضعیت قابل تایید پرداخت نیست.');await sql`UPDATE orders.orders SET status='confirmed',payment_status='paid',payment_id=${paymentId}::uuid,version=version+1,updated_at=now() WHERE id=${orderId}::uuid`.execute(ex);await sql`INSERT INTO orders.order_status_history(id,order_id,from_status,to_status,reason) VALUES(gen_random_uuid(),${orderId}::uuid,${o.status},'confirmed',${late?'late_payment_reacquired':'payment_paid'})`.execute(ex);const c=this.ctx.get()??{requestId:randomUUID(),correlationId:randomUUID(),actor:{type:'system' as const}};await this.outbox.append(ex,[{eventType:'order.confirmed.v1',eventVersion:1,aggregateType:'order',aggregateId:orderId,aggregateVersion:Number(o.version)+1,occurredAt:new Date(),payload:{order_id:orderId,order_number:String(o.order_number),payment_id:paymentId,reservation_id:String(o.reservation_id),late_payment:late}}],c);return{order_id:orderId,status:'confirmed',reservation_id:String(o.reservation_id),late};}
}
