from pathlib import Path
checks=[]
def c(name,cond): checks.append((name,bool(cond)))
repo=Path('src/modules/content/infrastructure/content.repository.ts').read_text()
svc=Path('src/modules/content/application/article-operations.service.ts').read_text()
sched=Path('apps/scheduler/scheduler-tasks.service.ts').read_text()
app=Path('apps/scheduler/app.module.ts').read_text()
ctl=Path('src/modules/content/presentation/content-admin.controller.ts').read_text()
api=Path('contracts/http/openapi.yaml').read_text()
c('claim uses SKIP LOCKED','FOR UPDATE SKIP LOCKED' in repo)
c('claim only scheduled due',"status='scheduled' AND scheduled_at IS NOT NULL AND scheduled_at<=now()" in repo)
c('publish CAS/idempotent',"AND status='scheduled' AND scheduled_at IS NOT NULL AND scheduled_at<=now()" in repo and 'version=${input.expectedAggregateVersion}' in repo)
c('system publish sets public snapshot','published_version_id=current_version_id' in repo)
c('system publish copies current slug','SELECT slug FROM content.article_versions WHERE id=current_version_id' in repo)
c('first published preserved','COALESCE(first_published_at,now())' in repo)
c('conflict precheck','scheduledPublishConflict' in repo)
c('operations summary due','scheduled_due' in repo)
c('operations summary oldest','oldest_due_seconds' in repo)
c('transition history written',"fromStatus:'scheduled',toStatus:'published'" in svc)
c('system audit written',"actorType:'system'" in svc and 'scheduled_publish' in svc)
c('outbox published event',"content.article.published.v1" in svc)
c('blocked observable','scheduled_publish_blocked' in svc and 'blocked_ids' in svc)
c('scheduler minute cron','publishScheduledContent' in sched and 'EVERY_MINUTE' in sched)
c('scheduler imports content module','ContentModule' in app)
c('operations endpoint RBAC',"@Permissions('content.view') @Get('operations/summary')" in ctl)
c('openapi operations endpoint','/admin/content/articles/operations/summary:' in api)
c('no new lifecycle status',all(x not in svc+repo for x in ["'processing'","'publish_failed'"]))
c('no provider/network dependency',all(x not in svc for x in ['fetch(','axios','HttpService']))
c('no AI/marketing implementation','ai/' not in svc.lower() and 'marketing' not in svc.lower())
failed=[n for n,v in checks if not v]
for n,v in checks: print(('PASS' if v else 'FAIL'),n)
print(f'{sum(v for _,v in checks)}/{len(checks)} PASS')
raise SystemExit(1 if failed else 0)
