from pathlib import Path
checks=[]
def ck(name,cond): checks.append((name,bool(cond)))
root=Path('.')
links=(root/'src/modules/content/application/article-internal-link.service.ts').read_text()
site=(root/'src/modules/content/application/article-sitemap.service.ts').read_text()
repo=(root/'src/modules/content/infrastructure/content.repository.ts').read_text()
seo=(root/'src/modules/content/application/article-seo.service.ts').read_text()
mod=(root/'src/modules/content/content.module.ts').read_text()
ck('internal-link-service', 'class ArticleInternalLinkService' in links)
ck('published-source-only', 'publicArticleBySlug' in links)
ck('article-path-only', 'articles\\/(' in links or '/articles/' in links)
ck('same-origin-check', 'url.origin !== baseUrl.origin' in links)
ck('self-link-detected', 'self.push' in links)
ck('broken-link-detected', 'broken.push' in links)
ck('external-ignored', 'externalIgnored' in links)
ck('dedupe-links', 'seen.has' in links)
ck('canonical-target', 'canonicalUrlForSlug' in links)
ck('sitemap-service', 'class ArticleSitemapService' in site)
ck('sitemap-bounded-limit', 'n > 1000' in site)
ck('sitemap-keyset-cursor', 'publishedAt' in site and 'base64url' in site)
ck('sitemap-canonical', 'canonicalUrlForSlug' in site)
ck('sitemap-lastmod', 'published_at.toISOString()' in site)
ck('repo-published-only', "a.status='published'" in repo and 'published_version_id IS NOT NULL' in repo)
ck('repo-keyset-order', '(a.published_at,a.id)<' in repo)
ck('seo-public-base-exported', 'async publicBaseUrl()' in seo)
ck('module-wires-links', 'ArticleInternalLinkService' in mod)
ck('module-wires-sitemap', 'ArticleSitemapService' in mod)
ck('no-catalog-sql', 'catalog.' not in links.lower() and 'catalog.' not in site.lower())
ck('no-category-tag-model', 'category_id' not in links and 'tag_id' not in links)
ck('no-sitemap-http', "@Controller('sitemap" not in (root/'src/modules/content/presentation/content-public.controller.ts').read_text())
failed=[n for n,v in checks if not v]
for n,v in checks: print(('PASS' if v else 'FAIL'), n)
print(f'A8 audit: {len(checks)-len(failed)}/{len(checks)} PASS')
raise SystemExit(1 if failed else 0)
