from pathlib import Path
root=Path(__file__).resolve().parents[1]
def read(p): return (root/p).read_text(encoding='utf-8')
checks=[]
def ck(name, cond): checks.append((name,bool(cond)))
repo=read('src/modules/content/infrastructure/content.repository.ts')
admin=read('src/modules/content/presentation/content-admin.controller.ts')
public=read('src/modules/content/application/article-public-query.service.ts')
ops=read('src/modules/content/application/article-operations.service.ts')
seo=read('src/modules/content/application/article-seo.service.ts')
links=read('src/modules/content/application/article-internal-link.service.ts')
sitemap=read('src/modules/content/application/article-sitemap.service.ts')
editorial=read('src/modules/content/application/article-editorial.service.ts')
draft=read('src/modules/content/application/article-draft.service.ts')
module=read('src/modules/content/content.module.ts')
openapi=read('contracts/http/openapi.yaml')
all_content='\n'.join(p.read_text(encoding='utf-8',errors='ignore') for p in (root/'src/modules/content').rglob('*.ts'))
ck('scheduler uses SKIP LOCKED', 'SKIP LOCKED' in repo)
ck('scheduler due guard', "status='scheduled'" in repo and 'scheduled_at<=now()' in repo.replace(' ',''))
ck('system publish event', 'content.article.published.v1' in ops or 'content.article.published.v1' in repo)
ck('scheduled publish blocked audit', 'content.article.scheduled_publish_blocked' in repo or 'content.article.scheduled_publish_blocked' in ops)
ck('public reads published snapshot', 'published_version_id' in repo and 'publicArticleBySlug' in repo)
ck('public avoids current snapshot', 'current_version_id' not in public)
ck('seo lifecycle published only', "published" in seo and 'noindex,nofollow' in seo)
ck('canonical https enforcement', 'https:' in seo)
ck('sitemap published only', 'listSitemap' in repo and "status='published'" in repo)
ck('sitemap uses canonical URL', 'canonicalUrlForSlug' in sitemap)
ck('internal links use public resolver', 'findPublishedBySlug' in links or 'public' in links.lower())
ck('admin staff only', '@StaffOnly' in admin)
ck('admin read permission', "content.view" in admin)
ck('create permission/idempotency', "content.edit" in admin and "content.article.create" in admin)
ck('edit permission/idempotency', "content.article.edit" in admin)
ck('submit review permission/idempotency', "content.article.submit_review" in admin)
ck('approve stepup/idempotency', "content.article.approve" in admin and '@RequireStepUp()' in admin)
ck('schedule stepup/idempotency', "content.article.schedule" in admin)
ck('publish stepup/idempotency', "content.article.publish" in admin)
ck('unpublish stepup/idempotency', "content.article.unpublish" in admin)
ck('archive stepup/idempotency', "content.article.archive" in admin)
ck('restore stepup/idempotency', "content.article.version.restore" in admin)
ck('openapi idempotency refs', openapi.count("#/components/parameters/IdempotencyKey") >= 9)
ck('openapi stepup tokens', openapi.count('stepUpToken') >= 6)
ck('draft service optimistic concurrency', 'version' in draft.lower())
ck('editorial lifecycle commands present', all(x in editorial for x in ['submitReview','approve','schedule','publish','unpublish','archive','restoreVersion']))
ck('content module wires admin controller', 'ContentAdminController' in module)
ck('content module wires public controller', 'ContentPublicController' in module)
ck('no catalog sql from content', 'catalog.' not in all_content.lower())
ck('no wallet term in content source', 'wallet' not in all_content.lower())
failed=[n for n,v in checks if not v]
for n,v in checks: print(('PASS' if v else 'FAIL')+': '+n)
print(f'SUMMARY {len(checks)-len(failed)}/{len(checks)} PASS')
if failed: raise SystemExit(1)
