from pathlib import Path
checks=[]
def ck(name,cond):
    checks.append((name,bool(cond)))
root=Path('.')
c=(root/'src/modules/finance/application/finance-cross-domain.consumer.ts').read_text()
pc=(root/'src/modules/finance/application/profit-calculation.service.ts').read_text()
pf=(root/'src/modules/finance/application/profit-finalization.service.ts').read_text()
fm=(root/'src/modules/finance/finance.module.ts').read_text()
wm=(root/'apps/worker/app.module.ts').read_text()
ck('consumer exists','class FinanceCrossDomainConsumer' in c)
ck('consumer registers','this.registry.register(this)' in c)
ck('consumer name','finance.cross_domain.v1' in c)
for e in ['order.created.v1','order.confirmed.v1','payment.paid.v1','payment.refunded.v1','inventory.stock.consumed.v1','inventory.return.received.v1','return.resolved.v1','procurement.landed_cost.finalized.v1']:
    ck('event '+e,e in c)
ck('final invalidation refund',"'payment.refunded.v1'" in c and 'FINAL_INVALIDATORS' in c)
ck('final invalidation inventory return',"'inventory.return.received.v1'" in c)
ck('final invalidation landed cost',"'procurement.landed_cost.finalized.v1'" in c)
ck('reverses current final','reverseInTransaction' in c and 'currentFinalProfit' in c)
ck('recalculates in same transaction','calculateInTransaction(trx' in c)
ck('direct order id resolution',"typeof p.order_id==='string'" in c)
ck('order item resolution','orders.order_items' in c)
ck('return resolution','returns.returns' in c)
ck('landed cost allocation resolution','procurement.landed_cost_allocations' in c)
ck('consumed cogs lineage resolution','inventory.cost_layer_consumptions' in c)
ck('profit calc exposes transaction method','async calculateInTransaction' in pc)
ck('profit calc wrapper preserved','this.tx.run(ex=>this.calculateInTransaction' in pc)
ck('finalization exposes reversal transaction method','async reverseInTransaction' in pf)
ck('finalization wrapper preserved','this.tx.run(ex=>this.reverseInTransaction' in pf)
ck('finance module provider wired','FinanceCrossDomainConsumer' in fm and 'providers:[' in fm)
ck('worker finance module wired','FinanceModule' in wm)
ck('no source-domain updates',not any(x in c for x in ['UPDATE orders.','UPDATE payments.','UPDATE inventory.','UPDATE procurement.','UPDATE returns.']))
ck('no source-domain deletes',not any(x in c for x in ['DELETE FROM orders.','DELETE FROM payments.','DELETE FROM inventory.','DELETE FROM procurement.','DELETE FROM returns.']))
ck('no HTTP controller in A9','Controller(' not in c)
ck('consumer uses event inbox registry','EventConsumerRegistry' in c)
ck('finance events excluded to avoid loop','finance.profit.' not in c.split('const TYPES=')[1].split('] as const')[0])
failed=[n for n,v in checks if not v]
for n,v in checks: print(('PASS' if v else 'FAIL'),n)
print(f'{len(checks)-len(failed)}/{len(checks)} PASS')
if failed: raise SystemExit(1)
