import { DomainEventCollector } from '../../../shared/kernel/domain-event';
import { DomainError } from '../../../shared/errors/domain-error';
import { ProductState } from './catalog.types';
import { optionalText, requiredText, slug } from './catalog.validation';
export interface ProductCreateInput {id:string;brandId?:string|null;primaryCategoryId:string;nameFa:string;nameEn?:string|null;slug:string;shortDescription?:string|null;description?:string|null;salesEnabled?:boolean;}
export interface ProductUpdateInput {brandId?:string|null;primaryCategoryId?:string;nameFa?:string;nameEn?:string|null;slug?:string;shortDescription?:string|null;description?:string|null;salesEnabled?:boolean;}
export class ProductAggregate extends DomainEventCollector {
 private constructor(private state:ProductState){super();}
 static create(i:ProductCreateInput){ const now=null; const p=new ProductAggregate({id:i.id,brandId:i.brandId??null,primaryCategoryId:requiredText(i.primaryCategoryId,'primary_category_id',80),nameFa:requiredText(i.nameFa,'name_fa',250),nameEn:optionalText(i.nameEn,250),slug:slug(i.slug),shortDescription:optionalText(i.shortDescription,1000),description:i.description??null,status:'draft',salesEnabled:i.salesEnabled??true,publishedAt:now,archivedAt:null,archiveReason:null,version:1}); p.emit('catalog.product.created.v1',{product_id:p.id,slug:p.state.slug}); return p; }
 static rehydrate(s:ProductState){return new ProductAggregate({...s});}
 get id(){return this.state.id;} get version(){return this.state.version;} get status(){return this.state.status;} get salesEnabled(){return this.state.salesEnabled;}
 update(i:ProductUpdateInput){ if(this.state.status==='archived')throw new DomainError('PRODUCT_ARCHIVED','محصول آرشیوشده ابتدا باید از آرشیو خارج شود.'); this.state={...this.state,brandId:i.brandId===undefined?this.state.brandId:i.brandId,primaryCategoryId:i.primaryCategoryId===undefined?this.state.primaryCategoryId:requiredText(i.primaryCategoryId,'primary_category_id',80),nameFa:i.nameFa===undefined?this.state.nameFa:requiredText(i.nameFa,'name_fa',250),nameEn:i.nameEn===undefined?this.state.nameEn:optionalText(i.nameEn,250),slug:i.slug===undefined?this.state.slug:slug(i.slug),shortDescription:i.shortDescription===undefined?this.state.shortDescription:optionalText(i.shortDescription,1000),description:i.description===undefined?this.state.description:i.description??null,salesEnabled:i.salesEnabled??this.state.salesEnabled,version:this.state.version+1}; this.emit('catalog.product.updated.v1',{product_id:this.id}); }
 publish(hasActiveVariant:boolean,hasSellablePrice:boolean){ if(this.state.status==='archived')throw new DomainError('INVALID_STATE_TRANSITION','محصول آرشیوشده قابل انتشار نیست.'); if(!hasActiveVariant)throw new DomainError('PRODUCT_VARIANT_REQUIRED','برای انتشار حداقل یک واریانت فعال لازم است.'); if(this.state.salesEnabled&&!hasSellablePrice)throw new DomainError('PRODUCT_PRICE_REQUIRED','برای محصول قابل فروش، قیمت معتبر لازم است.'); const at=new Date(); this.state={...this.state,status:'published',publishedAt:this.state.publishedAt??at,version:this.state.version+1}; this.emit('catalog.product.published.v1',{product_id:this.id,published_at:at.toISOString()}); }
 archive(reason:string){ if(this.state.status==='archived')return; const r=requiredText(reason,'reason',1000); this.state={...this.state,status:'archived',salesEnabled:false,archivedAt:new Date(),archiveReason:r,version:this.state.version+1}; this.emit('catalog.product.archived.v1',{product_id:this.id,reason:r}); }
 unarchive(){ if(this.state.status!=='archived')throw new DomainError('INVALID_STATE_TRANSITION','محصول آرشیوشده نیست.'); this.state={...this.state,status:'draft',publishedAt:null,archivedAt:null,archiveReason:null,version:this.state.version+1}; this.emit('catalog.product.unarchived.v1',{product_id:this.id}); }
 setSales(enabled:boolean){ if(this.state.status==='archived'&&enabled)throw new DomainError('PRODUCT_ARCHIVED','محصول آرشیوشده قابل فعال‌سازی فروش نیست.'); if(this.state.salesEnabled===enabled)return; this.state={...this.state,salesEnabled:enabled,version:this.state.version+1}; this.emit('catalog.product.sales_status_changed.v1',{product_id:this.id,sales_enabled:enabled}); }
 snapshot(){return {...this.state};}
 private emit(eventType:string,payload:Record<string,unknown>){this.recordEvent({eventType,eventVersion:1,aggregateType:'product',aggregateId:this.id,aggregateVersion:this.version,occurredAt:new Date(),payload});}
}
