import test from 'node:test';import assert from 'node:assert/strict';
class DomainError extends Error{constructor(code,msg){super(msg);this.code=code;}}
function whole(n,name){if(!Number.isInteger(n)||n<0)throw new DomainError('FULFILLMENT_INVALID_QUANTITY',`${name} invalid`);return n;}
function assertLineState(line){const ordered=whole(line.ordered,'ordered'),allocated=whole(line.allocated,'allocated'),picked=whole(line.picked,'picked'),shipped=whole(line.shipped,'shipped'),delivered=whole(line.delivered,'delivered');if(allocated>ordered)throw new DomainError('FULFILLMENT_ALLOCATION_EXCEEDS_ORDER','');if(picked>allocated)throw new DomainError('FULFILLMENT_PICK_EXCEEDS_ALLOCATION','');if(shipped>picked)throw new DomainError('FULFILLMENT_SHIP_EXCEEDS_PICK','');if(delivered>shipped)throw new DomainError('FULFILLMENT_DELIVERY_EXCEEDS_SHIPMENT','');}
function calculateFulfillmentStatus(lines,preparationStarted,cancelled=false){if(cancelled)return'cancelled';if(lines.length===0)return'unfulfilled';for(const l of lines)assertLineState(l);const total=lines.reduce((a,x)=>a+x.ordered,0),allocated=lines.reduce((a,x)=>a+x.allocated,0),shipped=lines.reduce((a,x)=>a+x.shipped,0),delivered=lines.reduce((a,x)=>a+x.delivered,0);if(delivered===total&&total>0)return'delivered';if(delivered>0)return'partially_delivered';if(shipped===total&&total>0)return'shipped';if(shipped>0)return'partially_shipped';if(preparationStarted&&allocated===total&&total>0)return'preparing';if(allocated===total&&total>0)return'allocated';if(allocated>0)return'partially_allocated';return'unfulfilled';}
function validatePickChange(current,delta,allocationQuantity){whole(current,'c');whole(delta,'d');whole(allocationQuantity,'q');if(delta<=0)throw new DomainError('FULFILLMENT_PICK_QUANTITY_INVALID','');const next=current+delta;if(next>allocationQuantity)throw new DomainError('FULFILLMENT_PICK_EXCEEDS_ALLOCATION','');return next;}
function validateUnpickChange(current,delta,shipped){whole(current,'c');whole(delta,'d');whole(shipped,'s');if(delta<=0)throw new DomainError('FULFILLMENT_UNPICK_QUANTITY_INVALID','');const next=current-delta;if(next<0)throw new DomainError('FULFILLMENT_UNPICK_EXCEEDS_PICK','');if(next<shipped)throw new DomainError('FULFILLMENT_UNPICK_BELOW_SHIPPED','');return next;}
const L=(o,a,p,s,d=0)=>({orderItemId:'x',ordered:o,allocated:a,picked:p,shipped:s,delivered:d});
test('state unfulfilled/partial/allocated/preparing',()=>{assert.equal(calculateFulfillmentStatus([L(2,0,0,0)],false),'unfulfilled');assert.equal(calculateFulfillmentStatus([L(2,1,0,0)],false),'partially_allocated');assert.equal(calculateFulfillmentStatus([L(2,2,0,0)],false),'allocated');assert.equal(calculateFulfillmentStatus([L(2,2,1,0)],true),'preparing');});
test('state shipping and delivery projections',()=>{assert.equal(calculateFulfillmentStatus([L(2,2,2,1)],true),'partially_shipped');assert.equal(calculateFulfillmentStatus([L(2,2,2,2)],true),'shipped');assert.equal(calculateFulfillmentStatus([L(2,2,2,2,1)],true),'partially_delivered');assert.equal(calculateFulfillmentStatus([L(2,2,2,2,2)],true),'delivered');});
test('invalid hierarchy fails closed',()=>{assert.throws(()=>calculateFulfillmentStatus([L(2,3,0,0)],false),e=>e.code==='FULFILLMENT_ALLOCATION_EXCEEDS_ORDER');assert.throws(()=>calculateFulfillmentStatus([L(2,2,3,0)],false),e=>e.code==='FULFILLMENT_PICK_EXCEEDS_ALLOCATION');assert.throws(()=>calculateFulfillmentStatus([L(2,2,1,2)],false),e=>e.code==='FULFILLMENT_SHIP_EXCEEDS_PICK');});
test('partial pick bounds',()=>{assert.equal(validatePickChange(1,2,5),3);assert.throws(()=>validatePickChange(4,2,5),e=>e.code==='FULFILLMENT_PICK_EXCEEDS_ALLOCATION');});
test('unpick cannot cross shipped floor',()=>{assert.equal(validateUnpickChange(5,2,2),3);assert.throws(()=>validateUnpickChange(3,2,2),e=>e.code==='FULFILLMENT_UNPICK_BELOW_SHIPPED');});
