import { Inject,Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { TransactionManager } from '../../../platform/database/transaction-manager';
import { RequestContextStore } from '../../../platform/request-context/request-context.store';
import { OutboxWriter } from '../../../platform/outbox/outbox-writer';
import { DomainError } from '../../../shared/errors/domain-error';
import { FulfillmentRepository } from '../infrastructure/fulfillment.repository';
import { calculateFulfillmentStatus,validatePickChange,validateUnpickChange } from '../domain/fulfillment.state';
import { fulfillmentEvent } from '../domain/fulfillment.events';
import { INVENTORY_FULFILLMENT_PORT,InventoryFulfillmentPort } from '../../inventory/application/ports/inventory-fulfillment.port';
import { ORDER_FULFILLMENT_PORT,OrderFulfillmentPort,OrderFulfillmentSnapshot } from '../../orders/application/ports/order-fulfillment.port';

@Injectable()
export class FulfillmentService{
  constructor(private readonly tx:TransactionManager,private readonly repo:FulfillmentRepository,private readonly ctx:RequestContextStore,private readonly outbox:OutboxWriter,@Inject(INVENTORY_FULFILLMENT_PORT) private readonly inventory:InventoryFulfillmentPort,@Inject(ORDER_FULFILLMENT_PORT) private readonly orders:OrderFulfillmentPort){}
  list(){return this.repo.list();}
  async get(orderId:string){const summary=await this.repo.orderSummary(orderId);if(summary)return summary;const order=await this.orders.getForFulfillment(this.repo.db(),orderId,false);if(!order)throw new DomainError('ORDER_NOT_FOUND','سفارش پیدا نشد.');return{order_id:order.id,status:'unfulfilled',preparation_started_at:null,completed_at:null,lines:order.items.map(x=>({orderItemId:x.id,ordered:x.quantity,allocated:0,picked:0,shipped:0,delivered:0})),allocations:[]};}

  private context(){return this.ctx.get()??{requestId:randomUUID(),correlationId:randomUUID(),actor:{type:'system' as const}};}
  private assertEligible(o:OrderFulfillmentSnapshot){if(o.status!=='confirmed')throw new DomainError('FULFILLMENT_ORDER_NOT_CONFIRMED','فقط سفارش تأییدشده قابل آماده‌سازی است.');if(!o.settlementPaymentId||!['paid','partially_refunded'].includes(o.paymentStatus))throw new DomainError('FULFILLMENT_PAYMENT_NOT_SETTLED','پرداخت نهایی سفارش تأیید نشده است.');}
  async recalculateInTransaction(ex:any,orderId:string,preparationStarted?:boolean){const current=await this.repo.ensureFulfillment(ex,orderId);const lines=await this.repo.lineStates(ex,orderId);const started=preparationStarted??Boolean(current?.preparation_started_at);const status=calculateFulfillmentStatus(lines,started,String(current?.status)==='cancelled');if(status!==current?.status||started!==Boolean(current?.preparation_started_at)){return this.repo.setStatus(ex,orderId,status,started);}return current;}

  async allocate(orderId:string,input:{strategy:'single_warehouse_preferred'|'manual';allocations?:{order_item_id:string;warehouse_id:string;quantity:number}[]}){
    if(!['single_warehouse_preferred','manual'].includes(input?.strategy))throw new DomainError('FULFILLMENT_STRATEGY_INVALID','راهبرد تخصیص معتبر نیست.');
    const ctx=this.context();return this.tx.run(async ex=>{
      const order=await this.orders.getForFulfillment(ex,orderId,true);if(!order)throw new DomainError('ORDER_NOT_FOUND','سفارش پیدا نشد.');this.assertEligible(order);if(!order.reservationId)throw new DomainError('FULFILLMENT_RESERVATION_REQUIRED','سفارش فاقد تعهد رزرو است.');await this.repo.ensureFulfillment(ex,orderId);
      const allocations=input.strategy==='single_warehouse_preferred'?(await this.inventory.planSingleWarehousePreferred(ex,{reservationId:order.reservationId,items:order.items.map(x=>({orderItemId:x.id,variantId:x.variantId,quantity:x.quantity}))})).map(x=>({order_item_id:x.orderItemId,warehouse_id:x.warehouseId,quantity:x.quantity})):input.allocations;if(!allocations?.length)throw new DomainError('FULFILLMENT_ALLOCATIONS_REQUIRED','برای تخصیص حداقل یک ردیف لازم است.');
      const byId=new Map(order.items.map(x=>[x.id,x]));const seen=new Set<string>();const created=[] as any[];
      for(const x of allocations){const oi=byId.get(x.order_item_id);if(!oi)throw new DomainError('FULFILLMENT_ORDER_ITEM_INVALID','قلم سفارش متعلق به این سفارش نیست.');if(!Number.isInteger(x.quantity)||x.quantity<=0)throw new DomainError('FULFILLMENT_ALLOCATION_QUANTITY_INVALID','تعداد تخصیص نامعتبر است.');const key=`${x.order_item_id}:${x.warehouse_id}`;if(seen.has(key))throw new DomainError('FULFILLMENT_DUPLICATE_ALLOCATION_LINE','انبار برای این قلم سفارش تکراری است.');seen.add(key);const a=await this.inventory.allocate(ex,{orderItemId:oi.id,warehouseId:x.warehouse_id,variantId:oi.variantId,quantity:x.quantity,reservationId:order.reservationId});await this.repo.upsertProgress(ex,{orderId,orderItemId:oi.id,allocationId:a.id});created.push(a);}
      const f=await this.recalculateInTransaction(ex,orderId);await this.outbox.append(ex,[fulfillmentEvent('fulfillment.allocated.v1',String(f.id),Number(f.version),{fulfillment_id:String(f.id),order_id:orderId,allocation_ids:created.map(x=>x.id),status:f.status})],ctx);return{order_id:orderId,status:f.status,allocations:created};
    });
  }

  async startPreparation(orderId:string,input:{note?:string|null}={}){const note=input.note==null?null:String(input.note).trim();if(note&&note.length>2000)throw new DomainError('VALIDATION_ERROR','یادداشت آماده‌سازی بیش از حد مجاز است.');const ctx=this.context();return this.tx.run(async ex=>{const o=await this.orders.getForFulfillment(ex,orderId,true);if(!o)throw new DomainError('ORDER_NOT_FOUND','سفارش پیدا نشد.');this.assertEligible(o);const f0=await this.repo.ensureFulfillment(ex,orderId);const lines=await this.repo.lineStates(ex,orderId);if(lines.length===0||lines.some(x=>x.allocated!==x.ordered))throw new DomainError('FULFILLMENT_NOT_FULLY_ALLOCATED','شروع آماده‌سازی نیازمند تخصیص کامل سفارش است.');if(f0.status==='cancelled')throw new DomainError('INVALID_STATE_TRANSITION','Fulfillment لغوشده قابل آماده‌سازی نیست.');const f=await this.recalculateInTransaction(ex,orderId,true);await this.outbox.append(ex,[fulfillmentEvent('fulfillment.preparation_started.v1',String(f.id),Number(f.version),{fulfillment_id:String(f.id),order_id:orderId,note,status:f.status})],ctx);return{order_id:orderId,status:f.status,preparation_started_at:f.preparation_started_at};});}

  async pick(allocationId:string,input:{picked_quantity:number;note?:string|null}){const delta=Number(input?.picked_quantity);const note=input.note==null?null:String(input.note).trim();if(note&&note.length>1000)throw new DomainError('VALIDATION_ERROR','یادداشت Pick بیش از حد مجاز است.');const ctx=this.context();return this.tx.run(async ex=>{const p=await this.repo.progress(ex,allocationId,true);if(!p)throw new DomainError('FULFILLMENT_ALLOCATION_NOT_FOUND','تخصیص Fulfillment پیدا نشد.');const next=validatePickChange(p.pickedQuantity,delta,p.quantity);if(p.inventoryStatus==='released'||p.inventoryStatus==='shipped')throw new DomainError('INVALID_STATE_TRANSITION','این تخصیص قابل Pick نیست.');await this.repo.setPickedQuantity(ex,allocationId,next);if(next===p.quantity&&p.inventoryStatus==='allocated')await this.inventory.markPicked(ex,allocationId);const f=await this.recalculateInTransaction(ex,p.orderId);await this.outbox.append(ex,[fulfillmentEvent('fulfillment.picked.v1',String(f.id),Number(f.version),{fulfillment_id:String(f.id),order_id:p.orderId,allocation_id:allocationId,picked_quantity:delta,total_picked_quantity:next,note,status:f.status})],ctx);return{allocation_id:allocationId,picked_quantity:next,status:f.status};});}

  async unpick(allocationId:string,input:{quantity:number;reason:string}){const delta=Number(input?.quantity),reason=String(input?.reason??'').trim();if(!reason||reason.length>2000)throw new DomainError('VALIDATION_ERROR','دلیل Unpick معتبر نیست.');const ctx=this.context();return this.tx.run(async ex=>{const p=await this.repo.progress(ex,allocationId,true);if(!p)throw new DomainError('FULFILLMENT_ALLOCATION_NOT_FOUND','تخصیص Fulfillment پیدا نشد.');if(p.inventoryStatus==='released'||p.inventoryStatus==='shipped')throw new DomainError('INVALID_STATE_TRANSITION','این تخصیص قابل Unpick نیست.');const next=validateUnpickChange(p.pickedQuantity,delta,p.shippedQuantity);await this.repo.setPickedQuantity(ex,allocationId,next);if(p.inventoryStatus==='picked'&&p.shippedQuantity===0&&next<p.quantity)await this.inventory.markAllocated(ex,allocationId);const f=await this.recalculateInTransaction(ex,p.orderId);await this.outbox.append(ex,[fulfillmentEvent('fulfillment.unpicked.v1',String(f.id),Number(f.version),{fulfillment_id:String(f.id),order_id:p.orderId,allocation_id:allocationId,quantity:delta,total_picked_quantity:next,reason,status:f.status})],ctx);return{allocation_id:allocationId,picked_quantity:next,status:f.status};});}
}
