import { Injectable } from '@nestjs/common';
import { sql } from 'kysely';
import { DatabaseExecutor,TransactionManager } from '../../../platform/database/transaction-manager';
import { AllocationState,FulfillmentLineState,FulfillmentStatus } from '../domain/fulfillment.types';
import { DomainError } from '../../../shared/errors/domain-error';

@Injectable()
export class FulfillmentRepository{
  constructor(private readonly tx:TransactionManager){}
  db(){return this.tx.readonly();}
  async fulfillment(ex:DatabaseExecutor,orderId:string,lock=false){const r=await sql<any>`SELECT * FROM fulfillment.fulfillments WHERE order_id=${orderId}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]??null;}
  async ensureFulfillment(ex:DatabaseExecutor,orderId:string){await sql`INSERT INTO fulfillment.fulfillments(id,order_id,status) VALUES(gen_random_uuid(),${orderId}::uuid,'unfulfilled') ON CONFLICT(order_id) DO NOTHING`.execute(ex);return this.fulfillment(ex,orderId,true);}
  async setStatus(ex:DatabaseExecutor,orderId:string,status:FulfillmentStatus,preparationStarted:boolean){const r=await sql<any>`UPDATE fulfillment.fulfillments SET status=${status},preparation_started_at=CASE WHEN ${preparationStarted} AND preparation_started_at IS NULL THEN now() ELSE preparation_started_at END,completed_at=CASE WHEN ${status}='delivered' THEN COALESCE(completed_at,now()) ELSE completed_at END,version=version+1,updated_at=now() WHERE order_id=${orderId}::uuid RETURNING *`.execute(ex);return r.rows[0]??null;}
  async lineStates(ex:DatabaseExecutor,orderId:string):Promise<FulfillmentLineState[]>{const r=await sql<any>`SELECT oi.id order_item_id,oi.quantity ordered,COALESCE(sum(CASE WHEN a.status<>'released' THEN a.quantity ELSE 0 END),0)::int allocated,COALESCE(sum(fp.picked_quantity),0)::int picked,COALESCE(sum(fp.shipped_quantity),0)::int shipped,COALESCE((SELECT sum(si.quantity)::int FROM fulfillment.shipment_items si JOIN fulfillment.shipments s ON s.id=si.shipment_id WHERE si.order_item_id=oi.id AND s.status='delivered'),0)::int delivered FROM orders.order_items oi LEFT JOIN inventory.allocations a ON a.order_item_id=oi.id LEFT JOIN fulfillment.allocation_progress fp ON fp.allocation_id=a.id WHERE oi.order_id=${orderId}::uuid GROUP BY oi.id,oi.quantity ORDER BY oi.id`.execute(ex);return r.rows.map((x:any)=>({orderItemId:String(x.order_item_id),ordered:Number(x.ordered),allocated:Number(x.allocated),picked:Number(x.picked),shipped:Number(x.shipped),delivered:Number(x.delivered)}));}
  async progress(ex:DatabaseExecutor,allocationId:string,lock=false):Promise<AllocationState|null>{const r=await sql<any>`SELECT fp.*,a.warehouse_id,a.variant_id,a.quantity,a.status inventory_status FROM fulfillment.allocation_progress fp JOIN inventory.allocations a ON a.id=fp.allocation_id WHERE fp.allocation_id=${allocationId}::uuid ${sql.raw(lock?'FOR UPDATE OF fp':'')}`.execute(ex);const x=r.rows[0];return x?{id:String(x.allocation_id),orderId:String(x.order_id),orderItemId:String(x.order_item_id),warehouseId:String(x.warehouse_id),variantId:String(x.variant_id),quantity:Number(x.quantity),inventoryStatus:x.inventory_status,pickedQuantity:Number(x.picked_quantity),shippedQuantity:Number(x.shipped_quantity)}:null;}
  async upsertProgress(ex:DatabaseExecutor,input:{orderId:string;orderItemId:string;allocationId:string}){await sql`INSERT INTO fulfillment.allocation_progress(id,order_id,order_item_id,allocation_id,picked_quantity,shipped_quantity) VALUES(gen_random_uuid(),${input.orderId}::uuid,${input.orderItemId}::uuid,${input.allocationId}::uuid,0,0) ON CONFLICT(allocation_id) DO NOTHING`.execute(ex);}
  async setPickedQuantity(ex:DatabaseExecutor,allocationId:string,quantity:number){await sql`UPDATE fulfillment.allocation_progress SET picked_quantity=${quantity},version=version+1,updated_at=now() WHERE allocation_id=${allocationId}::uuid`.execute(ex);}
  async listOrderAllocations(ex:DatabaseExecutor,orderId:string){const r=await sql<any>`SELECT fp.*,a.warehouse_id,a.variant_id,a.quantity,a.status inventory_status FROM fulfillment.allocation_progress fp JOIN inventory.allocations a ON a.id=fp.allocation_id WHERE fp.order_id=${orderId}::uuid ORDER BY fp.order_item_id,a.warehouse_id,a.id`.execute(ex);return r.rows;}
  async orderSummary(orderId:string){const db=this.db();const f=await this.fulfillment(db,orderId,false);if(!f)return null;const lines=await this.lineStates(db,orderId);const allocations=await this.listOrderAllocations(db,orderId);return{...f,lines,allocations};}
  async list(){const r=await sql<any>`SELECT f.id,o.id order_id,o.order_number,COALESCE(f.status,'unfulfilled') status,f.preparation_started_at,f.completed_at,COALESCE(f.updated_at,o.updated_at) updated_at,o.created_at order_created_at FROM orders.orders o LEFT JOIN fulfillment.fulfillments f ON f.order_id=o.id WHERE o.status IN ('confirmed','completed') AND o.settlement_payment_id IS NOT NULL AND o.payment_status IN ('paid','partially_refunded') ORDER BY COALESCE(f.updated_at,o.updated_at) DESC,o.id DESC LIMIT 500`.execute(this.db());return r.rows;}
async carrier(ex:DatabaseExecutor,id:string){const r=await sql<any>`SELECT * FROM fulfillment.carrier_providers WHERE id=${id}::uuid AND is_active=true`.execute(ex);return r.rows[0]??null;}
async shipment(ex:DatabaseExecutor,id:string,lock=false){const r=await sql<any>`SELECT * FROM fulfillment.shipments WHERE id=${id}::uuid ${sql.raw(lock?'FOR UPDATE':'')}`.execute(ex);return r.rows[0]??null;}
async shipmentView(id:string){const sh=await this.shipment(this.db(),id,false);if(!sh)return null;const items=await sql<any>`SELECT si.*,a.warehouse_id,a.variant_id FROM fulfillment.shipment_items si JOIN inventory.allocations a ON a.id=si.allocation_id WHERE si.shipment_id=${id}::uuid ORDER BY si.order_item_id,si.allocation_id`.execute(this.db());const tracking=await sql<any>`SELECT provider_status,normalized_status,occurred_at,created_at FROM fulfillment.tracking_events WHERE shipment_id=${id}::uuid ORDER BY occurred_at,id`.execute(this.db());return{...sh,items:items.rows,tracking:tracking.rows};}
async listShipments(){const r=await sql<any>`SELECT s.*,o.order_number FROM fulfillment.shipments s JOIN orders.orders o ON o.id=s.order_id ORDER BY s.created_at DESC,s.id DESC LIMIT 500`.execute(this.db());return r.rows;}
async insertShipment(ex:DatabaseExecutor,i:{id:string;orderId:string;warehouseId:string;carrierProviderId?:string|null;providerKey?:string|null;shippingMethod:string}){await sql`INSERT INTO fulfillment.shipments(id,order_id,warehouse_id,carrier_provider_id,provider_key,shipping_method,status) VALUES(${i.id}::uuid,${i.orderId}::uuid,${i.warehouseId}::uuid,${i.carrierProviderId??null}::uuid,${i.providerKey??null},${i.shippingMethod},'draft')`.execute(ex);}
async insertShipmentItem(ex:DatabaseExecutor,i:{id:string;shipmentId:string;allocationId:string;orderItemId:string;quantity:number}){await sql`INSERT INTO fulfillment.shipment_items(id,shipment_id,allocation_id,order_item_id,quantity) VALUES(${i.id}::uuid,${i.shipmentId}::uuid,${i.allocationId}::uuid,${i.orderItemId}::uuid,${i.quantity})`.execute(ex);}
async shipmentCandidates(ex:DatabaseExecutor,orderId:string,warehouseId:string,orderItemId:string){
  await sql`SELECT fp.allocation_id FROM fulfillment.allocation_progress fp JOIN inventory.allocations a ON a.id=fp.allocation_id WHERE fp.order_id=${orderId}::uuid AND fp.order_item_id=${orderItemId}::uuid AND a.warehouse_id=${warehouseId}::uuid ORDER BY fp.allocation_id FOR UPDATE OF fp`.execute(ex);
  const r=await sql<any>`SELECT fp.allocation_id,fp.order_id,fp.order_item_id,fp.picked_quantity,fp.shipped_quantity,a.quantity,a.status inventory_status,
    GREATEST(fp.picked_quantity-fp.shipped_quantity-COALESCE((SELECT sum(si.quantity)::int FROM fulfillment.shipment_items si JOIN fulfillment.shipments s ON s.id=si.shipment_id WHERE si.allocation_id=fp.allocation_id AND s.status IN ('draft','ready')),0),0)::int available_quantity
    FROM fulfillment.allocation_progress fp JOIN inventory.allocations a ON a.id=fp.allocation_id
    WHERE fp.order_id=${orderId}::uuid AND fp.order_item_id=${orderItemId}::uuid AND a.warehouse_id=${warehouseId}::uuid
    ORDER BY fp.allocation_id`.execute(ex);return r.rows;
}
async shipmentItemsForHandover(ex:DatabaseExecutor,shipmentId:string){const r=await sql<any>`SELECT si.*,fp.picked_quantity,fp.shipped_quantity,a.quantity allocation_quantity,a.status inventory_status FROM fulfillment.shipment_items si JOIN fulfillment.allocation_progress fp ON fp.allocation_id=si.allocation_id JOIN inventory.allocations a ON a.id=si.allocation_id WHERE si.shipment_id=${shipmentId}::uuid ORDER BY si.allocation_id FOR UPDATE OF fp`.execute(ex);return r.rows;}
async addShippedQuantity(ex:DatabaseExecutor,allocationId:string,q:number){const r=await sql<any>`UPDATE fulfillment.allocation_progress SET shipped_quantity=shipped_quantity+${q},version=version+1,updated_at=now() WHERE allocation_id=${allocationId}::uuid AND shipped_quantity+${q}<=picked_quantity RETURNING *`.execute(ex);if(!r.rows[0])throw new DomainError('FULFILLMENT_SHIPPED_QUANTITY_CONFLICT','مقدار ارسال با Pick ثبت‌شده سازگار نیست.');return r.rows[0];}
async setShipmentState(ex:DatabaseExecutor,id:string,status:string,reason?:string|null){const r=await sql<any>`UPDATE fulfillment.shipments SET status=${status},ready_at=CASE WHEN ${status}='ready' THEN COALESCE(ready_at,now()) ELSE ready_at END,handed_over_at=CASE WHEN ${status}='handed_over' THEN COALESCE(handed_over_at,now()) ELSE handed_over_at END,delivered_at=CASE WHEN ${status}='delivered' THEN COALESCE(delivered_at,now()) ELSE delivered_at END,cancelled_at=CASE WHEN ${status}='cancelled' THEN COALESCE(cancelled_at,now()) ELSE cancelled_at END,cancel_reason=CASE WHEN ${status}='cancelled' THEN ${reason??null} ELSE cancel_reason END,version=version+1,updated_at=now() WHERE id=${id}::uuid RETURNING *`.execute(ex);return r.rows[0]??null;}
async shipmentByTracking(ex:DatabaseExecutor,providerKey:string,trackingNumber:string,lock=false){const r=await sql<any>`SELECT * FROM fulfillment.shipments WHERE provider_key=${providerKey} AND tracking_number=${trackingNumber} AND status<>'cancelled' ${sql.raw(lock?'FOR UPDATE':'')} LIMIT 1`.execute(ex);return r.rows[0]??null;}
async insertTrackingEvent(ex:DatabaseExecutor,i:{id:string;shipmentId:string;providerKey:string;externalEventId?:string|null;trackingNumber:string;providerStatus:string;normalizedStatus:string;occurredAt:Date;payloadHash:string;payload:Record<string,unknown>}){await sql`INSERT INTO fulfillment.tracking_events(id,shipment_id,provider_key,external_event_id,tracking_number,provider_status,normalized_status,occurred_at,payload_hash,payload) VALUES(${i.id}::uuid,${i.shipmentId}::uuid,${i.providerKey},${i.externalEventId??null},${i.trackingNumber},${i.providerStatus},${i.normalizedStatus},${i.occurredAt},${i.payloadHash},${JSON.stringify(i.payload)}::jsonb) ON CONFLICT DO NOTHING`.execute(ex);}
async registerWebhook(ex:DatabaseExecutor,i:{id:string;providerKey:string;externalEventId:string;trackingNumber:string;payloadHash:string}){const r=await sql<any>`INSERT INTO fulfillment.shipping_webhook_inbox(id,provider_key,external_event_id,tracking_number,payload_hash,status) VALUES(${i.id}::uuid,${i.providerKey},${i.externalEventId},${i.trackingNumber},${i.payloadHash},'received') ON CONFLICT(provider_key,external_event_id) DO UPDATE SET external_event_id=EXCLUDED.external_event_id RETURNING *`.execute(ex);return r.rows[0];}
async markWebhook(ex:DatabaseExecutor,providerKey:string,eventId:string,status:'processed'|'failed',shipmentId?:string|null,errorCode?:string|null){await sql`UPDATE fulfillment.shipping_webhook_inbox SET status=${status},shipment_id=${shipmentId??null}::uuid,attempt_count=attempt_count+1,last_error_code=${errorCode??null},processed_at=CASE WHEN ${status}='processed' THEN now() ELSE processed_at END,updated_at=now() WHERE provider_key=${providerKey} AND external_event_id=${eventId}`.execute(ex);}

}
