import { Inject, Injectable } from '@nestjs/common';
import { Kysely, sql } from 'kysely';
import { KYSELY_DB } from '../../../platform/database/database.tokens';
import type { DatabaseSchema } from '../../../platform/database/database.types';
import type { DatabaseExecutor } from '../../../platform/database/transaction-manager';
import { DomainError } from '../../../shared/errors/domain-error';

type ProcurementItemsAggregate = Record<string,unknown> & { items: Record<string,unknown>[] };
type ProcurementAllocationsAggregate = Record<string,unknown> & { allocations: Record<string,unknown>[] };

@Injectable()
export class ProcurementRepository{
 constructor(@Inject(KYSELY_DB) private readonly db:Kysely<DatabaseSchema>){}
 async nextNumber(ex:DatabaseExecutor,kind:'PR'|'PO'|'GR'|'LC'|'PRT'){const seq={PR:'purchase_request_number_seq',PO:'purchase_order_number_seq',GR:'goods_receipt_number_seq',LC:'landed_cost_number_seq',PRT:'purchase_return_number_seq'}[kind];const r=await sql<{n:number}>`SELECT nextval(${sql.lit('procurement.'+seq)}::regclass)::bigint AS n`.execute(ex);const row=r.rows[0];if(!row)throw new DomainError('SEQUENCE_VALUE_MISSING','شماره ترتیبی تولید نشد.');return `${kind}-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${String(row.n).padStart(6,'0')}`;}
 async suppliers(){return (await sql<Record<string,unknown>>`SELECT * FROM procurement.suppliers ORDER BY name_fa`.execute(this.db)).rows;}
 async supplier(id:string){return (await sql<Record<string,unknown>>`SELECT * FROM procurement.suppliers WHERE id=${id}::uuid`.execute(this.db)).rows[0]??null;}
 async supplierForUpdate(ex:DatabaseExecutor,id:string){return (await sql<Record<string,unknown>>`SELECT * FROM procurement.suppliers WHERE id=${id}::uuid FOR UPDATE`.execute(ex)).rows[0]??null;}
 async createSupplier(ex:DatabaseExecutor,i:{id:string;code:string;name_fa:string;legal_name?:string;national_id?:string;mobile?:string;phone?:string;email?:string;payment_terms_days:number;notes?:string}){await sql`INSERT INTO procurement.suppliers(id,code,name_fa,legal_name,national_id,mobile,phone,email,payment_terms_days,notes) VALUES(${i.id}::uuid,${i.code},${i.name_fa},${i.legal_name??null},${i.national_id??null},${i.mobile??null},${i.phone??null},${i.email??null},${i.payment_terms_days},${i.notes??null})`.execute(ex);}
 async updateSupplier(ex:DatabaseExecutor,id:string,i:Record<string,unknown>,expected:number){const r=await sql`UPDATE procurement.suppliers SET name_fa=COALESCE(${i.name_fa??null}::text,name_fa),legal_name=COALESCE(${i.legal_name??null}::text,legal_name),national_id=COALESCE(${i.national_id??null}::text,national_id),mobile=COALESCE(${i.mobile??null}::text,mobile),phone=COALESCE(${i.phone??null}::text,phone),email=COALESCE(${i.email??null}::text,email),payment_terms_days=COALESCE(${i.payment_terms_days??null}::int,payment_terms_days),notes=COALESCE(${i.notes??null}::text,notes),version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','تامین‌کننده همزمان تغییر کرده است.');}
 async setSupplierStatus(ex:DatabaseExecutor,id:string,status:string,expected:number){const r=await sql`UPDATE procurement.suppliers SET status=${status},version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','تامین‌کننده همزمان تغییر کرده است.');}

 async purchaseRequests(allowed:string[]|null){return (await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_requests WHERE (${allowed}::uuid[] IS NULL OR warehouse_id=ANY(${allowed}::uuid[])) ORDER BY created_at DESC LIMIT 500`.execute(this.db)).rows;}
 async purchaseRequest(id:string):Promise<ProcurementItemsAggregate|null>{const h=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_requests WHERE id=${id}::uuid`.execute(this.db)).rows[0];if(!h)return null;const items=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_request_items WHERE purchase_request_id=${id}::uuid ORDER BY variant_id`.execute(this.db)).rows;return {...h,items};}
 async purchaseRequestForUpdate(ex:DatabaseExecutor,id:string):Promise<ProcurementItemsAggregate|null>{const h=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_requests WHERE id=${id}::uuid FOR UPDATE`.execute(ex)).rows[0];if(!h)return null;const items=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_request_items WHERE purchase_request_id=${id}::uuid ORDER BY variant_id`.execute(ex)).rows;return {...h,items};}
 async createPurchaseRequest(ex:DatabaseExecutor,i:{id:string;number:string;warehouseId:string;requestedBy?:string;reason?:string;items:Array<{id:string;variant_id:string;quantity:number;note?:string}>}){await sql`INSERT INTO procurement.purchase_requests(id,request_number,warehouse_id,requested_by,reason) VALUES(${i.id}::uuid,${i.number},${i.warehouseId}::uuid,${i.requestedBy??null}::uuid,${i.reason??null})`.execute(ex);for(const x of i.items)await sql`INSERT INTO procurement.purchase_request_items(id,purchase_request_id,variant_id,requested_quantity,note) VALUES(${x.id}::uuid,${i.id}::uuid,${x.variant_id}::uuid,${x.quantity},${x.note??null})`.execute(ex);}
 async updateRequestStatus(ex:DatabaseExecutor,id:string,status:string,expected:number,actorId?:string,reason?:string){const r=await sql`UPDATE procurement.purchase_requests SET status=${status},approved_by=CASE WHEN ${status}='approved' THEN ${actorId??null}::uuid ELSE approved_by END,reason=COALESCE(${reason??null},reason),submitted_at=CASE WHEN ${status}='submitted' THEN now() ELSE submitted_at END,approved_at=CASE WHEN ${status}='approved' THEN now() ELSE approved_at END,version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','درخواست خرید همزمان تغییر کرده است.');}

 async replacePurchaseRequestDraft(ex:DatabaseExecutor,id:string,input:{reason?:string;items?:Array<{id:string;variant_id:string;quantity:number;note?:string}>},expected:number){const r=await sql`UPDATE procurement.purchase_requests SET reason=COALESCE(${input.reason??null},reason),version=version+1,updated_at=now() WHERE id=${id}::uuid AND status='draft' AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','درخواست خرید قابل ویرایش نیست.');if(input.items){await sql`DELETE FROM procurement.purchase_request_items WHERE purchase_request_id=${id}::uuid`.execute(ex);for(const x of input.items)await sql`INSERT INTO procurement.purchase_request_items(id,purchase_request_id,variant_id,requested_quantity,note) VALUES(${x.id}::uuid,${id}::uuid,${x.variant_id}::uuid,${x.quantity},${x.note??null})`.execute(ex);}}
 async replacePurchaseOrderDraft(ex:DatabaseExecutor,id:string,input:{expectedAt?:string;items?:Array<{id:string;variant_id:string;quantity:number;unit_cost_toman:number;discount_toman:number;tax_toman:number}>},expected:number){const current=await this.purchaseOrderForUpdate(ex,id);if(!current||String(current.status)!=='draft'||Number(current.version)!==expected)throw new DomainError('VERSION_CONFLICT','سفارش خرید قابل ویرایش نیست.');let subtotal=Number(current.subtotal_toman),discount=Number(current.discount_toman),tax=Number(current.total_toman)-Number(current.subtotal_toman)+Number(current.discount_toman)-Number(current.additional_cost_toman);if(input.items){subtotal=input.items.reduce((sum,x)=>sum+x.quantity*x.unit_cost_toman,0);discount=input.items.reduce((sum,x)=>sum+x.discount_toman,0);tax=input.items.reduce((sum,x)=>sum+x.tax_toman,0);await sql`DELETE FROM procurement.purchase_order_items WHERE purchase_order_id=${id}::uuid`.execute(ex);for(const x of input.items)await sql`INSERT INTO procurement.purchase_order_items(id,purchase_order_id,variant_id,ordered_quantity,unit_cost_toman,discount_toman,tax_toman) VALUES(${x.id}::uuid,${id}::uuid,${x.variant_id}::uuid,${x.quantity},${x.unit_cost_toman},${x.discount_toman},${x.tax_toman})`.execute(ex);}await sql`UPDATE procurement.purchase_orders SET expected_at=COALESCE(${input.expectedAt??null}::timestamptz,expected_at),subtotal_toman=${subtotal},discount_toman=${discount},total_toman=${subtotal-discount+tax+Number(current.additional_cost_toman)},version=version+1,updated_at=now() WHERE id=${id}::uuid`.execute(ex);}
 async replaceReceiptDraft(ex:DatabaseExecutor,id:string,items:Array<{id:string;po_item_id?:string;variant_id:string;received:number;accepted:number;quarantine:number;rejected:number;unit_cost_toman:number}>,expected:number){const r=await sql`UPDATE procurement.goods_receipts SET version=version+1,updated_at=now() WHERE id=${id}::uuid AND status='draft' AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','رسید کالا قابل ویرایش نیست.');await sql`DELETE FROM procurement.goods_receipt_items WHERE goods_receipt_id=${id}::uuid`.execute(ex);for(const x of items)await sql`INSERT INTO procurement.goods_receipt_items(id,goods_receipt_id,purchase_order_item_id,variant_id,received_quantity,accepted_quantity,quarantine_quantity,rejected_quantity,unit_cost_toman) VALUES(${x.id}::uuid,${id}::uuid,${x.po_item_id??null}::uuid,${x.variant_id}::uuid,${x.received},${x.accepted},${x.quarantine},${x.rejected},${x.unit_cost_toman})`.execute(ex);}

 async purchaseOrders(allowed:string[]|null){return (await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_orders WHERE (${allowed}::uuid[] IS NULL OR warehouse_id=ANY(${allowed}::uuid[])) ORDER BY created_at DESC LIMIT 500`.execute(this.db)).rows;}
 async purchaseOrder(id:string):Promise<ProcurementItemsAggregate|null>{const h=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_orders WHERE id=${id}::uuid`.execute(this.db)).rows[0];if(!h)return null;const items=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_order_items WHERE purchase_order_id=${id}::uuid ORDER BY variant_id`.execute(this.db)).rows;return {...h,items};}
 async purchaseOrderForUpdate(ex:DatabaseExecutor,id:string):Promise<ProcurementItemsAggregate|null>{const h=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_orders WHERE id=${id}::uuid FOR UPDATE`.execute(ex)).rows[0];if(!h)return null;const items=(await sql<Record<string,unknown>>`SELECT * FROM procurement.purchase_order_items WHERE purchase_order_id=${id}::uuid ORDER BY variant_id FOR UPDATE`.execute(ex)).rows;return {...h,items};}
 async createPurchaseOrder(ex:DatabaseExecutor,i:{id:string;number:string;supplierId:string;warehouseId:string;requestId?:string;expectedAt?:string;createdBy?:string;items:Array<{id:string;variant_id:string;quantity:number;unit_cost_toman:number;discount_toman:number;tax_toman:number}>}){const subtotal=i.items.reduce((s,x)=>s+x.quantity*x.unit_cost_toman,0),discount=i.items.reduce((s,x)=>s+x.discount_toman,0),tax=i.items.reduce((s,x)=>s+x.tax_toman,0),total=subtotal-discount+tax;await sql`INSERT INTO procurement.purchase_orders(id,po_number,supplier_id,warehouse_id,purchase_request_id,expected_at,created_by,subtotal_toman,discount_toman,additional_cost_toman,total_toman) VALUES(${i.id}::uuid,${i.number},${i.supplierId}::uuid,${i.warehouseId}::uuid,${i.requestId??null}::uuid,${i.expectedAt??null}::timestamptz,${i.createdBy??null}::uuid,${subtotal},${discount},0,${total})`.execute(ex);for(const x of i.items)await sql`INSERT INTO procurement.purchase_order_items(id,purchase_order_id,variant_id,ordered_quantity,unit_cost_toman,discount_toman,tax_toman) VALUES(${x.id}::uuid,${i.id}::uuid,${x.variant_id}::uuid,${x.quantity},${x.unit_cost_toman},${x.discount_toman},${x.tax_toman})`.execute(ex);}
 async updatePOStatus(ex:DatabaseExecutor,id:string,status:string,expected:number,actorId?:string,reason?:string){const r=await sql`UPDATE procurement.purchase_orders SET status=${status},submitted_at=CASE WHEN ${status}='submitted' THEN now() ELSE submitted_at END,approved_at=CASE WHEN ${status}='approved' THEN now() ELSE approved_at END,approved_by=CASE WHEN ${status}='approved' THEN ${actorId??null}::uuid ELSE approved_by END,sent_at=CASE WHEN ${status}='sent' THEN now() ELSE sent_at END,closed_at=CASE WHEN ${status}='closed' THEN now() ELSE closed_at END,cancellation_reason=CASE WHEN ${status}='cancelled' THEN ${reason??null} ELSE cancellation_reason END,version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','سفارش خرید همزمان تغییر کرده است.');}
 async incrementReceived(ex:DatabaseExecutor,poItemId:string,q:number){const r=await sql`UPDATE procurement.purchase_order_items SET received_quantity=received_quantity+${q} WHERE id=${poItemId}::uuid AND received_quantity+cancelled_quantity+${q}<=ordered_quantity`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('PO_OVER_RECEIPT','مقدار دریافت از مقدار قابل دریافت سفارش بیشتر است.');}
 async decrementReceived(ex:DatabaseExecutor,poItemId:string,q:number){const r=await sql`UPDATE procurement.purchase_order_items SET received_quantity=received_quantity-${q} WHERE id=${poItemId}::uuid AND received_quantity>=${q}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('PO_RECEIPT_CONFLICT','مقدار دریافتی سفارش قابل برگشت نیست.');}
 async refreshPOReceiptStatus(ex:DatabaseExecutor,poId:string){await sql`UPDATE procurement.purchase_orders p SET status=CASE WHEN NOT EXISTS(SELECT 1 FROM procurement.purchase_order_items i WHERE i.purchase_order_id=p.id AND i.received_quantity+i.cancelled_quantity<i.ordered_quantity) THEN 'received' WHEN EXISTS(SELECT 1 FROM procurement.purchase_order_items i WHERE i.purchase_order_id=p.id AND i.received_quantity>0) THEN 'partially_received' ELSE 'sent' END,version=version+1,updated_at=now() WHERE p.id=${poId}::uuid AND p.status IN ('sent','partially_received','received')`.execute(ex);}
 async cancelPORemainder(ex:DatabaseExecutor,poId:string){await sql`UPDATE procurement.purchase_order_items SET cancelled_quantity=ordered_quantity-received_quantity WHERE purchase_order_id=${poId}::uuid AND received_quantity+cancelled_quantity<ordered_quantity`.execute(ex);}
 async assertPOClosable(ex:DatabaseExecutor,poId:string){const r=await sql<{open_receipts:number;draft_costs:number}>`SELECT (SELECT COUNT(*)::int FROM procurement.goods_receipts WHERE purchase_order_id=${poId}::uuid AND status IN ('draft','submitted')) open_receipts,(SELECT COUNT(*)::int FROM procurement.landed_costs WHERE purchase_order_id=${poId}::uuid AND status='draft') draft_costs`.execute(ex);const row=r.rows[0];if(!row)throw new DomainError('PO_CLOSABILITY_CHECK_FAILED','بررسی قابلیت بستن سفارش خرید ناموفق بود.');if(Number(row.open_receipts)>0)throw new DomainError('PO_OPEN_RECEIPTS','سفارش خرید رسید باز دارد.');if(Number(row.draft_costs)>0)throw new DomainError('PO_DRAFT_LANDED_COST','هزینه جانبی پیش‌نویس باید قبل از بستن سفارش تعیین تکلیف شود.');}

 async receipts(allowed:string[]|null){return (await sql<Record<string,unknown>>`SELECT * FROM procurement.goods_receipts WHERE (${allowed}::uuid[] IS NULL OR warehouse_id=ANY(${allowed}::uuid[])) ORDER BY created_at DESC LIMIT 500`.execute(this.db)).rows;}
 async receipt(id:string):Promise<ProcurementItemsAggregate|null>{const h=(await sql<Record<string,unknown>>`SELECT * FROM procurement.goods_receipts WHERE id=${id}::uuid`.execute(this.db)).rows[0];if(!h)return null;const items=(await sql<Record<string,unknown>>`SELECT * FROM procurement.goods_receipt_items WHERE goods_receipt_id=${id}::uuid ORDER BY variant_id`.execute(this.db)).rows;return {...h,items};}
 async receiptForUpdate(ex:DatabaseExecutor,id:string):Promise<ProcurementItemsAggregate|null>{const h=(await sql<Record<string,unknown>>`SELECT * FROM procurement.goods_receipts WHERE id=${id}::uuid FOR UPDATE`.execute(ex)).rows[0];if(!h)return null;const items=(await sql<Record<string,unknown>>`SELECT * FROM procurement.goods_receipt_items WHERE goods_receipt_id=${id}::uuid ORDER BY variant_id FOR UPDATE`.execute(ex)).rows;return {...h,items};}
 async createReceipt(ex:DatabaseExecutor,i:{id:string;number:string;poId?:string;supplierId:string;warehouseId:string;createdBy?:string;items:Array<{id:string;po_item_id?:string;variant_id:string;received:number;accepted:number;quarantine:number;rejected:number;unit_cost_toman:number}>}){await sql`INSERT INTO procurement.goods_receipts(id,receipt_number,purchase_order_id,supplier_id,warehouse_id,created_by) VALUES(${i.id}::uuid,${i.number},${i.poId??null}::uuid,${i.supplierId}::uuid,${i.warehouseId}::uuid,${i.createdBy??null}::uuid)`.execute(ex);for(const x of i.items)await sql`INSERT INTO procurement.goods_receipt_items(id,goods_receipt_id,purchase_order_item_id,variant_id,received_quantity,accepted_quantity,quarantine_quantity,rejected_quantity,unit_cost_toman) VALUES(${x.id}::uuid,${i.id}::uuid,${x.po_item_id??null}::uuid,${x.variant_id}::uuid,${x.received},${x.accepted},${x.quarantine},${x.rejected},${x.unit_cost_toman})`.execute(ex);}
 async updateReceiptStatus(ex:DatabaseExecutor,id:string,status:string,expected:number,actorId?:string,reason?:string){const r=await sql`UPDATE procurement.goods_receipts SET status=${status},received_at=CASE WHEN ${status}='submitted' THEN COALESCE(received_at,now()) ELSE received_at END,posted_at=CASE WHEN ${status}='posted' THEN now() ELSE posted_at END,posted_by=CASE WHEN ${status}='posted' THEN ${actorId??null}::uuid ELSE posted_by END,reversed_at=CASE WHEN ${status}='reversed' THEN now() ELSE reversed_at END,reversal_reason=CASE WHEN ${status}='reversed' THEN ${reason??null} ELSE reversal_reason END,version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','رسید کالا همزمان تغییر کرده است.');}

 async landedCosts(allowed:string[]|null){return (await sql<Record<string,unknown>>`SELECT lc.* FROM procurement.landed_costs lc LEFT JOIN procurement.goods_receipts gr ON gr.id=lc.goods_receipt_id LEFT JOIN procurement.purchase_orders po ON po.id=lc.purchase_order_id WHERE (${allowed}::uuid[] IS NULL OR COALESCE(gr.warehouse_id,po.warehouse_id)=ANY(${allowed}::uuid[])) ORDER BY lc.created_at DESC LIMIT 500`.execute(this.db)).rows;}
 async landedCost(id:string):Promise<ProcurementAllocationsAggregate|null>{const h=(await sql<Record<string,unknown>>`SELECT lc.*,COALESCE(gr.warehouse_id,po.warehouse_id) AS warehouse_id FROM procurement.landed_costs lc LEFT JOIN procurement.goods_receipts gr ON gr.id=lc.goods_receipt_id LEFT JOIN procurement.purchase_orders po ON po.id=lc.purchase_order_id WHERE lc.id=${id}::uuid`.execute(this.db)).rows[0];if(!h)return null;const a=(await sql<Record<string,unknown>>`SELECT * FROM procurement.landed_cost_allocations WHERE landed_cost_id=${id}::uuid ORDER BY goods_receipt_item_id`.execute(this.db)).rows;return {...h,allocations:a};}
 async landedCostForUpdate(ex:DatabaseExecutor,id:string):Promise<ProcurementAllocationsAggregate|null>{const h=(await sql<Record<string,unknown>>`SELECT * FROM procurement.landed_costs WHERE id=${id}::uuid FOR UPDATE`.execute(ex)).rows[0];if(!h)return null;const a=(await sql<Record<string,unknown>>`SELECT * FROM procurement.landed_cost_allocations WHERE landed_cost_id=${id}::uuid ORDER BY goods_receipt_item_id`.execute(ex)).rows;return {...h,allocations:a};}
 async createLandedCost(ex:DatabaseExecutor,i:{id:string;reference:string;poId?:string;receiptId?:string;costType:string;amount:number;method:string;createdBy?:string}){await sql`INSERT INTO procurement.landed_costs(id,reference_number,purchase_order_id,goods_receipt_id,cost_type,amount_toman,allocation_method,created_by) VALUES(${i.id}::uuid,${i.reference},${i.poId??null}::uuid,${i.receiptId??null}::uuid,${i.costType},${i.amount},${i.method},${i.createdBy??null}::uuid)`.execute(ex);}
 async allocationCandidates(ex:DatabaseExecutor,landed:Record<string,unknown>){const receipt=landed.goods_receipt_id?String(landed.goods_receipt_id):null,po=landed.purchase_order_id?String(landed.purchase_order_id):null;return (await sql<Record<string,unknown>>`SELECT gri.id,gri.received_quantity,gri.accepted_quantity,gri.quarantine_quantity,gri.unit_cost_toman FROM procurement.goods_receipt_items gri JOIN procurement.goods_receipts gr ON gr.id=gri.goods_receipt_id WHERE gr.status='posted' AND ((${receipt}::uuid IS NOT NULL AND gr.id=${receipt}::uuid) OR (${receipt}::uuid IS NULL AND ${po}::uuid IS NOT NULL AND gr.purchase_order_id=${po}::uuid)) ORDER BY gri.id`.execute(ex)).rows;}
 async replaceAllocations(ex:DatabaseExecutor,id:string,rows:Array<{goods_receipt_item_id:string;allocated_amount_toman:number}>){await sql`DELETE FROM procurement.landed_cost_allocations WHERE landed_cost_id=${id}::uuid`.execute(ex);for(const x of rows)await sql`INSERT INTO procurement.landed_cost_allocations(id,landed_cost_id,goods_receipt_item_id,allocated_amount_toman) VALUES(gen_random_uuid(),${id}::uuid,${x.goods_receipt_item_id}::uuid,${x.allocated_amount_toman})`.execute(ex);}
 async finalizeLandedCost(ex:DatabaseExecutor,id:string,expected:number){const r=await sql`UPDATE procurement.landed_costs SET status='finalized',finalized_at=now(),version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected} AND status='draft'`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','هزینه جانبی قابل نهایی‌سازی نیست یا همزمان تغییر کرده است.');}
 async addPOAdditionalCost(ex:DatabaseExecutor,poId:string,amount:number){await sql`UPDATE procurement.purchase_orders SET additional_cost_toman=additional_cost_toman+${amount},total_toman=total_toman+${amount},version=version+1,updated_at=now() WHERE id=${poId}::uuid`.execute(ex);}

 async invoices(allowed:string[]|null){return (await sql<Record<string,unknown>>`SELECT si.* FROM procurement.supplier_invoices si LEFT JOIN procurement.purchase_orders po ON po.id=si.purchase_order_id WHERE (${allowed}::uuid[] IS NULL OR po.id IS NULL OR po.warehouse_id=ANY(${allowed}::uuid[])) ORDER BY si.created_at DESC LIMIT 500`.execute(this.db)).rows;}
 async createInvoice(ex:DatabaseExecutor,i:{id:string;supplierId:string;poId?:string;invoiceNumber:string;invoiceDate:string;amount:number}){await sql`INSERT INTO procurement.supplier_invoices(id,supplier_id,purchase_order_id,invoice_number,invoice_date,amount_toman) VALUES(${i.id}::uuid,${i.supplierId}::uuid,${i.poId??null}::uuid,${i.invoiceNumber},${i.invoiceDate}::date,${i.amount})`.execute(ex);}
 async invoiceForUpdate(ex:DatabaseExecutor,id:string){return (await sql<Record<string,unknown>>`SELECT * FROM procurement.supplier_invoices WHERE id=${id}::uuid FOR UPDATE`.execute(ex)).rows[0]??null;}
 async updateInvoiceStatus(ex:DatabaseExecutor,id:string,status:string,expected:number,reason?:string){const r=await sql`UPDATE procurement.supplier_invoices SET status=${status},review_note=COALESCE(${reason??null},review_note),version=version+1,updated_at=now() WHERE id=${id}::uuid AND version=${expected}`.execute(ex);if(Number(r.numAffectedRows)!==1)throw new DomainError('VERSION_CONFLICT','فاکتور همزمان تغییر کرده است.');}
}
