import { Inject,Injectable } from '@nestjs/common';import { Kysely,sql } from 'kysely';import { KYSELY_DB } from '../../../platform/database/database.tokens';import { DatabaseSchema } from '../../../platform/database/database.types';import { DatabaseExecutor } from '../../../platform/database/transaction-manager';
@Injectable() export class ConfigurationRepository{constructor(@Inject(KYSELY_DB)private readonly db:Kysely<DatabaseSchema>){}
 async definitions(){return (await sql<any>`SELECT k.*,COALESCE(v.value,k.default_value) resolved_value,COALESCE(v.version,0) version,v.effective_from FROM configuration.configuration_keys k LEFT JOIN configuration.configuration_values v ON v.key=k.key AND v.scope_type='global' AND v.scope_id IS NULL AND v.effective_to IS NULL ORDER BY k.key`.execute(this.db)).rows;}
 async key(key:string,scopeType='global',scopeId:string|null=null,ex:DatabaseExecutor=this.db,lock=false){const q=lock?sql<any>`SELECT k.*,COALESCE(v.value,k.default_value) resolved_value,COALESCE(v.version,0) version,v.id value_id,v.effective_from FROM configuration.configuration_keys k LEFT JOIN configuration.configuration_values v ON v.key=k.key AND v.scope_type=${scopeType} AND v.scope_id IS NOT DISTINCT FROM ${scopeId}::uuid AND v.effective_to IS NULL WHERE k.key=${key} FOR UPDATE OF k`:sql<any>`SELECT k.*,COALESCE(v.value,k.default_value) resolved_value,COALESCE(v.version,0) version,v.id value_id,v.effective_from FROM configuration.configuration_keys k LEFT JOIN configuration.configuration_values v ON v.key=k.key AND v.scope_type=${scopeType} AND v.scope_id IS NOT DISTINCT FROM ${scopeId}::uuid AND v.effective_to IS NULL WHERE k.key=${key}`;return (await q.execute(ex)).rows[0]??null;}
 async history(key:string){return (await sql<any>`SELECT * FROM configuration.configuration_values WHERE key=${key} ORDER BY version DESC LIMIT 100`.execute(this.db)).rows;}
 async applyValue(ex:DatabaseExecutor,input:{id:string;key:string;scopeType:string;scopeId:string|null;value:unknown;actorId:string;reason:string;changeRequestId?:string|null;effectiveFrom?:Date|null}){const cur=await this.key(input.key,input.scopeType,input.scopeId,ex,true);if(!cur)return null;const next=Number(cur.version)+1;await sql`UPDATE configuration.configuration_values SET effective_to=now() WHERE key=${input.key} AND scope_type=${input.scopeType} AND scope_id IS NOT DISTINCT FROM ${input.scopeId}::uuid AND effective_to IS NULL`.execute(ex);await sql`INSERT INTO configuration.configuration_values(id,key,scope_type,scope_id,value,version,effective_from,changed_by,change_request_id,reason) VALUES(${input.id}::uuid,${input.key},${input.scopeType},${input.scopeId}::uuid,${JSON.stringify(input.value)}::jsonb,${next},${input.effectiveFrom??new Date()},${input.actorId}::uuid,${input.changeRequestId??null}::uuid,${input.reason})`.execute(ex);return{...cur,resolved_value:input.value,version:next,id:input.id};}
 async createChange(ex:DatabaseExecutor,i:any){await sql`INSERT INTO configuration.change_requests(id,key,scope_type,scope_id,proposed_value,reason,status,effective_from,requested_by) VALUES(${i.id}::uuid,${i.key},${i.scopeType},${i.scopeId}::uuid,${JSON.stringify(i.value)}::jsonb,${i.reason},'submitted',${i.effectiveFrom??null},${i.actorId}::uuid)`.execute(ex);return this.changeById(i.id,ex);}
 async changeById(id:string,ex:DatabaseExecutor=this.db,lock=false){const q=lock?sql<any>`SELECT * FROM configuration.change_requests WHERE id=${id}::uuid FOR UPDATE`:sql<any>`SELECT * FROM configuration.change_requests WHERE id=${id}::uuid`;return (await q.execute(ex)).rows[0]??null;}
 async changes(status?:string){return (await (status?sql<any>`SELECT * FROM configuration.change_requests WHERE status=${status} ORDER BY created_at DESC`:sql<any>`SELECT * FROM configuration.change_requests ORDER BY created_at DESC LIMIT 200`).execute(this.db)).rows;}
 async transition(ex:DatabaseExecutor,id:string,from:string[],to:string,actorId:string,reason?:string|null,scheduledFor?:Date|null){const r=await sql<any>`UPDATE configuration.change_requests SET status=${to},reviewed_by=CASE WHEN ${to} IN ('approved','rejected') THEN ${actorId}::uuid ELSE reviewed_by END,decision_reason=COALESCE(${reason??null},decision_reason),scheduled_for=COALESCE(${scheduledFor??null},scheduled_for),version=version+1,updated_at=now() WHERE id=${id}::uuid AND status=ANY(${from}::text[]) RETURNING *`.execute(ex);return r.rows[0]??null;}
 async flag(key:string,ex:DatabaseExecutor=this.db,lock=false){const q=lock?sql<any>`SELECT * FROM configuration.feature_flags WHERE key=${key} FOR UPDATE`:sql<any>`SELECT * FROM configuration.feature_flags WHERE key=${key}`;return (await q.execute(ex)).rows[0]??null;}
 async flags(){return (await sql<any>`SELECT * FROM configuration.feature_flags ORDER BY key`.execute(this.db)).rows;}
 async createFlag(ex:DatabaseExecutor,i:any){await sql`INSERT INTO configuration.feature_flags(key,name_fa,flag_type,default_variant,risk_level,created_by,updated_by) VALUES(${i.key},${i.nameFa},${i.flagType},${i.defaultVariant},${i.riskLevel},${i.actorId}::uuid,${i.actorId}::uuid)`.execute(ex);return this.flag(i.key,ex);}
 async patchFlag(ex:DatabaseExecutor,key:string,patch:any,actorId:string){const r=await sql<any>`UPDATE configuration.feature_flags SET name_fa=COALESCE(${patch.nameFa??null},name_fa),default_variant=COALESCE(${patch.defaultVariant??null},default_variant),risk_level=COALESCE(${patch.riskLevel??null},risk_level),updated_by=${actorId}::uuid,version=version+1,updated_at=now() WHERE key=${key} AND status<>'retired' RETURNING *`.execute(ex);return r.rows[0]??null;}
 async mutateFlag(ex:DatabaseExecutor,key:string,input:{status?:string;rollout?:number;targetType?:string|null;targetIds?:string[];actorId:string}){const r=await sql<any>`UPDATE configuration.feature_flags SET status=COALESCE(${input.status??null},status),rollout_percent=COALESCE(${input.rollout??null},rollout_percent),target_type=CASE WHEN ${input.targetType===undefined} THEN target_type ELSE ${input.targetType??null} END,target_ids=CASE WHEN ${input.targetIds===undefined} THEN target_ids ELSE ${JSON.stringify(input.targetIds??[])}::jsonb END,updated_by=${input.actorId}::uuid,version=version+1,updated_at=now() WHERE key=${key} RETURNING *`.execute(ex);return r.rows[0]??null;}
}
