import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';
// @ts-ignore Repository-native design validator
import {validateGrowth} from '../../scripts/validate-step56-customers-growth.mjs';
const read=()=>JSON.parse(readFileSync('docs/13-product-design/step56-customers-growth-wireframes.json','utf8'));
test('56-F complete growth contract',()=>assert.deepEqual(validateGrowth(read()),[]));
const changes:Array<[string,(c:any)=>void]>=[
['surface lost',c=>c.screens.pop()],['operation lost',c=>c.screens[6].operations.pop()],['source omitted',c=>c.sources.pop()],['source forged',c=>c.sources[0].sha256='bad'],['permission widened',c=>c.screens[1].permissions.push('admin.all')],['gap lost',c=>c.sourceGaps=[]],['state lost',c=>c.screens[0].states.pop()],['view lost',c=>c.screens[1].views.pop()],['provenance lost',c=>c.screens[6].operationEvidence.pop()],['G started',c=>c.nextGateStatus='STARTED'],['runtime changed',c=>c.boundary.runtime=true],['mixed campaign enabled',c=>c.screens[6].operationViews[4].executionEnabled=true],['blocked coupon confirm',c=>c.screens[7].operationViews[7].confirmationView='overview'],['blocked customer success',c=>c.screens[0].views.find((v:any)=>v.id==='success').kind='summary'],['Step-Up bypass',c=>c.screens[1].operationViews[2].stepUp=false],['replay altered',c=>c.screens[1].operationViews[2].idempotencyScope=null],['automatic retry',c=>c.screens[10].operationViews[3].recovery='AUTO'],['body version removed',c=>c.screens[6].operationViews[9].bodyExpectedVersion=false],['If-Match invented',c=>c.screens[5].operationViews[5].versionRequired=true],['preview sends',c=>c.invariants.templatePreview='SEND'],['preview gains confirmation',c=>c.screens[11].operationViews[4].confirmation='SAFE_CANCEL_FIRST'],['preview result removed',c=>c.screens[11].operationViews[4].resultView='success'],['delivered retry',c=>c.invariants.notificationRetryStates.push('delivered')],['in-app retry',c=>c.invariants.notificationRetryChannels.push('in_app')],['queue shown delivered',c=>c.invariants.notificationRetryResult='DELIVERED'],['revision replaces active',c=>c.limitations.templateRevisionUpdatesActive=true],['restore publishes',c=>c.invariants.articleRestore='PUBLISH'],['stale protection invented',c=>c.invariants.articleClientStaleWriteProtection=true],['coupon disabled creation',c=>c.invariants.couponInitiallyEnabled=false],['promotion picker enabled',c=>c.invariants.couponPromotionLookup='ENABLED'],['masking guaranteed',c=>c.limitations.rawNotificationDetailMasked=true],['HTML sanitizer claimed',c=>c.limitations.htmlPreviewSanitizedByBackend=true],['guard hidden',c=>c.screens[6].views.find((v:any)=>v.id==='op-10').items=c.screens[6].views.find((v:any)=>v.id==='op-10').items.filter((x:string)=>x!==c.screens[6].operationViews[9].guard)],['required field lost',c=>c.screens[7].operationViews[4].fields.pop()],['review pending',c=>c.review.visual='PENDING']];
for(const [name,change] of changes)test('56-F rejects '+name,()=>{const c=read();change(c);assert.ok(validateGrowth(c).length);});
test('56-F deterministic coverage',()=>{const p=spawnSync(process.execPath,['scripts/generate-step56-customers-growth.mjs','--check'],{encoding:'utf8'});assert.equal(p.status,0,p.stderr);const m=JSON.parse(readFileSync('docs/13-product-design/step56-wireframes/F/manifest.json','utf8'));assert.equal(m.screenCount,16);assert.equal(m.frameCount,488);assert.equal(m.artifacts.length+1,523);});
test('56-F safe cancel before campaign pause',()=>{const svg=readFileSync('docs/13-product-design/step56-wireframes/F/AD-F-07/AD-F-07--320--op-10-confirm--v1.svg','utf8');assert.ok(svg.includes('انصراف'));assert.ok(svg.lastIndexOf('انصراف')<svg.lastIndexOf('توقف کمپین'));});
