import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';
// @ts-ignore Repository-native semantic validator
import {validateOperations} from '../../scripts/validate-step56-pricing-inventory.mjs';
const read=()=>JSON.parse(readFileSync('docs/13-product-design/step56-pricing-inventory-wireframes.json','utf8'));
test('56-D complete operations contract',()=>assert.deepEqual(validateOperations(read()),[]));
const changes:Array<[string,(c:any)=>void]>=[
['surface omitted',c=>c.screens.pop()],['operation omitted',c=>c.screens[0].operations.pop()],['permission widened',c=>c.screens[0].permissions.push('admin.all')],['source forged',c=>c.sources[0].sha256='0'.repeat(64)],['source omitted',c=>c.sources.pop()],['wrong baseline',c=>c.baseline='wrong'],['E started',c=>c.nextGateStatus='STARTED'],['runtime enabled',c=>c.boundary.runtime=true],['inherited gap removed',c=>c.sourceGaps={}],['state omitted',c=>c.screens[0].states.pop()],['view omitted',c=>c.screens[0].views.pop()],['operation authority lost',c=>c.screens[0].operationEvidence.pop()],['Step-Up bypass',c=>c.screens[6].operationViews[0].stepUp=false],['idempotency altered',c=>c.screens[6].operationViews[0].idempotencyScope=null],['version bypass',c=>c.screens[1].operationViews.find((x:any)=>x.versionRequired).versionRequired=false],['unsafe retry',c=>c.screens[0].operationViews[0].recovery='AUTO'],['scope guarantee',c=>c.limitations.uniformWarehouseScopeEnforcement=true],['currency guarantee',c=>c.limitations.currencyFreshPriceCheck=true],['full scope guarantee',c=>c.limitations.currencyCompletePopulation=true],['transfer reserves',c=>c.limitations.transferApprovalReservesStock=true],['partial receive',c=>c.limitations.transferPartialReceive=true],['import status invented',c=>c.limitations.importStatusEndpoint=true],['combined apply',c=>c.limitations.combinedExcelAtomicApply=true],['bulk cap changed',c=>c.invariants.bulkMaxVariants=10000],['preview lifetime changed',c=>c.invariants.previewSeconds=3600],['receipt equation changed',c=>c.invariants.receiptQuantityEquation='accepted=received'],['recovery attempts changed',c=>c.invariants.recoveryMaxAttempts=99],['separation removed',c=>c.invariants.separationOfDuties=[]],['formula accepted',c=>c.invariants.excelRejects=[]],['rule removed',c=>c.rules.pop()],['review pending',c=>c.review.visual='PENDING']];
for(const [name,change] of changes)test('56-D rejects '+name,()=>{const c=read();change(c);assert.ok(validateOperations(c).length);});
test('56-D deterministic frame and trace coverage',()=>{const run=spawnSync(process.execPath,['scripts/generate-step56-pricing-inventory.mjs','--check'],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const m=JSON.parse(readFileSync('docs/13-product-design/step56-wireframes/D/manifest.json','utf8'));assert.equal(m.screenCount,21);assert.equal(m.frameCount,624);assert.equal(m.artifacts.length+1,669);});
test('56-D sensitive confirmation offers cancel before apply',()=>{const svg=readFileSync('docs/13-product-design/step56-wireframes/D/AD-D-03/AD-D-03--320--op-02--v1.svg','utf8');assert.ok(svg.includes('انصراف'));assert.ok(svg.lastIndexOf('انصراف')<svg.lastIndexOf('اعمال تغییرات'));});
