import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';
// @ts-ignore Repository-native semantic validator
import {validateCommerce} from '../../scripts/validate-step56-commerce-operations.mjs';
const read=()=>JSON.parse(readFileSync('docs/13-product-design/step56-commerce-operations-wireframes.json','utf8'));
test('56-E complete commerce contract',()=>assert.deepEqual(validateCommerce(read()),[]));
const changes:Array<[string,(c:any)=>void]>=[
['surface omitted',c=>c.screens.pop()],['operation omitted',c=>c.screens[0].operations.pop()],['permission widened',c=>c.screens[0].permissions.push('admin.all')],['source forged',c=>c.sources[0].sha256='0'.repeat(64)],['source omitted',c=>c.sources.pop()],['wrong baseline',c=>c.baseline='wrong'],['F started',c=>c.nextGateStatus='STARTED'],['runtime enabled',c=>c.boundary.runtime=true],['gap removed',c=>c.sourceGaps={}],['state omitted',c=>c.screens[0].states.pop()],['view omitted',c=>c.screens[0].views.pop()],['provenance lost',c=>c.screens[0].operationEvidence.pop()],['Step-Up bypass',c=>c.screens[2].operationViews[3].stepUp=false],['idempotency removed',c=>c.screens[2].operationViews[3].idempotencyScope=null],['version bypass',c=>c.screens[5].operationViews[1].versionRequired=false],['automatic retry',c=>c.screens[2].operationViews[8].recovery='AUTO'],['blocked GET enabled',c=>c.screens[0].operationViews[0].executionEnabled=true],['blocked POS confirmation',c=>c.screens[10].operationViews[5].confirmationView='overview'],['blocked success displayed',c=>c.screens[0].views.find((v:any)=>v.id==='success').kind='summary'],['blocked state enabled',c=>c.screens[0].states[0].view='overview'],['unknown refund retry',c=>c.invariants.refundRetryFrom.push('unknown')],['processing cancellation',c=>c.invariants.refundCancelFrom.push('processing')],['self approval',c=>c.invariants.refundApproval='ANYONE'],['handover cancellation',c=>c.invariants.shipmentCancelFrom.push('handed_over')],['partial item coverage',c=>c.invariants.returnResolutionCoverage='OPTIONAL'],['request shown paid',c=>c.invariants.afterSalesRefund='PAID'],['replacement shown shipped',c=>c.invariants.replacement='SHIPPED'],['unresolved warranty close',c=>c.invariants.warrantyCloseFrom.push('received')],['uniform scope claimed',c=>c.limitations.uniformWarehouseScopeEnforcement=true],['manual payment success',c=>c.limitations.manualMarkPaid=true],['provider guarantee',c=>c.limitations.universalProviderRefundSupport=true],['refund amount field lost',c=>c.screens[2].operationViews[2].fields.pop()],['guard hidden',c=>c.screens[2].views.find((v:any)=>v.id==='op-09').items.pop()],['cancel omitted',c=>c.screens[2].operationViews[8].confirmation='NONE'],['review pending',c=>c.review.visual='PENDING']];
for(const [name,change] of changes)test('56-E rejects '+name,()=>{const c=read();change(c);assert.ok(validateCommerce(c).length);});
test('56-E deterministic artifact coverage',()=>{const p=spawnSync(process.execPath,['scripts/generate-step56-commerce-operations.mjs','--check'],{encoding:'utf8'});assert.equal(p.status,0,p.stderr);const m=JSON.parse(readFileSync('docs/13-product-design/step56-wireframes/E/manifest.json','utf8'));assert.equal(m.screenCount,11);assert.equal(m.frameCount,368);assert.equal(m.artifacts.length+1,393);});
test('56-E refund retry keeps cancel before sensitive action',()=>{const svg=readFileSync('docs/13-product-design/step56-wireframes/E/AD-E-03/AD-E-03--320--op-09--v1.svg','utf8');assert.ok(svg.includes('انصراف'));assert.ok(svg.lastIndexOf('انصراف')<svg.lastIndexOf('تلاش مجددِ ناموفق'));assert.ok(svg.includes('فقط ناموفق'));});
