import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';
// @ts-ignore Repository-native audit module
import {auditUnion,loadInputs,auditManifests} from '../../scripts/step56-final-audit.mjs';
// @ts-ignore Repository-native validator
import {validateFinalAudit} from '../../scripts/validate-step56-final-audit.mjs';
const read=()=>JSON.parse(readFileSync('docs/13-product-design/step56-final-audit.json','utf8'));
test('56-H union and canonical contract',()=>assert.deepEqual(validateFinalAudit(read()),[]));
const changes:Array<[string,(x:any)=>void]>=[
['missing gate',x=>x.gates.pop()],['duplicate gate',x=>x.gates[5]=x.gates[4]],['unowned surface',x=>x.gates[5].screens.pop()],['duplicate surface',x=>x.gates[5].screens[1]=x.gates[5].screens[0]],['duplicate operation',x=>x.gates[5].screens[0].operations.push(x.gates[0].screens[0].operations[0])],['operation missing',x=>x.gates[5].screens[0].operations.pop()],['lost state',x=>x.gates[1].screens[0].states.pop()],['dangling state',x=>x.gates[1].screens[0].states[0].view='missing'],['duplicate view',x=>x.gates[1].screens[0].views.push(x.gates[1].screens[0].views[0])],['lost facet',x=>x.gates[1].screens[0].requiredFacets.pop()],['widened permission',x=>x.gates[1].screens[0].operationViews[0].permissionClaims.runtime=['admin.all']],['dangling shared view',x=>x.gates[0].screens[0].operationViews[0].view='AD-B-07/missing'],['blocked dashboard executable',x=>x.gates[0].screens[2].operationViews[0].executionEnabled=true],['blocked dashboard success',x=>x.gates[0].screens[2].operationViews[0].resultView='success'],['blocked RBAC presented as form',x=>{const s=x.gates[5].screens[15],o=s.operationViews.find((v:any)=>v.executionAuthority.startsWith('NO_ACTION'));s.views.find((v:any)=>v.id===o.view).kind='form';}],['foundation gaps lost',x=>x.gates[5].sourceGaps=[]],['journey operation unknown',x=>x.a.journeys[0].operations.push('GET /invented')],['journey owner unlinked',x=>x.a.journeys[0].operations.push('GET /admin/finance/dashboard')],['runtime certification',x=>x.gates[0].review.runtimeAccessibilityCertified=true],['review widths lost',x=>x.gates[1].review.widths.pop()],['remote design authority',x=>x.gates[1].canonicalSource='figma'],['gate not complete',x=>x.gates[5].status='PENDING']];
for(const [name,change] of changes)test('56-H rejects '+name,()=>{const x=loadInputs();change(x);assert.throws(()=>auditUnion(x));});
for(const [name,change] of [
['runtime released',(c:any)=>c.runtimeRelease='READY'],['step57 started',(c:any)=>c.nextStepStatus='STARTED'],['gap waived',(c:any)=>c.sourceGaps.pop()],['false CI head',(c:any)=>c.transport.gates[0].ci.head[0].head='forged'],['missing handoff',(c:any)=>c.handoffs.pop()],['invented closure counts',(c:any)=>c.counts.operations=531]
] as Array<[string,(x:any)=>void]>)test('56-H rejects '+name,()=>{const c=read();change(c);assert.ok(validateFinalAudit(c).length);});
test('56-H all frame manifests and inherited visual evidence',()=>{const m=auditManifests(loadInputs().gates);assert.equal(m.length,6);assert.ok(m.every((g:any)=>g.review.samples.length>0));});
test('56-H deterministic artifact check',()=>{const p=spawnSync(process.execPath,['scripts/generate-step56-final-audit.mjs','--check'],{encoding:'utf8'});assert.equal(p.status,0,p.stderr);});
