import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';
// @ts-ignore Repository-native validator module
import {validateCatalog} from '../../scripts/validate-step56-catalog-media.mjs';
const read=()=>JSON.parse(readFileSync('docs/13-product-design/step56-catalog-media-wireframes.json','utf8'));
test('56-C valid complete catalog contract',()=>assert.deepEqual(validateCatalog(read()),[]));
for(const [name,change] of [
['lost surface',(c:any)=>c.screens.pop()],['new permission',(c:any)=>c.screens[0].permissions.push('catalog.all')],['lost state',(c:any)=>c.screens[1].states.pop()],['lost actor',(c:any)=>c.screens[0].actors.pop()],['missing source',(c:any)=>c.sources.pop()],['source forgery',(c:any)=>c.sources[0].sha256='0'.repeat(64)],['wrong handoff',(c:any)=>c.baseline='invented'],['D started',(c:any)=>c.nextGateStatus='IN_PROGRESS'],['runtime change',(c:any)=>c.boundary.runtime=true],['restore publishes',(c:any)=>c.invariants.productRestoreState='published'],['restore sells',(c:any)=>c.invariants.productRestoreSalesEnabled=true],['unconditional price',(c:any)=>c.invariants.publishPriceCondition='ALWAYS'],['delete referenced media',(c:any)=>c.invariants.mediaDeleteWhenReferenced=true],['detach deletes asset',(c:any)=>c.invariants.detachDeletesAsset=true],['complete activates',(c:any)=>c.invariants.mediaCompleteState='active'],['multiple primary',(c:any)=>c.invariants.primaryMediaMaximum=2],['drag only',(c:any)=>c.invariants.reorderAlternatives=[]],['unsupported mime',(c:any)=>c.invariants.mediaMimeTypes.push('image/svg+xml')],['larger upload',(c:any)=>c.invariants.mediaMaxBytes=100000000],['StepUp bypass',(c:any)=>c.invariants.salesApplyStepUp=false],['fresh count claim',(c:any)=>c.limitations.previewFreshRecount=true],['requester binding claim',(c:any)=>c.limitations.previewRequesterBinding=true],['retry mutation',(c:any)=>c.limitations.automaticMutationRetry=true],['history invention',(c:any)=>c.limitations.catalogHistoryEndpoint=true],['byte verification claim',(c:any)=>c.limitations.storageByteVerification=true],['lost view',(c:any)=>c.screens[6].views.pop()],['operation view authority',(c:any)=>c.screens[7].operationViews[0].stepUp=false],['review pending',(c:any)=>c.review.visual='PENDING']
] as const)test('56-C rejects '+name,()=>{const c=read();change(c);assert.ok(validateCatalog(c).length);});
test('56-C all generated evidence remains deterministic',()=>{const r=spawnSync(process.execPath,['scripts/generate-step56-catalog-media.mjs','--check'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);const m=JSON.parse(readFileSync('docs/13-product-design/step56-wireframes/C/manifest.json','utf8'));assert.equal(m.frameCount,114);assert.equal(m.screenCount,8);});
test('56-C reorder includes non-drag alternatives',()=>{const s=readFileSync('docs/13-product-design/step56-wireframes/C/AD-C-04/AD-C-04--320--reorder--v1.svg','utf8');assert.ok(s.includes('بالاتر')&&s.includes('پایین‌تر'));});
